/* Mini Crossword — clue-bank. AUTO-SEEDED, then hand-extended.
 *
 * One clue per 5-letter answer word. Any grid that uses a word inherits its
 * clue here, so generated grids clue themselves. To scale Crossword, just add
 * more WORD: "clue" lines below (keep words UPPERCASE, alphabetical).
 *
 * A puzzle in puzzles.js may still override any clue locally for flavor — the
 * engine prefers a puzzle's own clue and falls back to this bank.
 *
 * Seeded from puzzles.js by tools/grid-generator/build-cluebank.js.
 * Re-run that script to refresh the seeded entries.
 */
window.CrosswordClues = {
  ADAGE: "Old saying",
  ADEPT: "Highly skilled",
  AISLE: "Best seat for an easy exit",
  ALIEN: "Sigourney Weaver foe; also a 'Strange Loop' theme",
  ALONE: "By oneself; the soloist's pre-curtain state",
  ALOUD: "How a script first gets voiced at rehearsal",
  ALTER: "Modify, as a costume",
  ANGER: "An 'Inside Out' emotion",
  ANIME: "Japanese animation style",
  ARENA: "Madison Square Garden, broadly",
  AROMA: "Smell of fresh-baked bread",
  ASIDE: "Line delivered to the audience, not the other characters",
  AVAIL: "Use; 'to no ___'",
  AVERT: "Turn aside, as one's gaze",
  BALLS: "Formal dances",
  BLEEP: "What censors do to expletives",
  BOARS: "Tusked pigs",
  BUSES: "City transit fleet",
  CANOE: "Single-paddle watercraft",
  CARVE: "Turkey-day verb",
  CHIDE: "Scold mildly",
  CHILE: "South American country with a famously long coast",
  COVET: "Desire enviously",
  CREPE: "Thin French pancake",
  DEARS: "Address from a sympathetic monologue: 'my ___'",
  DECOR: "A room's styling",
  DEEPS: "Ocean depths, poetically",
  DELAY: "Hold up; postpone",
  DENSE: "Slow on the uptake; also, packed",
  DETER: "Discourage; turn away",
  DICED: "Cut into small cubes",
  DOING: "Currently performing (gerund)",
  DOUBT: "Uncertainty; Shanley's 2004 Best Play",
  DYNES: "Units of force, in physics class",
  EAGER: "Keen, like a stage-door fan",
  EARLY: "Punctuality, posh",
  EAVES: "Roof overhangs",
  EDGED: "Bordered, as with trim",
  EDGES: "Sharpens (a knife)",
  EGRET: "White wading bird in 'The Boy Friend'? No, just a wading bird",
  ELEGY: "Mournful poem",
  EMAIL: "Modern equivalent of a fan letter",
  ENSUE: "Follow as a result",
  ENTER: "Stage direction at the top of a script",
  ESTER: "Banana-scented organic compound (acid + alcohol)",
  EVADE: "Slip past, as a question",
  EVENT: "Premiere or gala",
  EVOKE: "Call to mind",
  FATES: "Greek life-thread trio; 'Hadestown' chorus",
  FENDS: "Wards off",
  FILED: "Submitted, as paperwork",
  GALAS: "Opening-night fundraising events",
  GAMEY: "Wild-tasting, said of meat",
  GHOST: "What the lit ___ light wards off in a dark theater",
  GLEAN: "Pick up, harvest-style",
  GLUED: "Fixated, as on a screen",
  HALES: "Drags forcibly (archaic verb)",
  HAVEN: "Safe place; a theater, for many",
  HERDS: "Cattle groupings",
  HILLY: "Like San Francisco terrain",
  IDEAL: "'An ___ Husband,' Wilde play",
  IDLED: "Sat with the engine running",
  IMBUE: "Saturate (with color, with feeling)",
  INEPT: "Clumsy beyond belief",
  IRATE: "Furious",
  ISSUE: "Magazine edition; or a problem",
  LACED: "Tied up, as sneakers",
  LADED: "Loaded down (archaic)",
  LANCE: "Knight's jousting weapon",
  LAPEL: "Where the corsage goes",
  LAPSE: "Subscription expiry",
  LARGO: "Tempo marking: very slow, broadly",
  LASER: "Focused light beam",
  LAVAS: "Molten flows",
  LIFER: "Career stage professional (or, in prison, a long-termer)",
  LILAC: "Pale-purple bloom",
  LONER: "Solitary type; the Phantom, broadly",
  LUNGE: "Fencer's forward thrust",
  METED: "Dispensed (justice)",
  NERDS: "Mathlete archetypes",
  NOOSE: "Hangman's loop",
  NORMS: "Social conventions",
  OFTEN: "Frequently",
  OKAPI: "Striped-legged giraffe relative",
  OPERA: "The Phantom's haunt",
  ORGAN: "Phantom's instrument of choice; also a body part",
  OVERS: "Cricket bowling stints, broadly",
  PAGES: "Squires-in-training; or what a script has",
  PEEPS: "Marshmallow chicks; or small chick sounds",
  PENAL: "Pertaining to punishment",
  PIANO: "The pit orchestra's anchor",
  PLANT: "Bury (an idea); also a vegetable starter",
  POISE: "Composed bearing on stage",
  POSES: "Stances for a magazine shoot",
  PRESS: "The fourth estate",
  PREYS: "Hunts (homophone of 'prays')",
  PROFS: "Tenured types, informally",
  RALLY: "Political assembly; or a comeback",
  RANGE: "Singer's vocal span",
  RARER: "Less common, comparatively",
  RAVEL: "Composer of 'Boléro'",
  RESTS: "Silent beats in a score",
  RISEN: "What the curtain has, at 8:01",
  RUDER: "More impolite",
  RURAL: "Country, not city",
  SALTS: "Epsom ___, for bath soaking",
  SCABS: "Healing scrapes",
  SCENE: "Each blackout-bounded unit of a play",
  SCOOT: "Move quickly aside",
  SCRIP: "Bit of writing; theater token",
  SEEDS: "Tournament rankings, or what gardeners plant",
  SENDS: "Dispatches, as flowers to a dressing room",
  SENSE: "What audiences make of a Beckett play, hopefully",
  SERGE: "Wool fabric for a sharp suit",
  SINCE: "Ever ___ (from then on)",
  SLASH: "Forward-leaning punctuation: /",
  SLEDS: "Winter rides on a hill",
  SLOTS: "Casino fixtures; also schedule openings",
  SLUGS: "Garden pests, or punches in a stage fight",
  SNAIL: "Slow-moving mollusk",
  SONAR: "Echolocation system",
  SPECS: "Eyeglasses, slangily",
  STAGS: "Bachelor parties (or male deer)",
  STAMP: "Postal sticker; or a foot-strike",
  STRIP: "Sunset ___, the Strip on Broadway? No — a Boulevard",
  SUNUP: "Dawn, casually",
  TERRA: "___ firma, solid ground",
  TERSE: "Curt; minimalist Beckett dialogue",
  THETA: "Greek letter often used in physics formulas",
  TIARA: "Princess-bride headpiece",
  TITLE: "What the marquee announces",
  TONAL: "Pertaining to musical tone or key",
  TRADE: "Swap; also Broadway's industry",
  TRAMP: "Drifter, or a heavy step",
  TRASH: "What stagehands sweep after curtain",
  TRAYS: "Dinner-service holders",
  TRIPS: "Stumbles; or vacations",
  TRUST: "Belief; also, an estate-planning vehicle",
  ULTRA: "Beyond, as a prefix",
  UNDID: "Reversed; cancelled out",
  UNITE: "Bring together, as a cast",
  UNTIE: "Reverse a knot",
  USUAL: "The ___ suspects",
  UTILE: "Useful, archaic",
  YETIS: "Himalayan legends",
};
