/* Mini Crossword — clue-bank EXTRA (hand-written common words).
 *
 * The auto-seeded cluebank.js only knows the ~145 words from the 18 curated
 * puzzles, which interlock so tightly that the generator mostly rebuilds those
 * same puzzles. This file adds common 5-letter words so the generator has a
 * richer vocabulary and can produce genuinely fresh grids that still auto-clue.
 *
 * This file is HAND-MAINTAINED and is never overwritten by the build script
 * (which only regenerates cluebank.js). To scale Crossword further in future
 * months, add more WORD: "clue" pairs below.
 *
 * Merge rule: we only ADD words not already in the bank, so the themed seed
 * clues from the curated puzzles always win over a generic definition here.
 */
(function () {
  window.CrosswordClues = window.CrosswordClues || {};
  var extra = {
    ABOUT: "Approximately",
    AFTER: "Following",
    AGENT: "Actor's representative",
    AISLE: "Best seat for a quick exit",
    ALERT: "On guard",
    ALIKE: "Much the same",
    ALONG: "Together with",
    AMONG: "In the midst of",
    ANGLE: "Corner measure",
    APART: "Separated",
    APPLE: "Orchard fruit",
    ARGUE: "Debate heatedly",
    ARRAY: "Ordered arrangement",
    AWARE: "Conscious of",
    BACON: "Breakfast strip",
    BASIC: "Fundamental",
    BEACH: "Sandy shore",
    BEGIN: "Get started",
    BELOW: "Beneath",
    BLADE: "Knife's edge",
    BLANK: "Empty, as a page",
    BLAST: "Loud explosion",
    BLEND: "Mix smoothly",
    BLOOM: "Flower's opening",
    BOARD: "Plank, or to get on a plane",
    BRAIN: "Thinking organ",
    BRAVE: "Showing courage",
    BREAD: "Bakery staple",
    BREAK: "Take a pause",
    BRICK: "Mason's block",
    BRING: "Carry along",
    BROWN: "Chocolate shade",
    BRUSH: "Painter's tool",
    BUILD: "Construct",
    CABIN: "Rustic getaway",
    CHAIN: "Linked metal loops",
    CHAIR: "Seat with a back",
    CHARM: "Captivating appeal",
    CHART: "Data table",
    CHASE: "Pursue",
    CHEAP: "Inexpensive",
    CHEST: "Treasure container",
    CHIEF: "Top leader",
    CHILD: "Young one",
    CLAIM: "Assert as true",
    CLASS: "Schoolroom group",
    CLEAN: "Free of dirt",
    CLEAR: "Easy to see through",
    CLIMB: "Make one's way up",
    CLOCK: "Time-teller",
    CLOSE: "Shut",
    CLOUD: "Sky puff",
    COACH: "Team's trainer",
    COAST: "Shoreline",
    COUNT: "Tally up",
    COURT: "Tennis venue, or where a judge sits",
    COVER: "Put a lid on",
    CRAFT: "Skilled trade",
    CRASH: "Collide",
    CREAM: "Coffee lightener",
    CRIME: "Lawbreaking act",
    CROWD: "Big gathering",
    DAILY: "Every day",
    DRAFT: "Rough first version",
    DREAM: "Vision in sleep",
    DRESS: "Frock",
    DRINK: "Beverage",
    DRIVE: "Operate a car",
    EAGLE: "Bald national bird",
    EARTH: "Our planet",
    EIGHT: "Number after seven",
    EMPTY: "Containing nothing",
    ENJOY: "Take pleasure in",
    ENTRY: "Way in",
    EQUAL: "The same as",
    EVENT: "Notable happening",
    EVERY: "Each and all",
    EXACT: "Precise",
    FAITH: "Strong belief",
    FANCY: "Elaborate",
    FAVOR: "Kind act",
    FENCE: "Yard boundary",
    FIELD: "Open grassland",
    FIGHT: "Brawl",
    FINAL: "Last",
    FLAME: "Fire's tongue",
    FLASH: "Quick burst of light",
    FLOOR: "Room's bottom",
    FLOUR: "Baking basic",
    FOCUS: "Center of attention",
    FORCE: "Push or pull",
    FRAME: "Picture border",
    FRESH: "Newly made",
    FRONT: "Opposite of back",
    FRUIT: "Apple or pear",
    GIANT: "Enormous",
    GLASS: "Window pane material",
    GRAND: "Magnificent",
    GRAPE: "Vine fruit",
    GRASS: "Lawn cover",
    GREAT: "Excellent",
    GREEN: "Grass color",
    GROUP: "Cluster",
    GUARD: "Protector",
    GUESS: "Estimate",
    GUEST: "Visitor",
    HAPPY: "Joyful",
    HEART: "Love symbol",
    HEAVY: "Weighty",
    HONEY: "Bee's product",
    HORSE: "Stable animal",
    HOTEL: "Travelers' lodging",
    HOUSE: "Dwelling",
    HUMAN: "Person",
    IMAGE: "Picture",
    INDEX: "Book's locator list",
    INNER: "Interior",
    JUDGE: "Court official",
    JUICE: "Squeezed drink",
    KNIFE: "Cutting blade",
    LARGE: "Big",
    LAUGH: "Chuckle",
    LAYER: "One of many tiers",
    LEARN: "Acquire knowledge",
    LEMON: "Sour citrus",
    LEVEL: "Flat and even",
    LIGHT: "Stage illumination",
    LIMIT: "Boundary",
    LOCAL: "Nearby",
    LOWER: "Bring down",
    LOYAL: "Faithful",
    LUCKY: "Fortunate",
    LUNCH: "Midday meal",
    MAGIC: "Stage illusion",
    MAJOR: "Significant",
    MATCH: "Pair up",
    METAL: "Iron or gold",
    MIGHT: "Sheer strength",
    MONEY: "Currency",
    MONTH: "Calendar unit",
    MOTOR: "Engine",
    MOUSE: "Small rodent",
    MOUTH: "Where words come out",
    MOVIE: "Film",
    MUSIC: "Melody and harmony",
    NIGHT: "Opposite of day",
    NOISE: "Loud sound",
    NORTH: "Compass direction",
    NOVEL: "Long work of fiction",
    OCEAN: "Vast saltwater body",
    OFFER: "Propose",
    ORDER: "Sequence, or a restaurant request",
    PAINT: "Artist's color",
    PANEL: "Discussion group",
    PAPER: "Newsprint sheet",
    PARTY: "Festive gathering",
    PEACE: "Absence of war",
    PHONE: "Calling device",
    PHOTO: "Snapshot",
    PLACE: "Location",
    PLANE: "Air traveler's ride",
    PLATE: "Dinner dish",
    POINT: "Sharp tip",
    POWER: "Energy or strength",
    PRESS: "Push down; also the news media",
    PRICE: "Cost",
    PRIDE: "Self-respect; also a lion group",
    PRIZE: "Award",
    PROOF: "Evidence",
    PROUD: "Pleased with oneself",
    QUEEN: "Royal woman; also a chess piece",
    QUICK: "Fast",
    QUIET: "Hushed",
    QUOTE: "Cite, as a line",
    RADIO: "Broadcast receiver",
    RAISE: "Lift up",
    RAPID: "Swift",
    REACH: "Stretch toward",
    READY: "Prepared",
    RIVER: "Flowing waterway",
    ROYAL: "Kingly",
    SHARP: "Keen-edged; also a half-step up in music",
    SHEEP: "Wool provider",
    SHELF: "Wall ledge",
    SHINE: "Gleam",
    SHIRT: "Torso garment",
    SHORT: "Not tall",
    SHOUT: "Yell",
    SIGHT: "Something worth seeing",
    SKILL: "Honed ability",
    SLEEP: "Nighttime rest",
    SMALL: "Little",
    SMART: "Clever",
    SMILE: "Happy expression",
    SMOKE: "Fire's haze",
    SNAKE: "Slithering reptile",
    SOUND: "What ears detect",
    SOUTH: "Compass direction",
    SPACE: "The final frontier",
    SPARE: "Held in reserve",
    SPEAK: "Talk",
    SPEND: "Pay out",
    SPICE: "Seasoning",
    SPLIT: "Divide",
    SPORT: "Athletic game",
    STAIR: "Step in a flight",
    STAND: "Rise to one's feet",
    START: "Begin",
    STATE: "Condition, or one of fifty",
    STEAM: "Boiling vapor",
    STEEL: "Strong alloy",
    STONE: "Rock",
    STORM: "Tempest",
    STORY: "Tale",
    STUDY: "Examine closely",
    STYLE: "Manner of fashion",
    SUGAR: "Sweetener",
    SWEET: "Sugary",
    TABLE: "Dining surface",
    TASTE: "Flavor sense",
    TEACH: "Instruct",
    THEME: "Central idea",
    THICK: "Not thin",
    THINK: "Use the mind",
    THREE: "Number after two",
    THROW: "Toss",
    TIGER: "Striped big cat",
    TODAY: "This very day",
    TOAST: "Browned bread, or a celebratory drink",
    TOOTH: "Mouth biter",
    TOTAL: "Sum",
    TOUCH: "Feel by hand",
    TOWER: "Tall structure",
    TRACK: "Race lane",
    TRAIN: "Railway transport",
    TREAT: "Special indulgence",
    TREND: "Popular direction",
    TRICK: "Sleight of hand",
    TRUCK: "Cargo hauler",
    TRUTH: "What's factual",
    UNCLE: "Parent's brother",
    UNDER: "Beneath",
    UNION: "Joining together",
    UNITY: "Oneness",
    UPPER: "Higher",
    URBAN: "City-related",
    USHER: "One who seats theatergoers",
    VALUE: "Worth",
    VIDEO: "Recorded footage",
    VOICE: "Singer's instrument",
    WAGON: "Pull-along cart",
    WASTE: "Squander",
    WATCH: "Wrist timepiece",
    WATER: "H2O",
    WHEEL: "Round roller",
    WHERE: "In what place",
    WHICH: "What one",
    WHILE: "During",
    WHITE: "Snow's color",
    WHOLE: "Entire",
    WOMAN: "Female adult",
    WORLD: "The globe",
    WORRY: "Fret",
    WORTH: "Value",
    WOUND: "Injury",
    WRITE: "Put words on paper",
    WRONG: "Incorrect",
    YOUNG: "Not old",
    YOUTH: "Early life"
  };
  // Words used by the generated grids in generated.js (clued so those grids
  // resolve fully). Added 2026-06-02 alongside the first generated batch.
  var gridWords = {
    ABATE: "Lessen, as a storm",
    ABUSE: "Mistreat",
    ADORE: "Love deeply",
    AGAPE: "Wide open, as a mouth",
    AGING: "Getting older",
    AMEND: "Revise, as a bill",
    AROSE: "Got up",
    ASSET: "Valuable resource",
    AUDIO: "Sound portion",
    CIVIL: "Polite, or non-military",
    CRAVE: "Yearn for",
    DARTS: "Pub game with a board",
    DEITY: "A god or goddess",
    DIGIT: "A finger, or a single number",
    DRIED: "No longer wet",
    EARED: "Having earlike parts",
    EATEN: "Consumed",
    EERIE: "Spookily strange",
    EPOXY: "Strong two-part glue",
    ERASE: "Rub out",
    ETHER: "Old-time anesthetic",
    ETHIC: "Moral principle",
    FINED: "Made to pay a penalty",
    FLUTE: "Woodwind in the pit orchestra",
    GENUS: "Classification above species",
    GORSE: "Spiny yellow-flowered shrub",
    HEARD: "Listened to",
    HEDGE: "Shrub boundary, or to avoid committing",
    HOCKS: "Pawns, or pig's leg joints",
    HOLDS: "Grips, or a ship's cargo areas",
    INANE: "Silly and pointless",
    KNEEL: "Go down on one's knees",
    LATER: "After a while",
    LEERY: "Wary",
    LEGAL: "Allowed by law",
    LEVEE: "River embankment",
    LIMED: "Treated with a chalky soil dressing",
    MASSE: "Curving billiards shot",
    MOSSY: "Covered in green growth",
    NAMED: "Gave a title to",
    NASAL: "Spoken through the nose",
    NESTS: "Birds' homes",
    NODAL: "Relating to a hub or node",
    OPINE: "Offer a view",
    ORATE: "Deliver a grand speech",
    OTTER: "Playful river mammal",
    PARES: "Trims, as an apple",
    PARSE: "Break down grammatically",
    PIPED: "Conveyed through a tube",
    PSALM: "Biblical song of praise",
    REAMS: "Lots of paper",
    RENDS: "Tears apart",
    RERAN: "Showed again, as an episode",
    REUSE: "Use once more",
    REVUE: "A song-and-sketch stage show",
    RIFFS: "Improvised musical phrases",
    RUSES: "Clever tricks",
    RUSTS: "Corrodes",
    SALLY: "A witty retort, or to set forth",
    SAUNA: "Hot steam room",
    SEALS: "Flippered performers, or closes tight",
    SEDAN: "Four-door car",
    SEEDY: "Run-down and disreputable",
    SEERS: "Fortune-tellers",
    SEVEN: "Lucky number",
    SHIVA: "Hindu deity of destruction",
    SLEET: "Icy rain",
    SLOPS: "Spills messily",
    SORTS: "Arranges by type",
    STARS: "Leading performers, or night-sky lights",
    SUEDE: "Soft napped leather",
    SUSHI: "Rolled rice-and-fish dish",
    TENET: "Core belief",
    TESTS: "Exams",
    TILES: "Bathroom wall squares",
    TONED: "Made more muscular",
    TRACE: "A faint remnant",
    UNLIT: "Dark, like a stage before the show",
    UTTER: "Speak aloud, or complete",
    VAPOR: "Mist or steam",
    VISAS: "Passport stamps for travel"
  };
  [extra, gridWords].forEach(function (obj) {
    for (var w in obj) {
      if (!Object.prototype.hasOwnProperty.call(window.CrosswordClues, w)) {
        window.CrosswordClues[w] = obj[w];
      }
    }
  });
})();
