/* Setlist — daily puzzles.
   The show is given; put its songs in the order they're performed. Each
   `songs` array is the CORRECT running order (the game shuffles it for play).
   Five songs each, chosen with clear act/position anchors (opening number →
   Act One finale → late Act Two) so the order is unambiguous.

   Fact-bound: verify song order before expanding heavily.
*/
window.SetlistPuzzles = [
  { id: 1,  show: "Hamilton",
    songs: ["Alexander Hamilton", "My Shot", "The Schuyler Sisters", "Satisfied", "Non-Stop"] },
  { id: 2,  show: "Wicked",
    songs: ["The Wizard and I", "What Is This Feeling?", "Popular", "Defying Gravity", "For Good"] },
  { id: 3,  show: "Les Misérables",
    songs: ["I Dreamed a Dream", "Castle on a Cloud", "Do You Hear the People Sing?", "One Day More", "Bring Him Home"] },
  { id: 4,  show: "Rent",
    songs: ["Rent", "One Song Glory", "Light My Candle", "La Vie Bohème", "Seasons of Love"] },
  { id: 5,  show: "The Phantom of the Opera",
    songs: ["Think of Me", "The Phantom of the Opera", "The Music of the Night", "Masquerade", "The Point of No Return"] },
  { id: 6,  show: "Hadestown",
    songs: ["Road to Hell", "Wedding Song", "Way Down Hadestown", "Wait for Me", "Doubt Comes In"] },
  { id: 7,  show: "The Sound of Music",
    songs: ["The Sound of Music", "My Favorite Things", "Do-Re-Mi", "Sixteen Going on Seventeen", "Edelweiss"] },
  { id: 8,  show: "Annie",
    songs: ["Maybe", "It's the Hard-Knock Life", "Tomorrow", "Easy Street", "I Don't Need Anything But You"] },
  { id: 9,  show: "Dear Evan Hansen",
    songs: ["Anybody Have a Map?", "Waving Through a Window", "For Forever", "You Will Be Found", "Words Fail"] },
  { id: 10, show: "Chicago",
    songs: ["All That Jazz", "Cell Block Tango", "When You're Good to Mama", "Razzle Dazzle", "Nowadays"] },
  { id: 11, show: "Hairspray",
    songs: ["Good Morning Baltimore", "The Nicest Kids in Town", "Welcome to the 60's", "Big, Blonde and Beautiful", "You Can't Stop the Beat"] },
  { id: 12, show: "The Lion King",
    songs: ["Circle of Life", "I Just Can't Wait to Be King", "Be Prepared", "Hakuna Matata", "Can You Feel the Love Tonight"] },
  { id: 13, show: "Cabaret",
    songs: ["Willkommen", "Don't Tell Mama", "Maybe This Time", "Cabaret", "Finale"] },
  { id: 14, show: "Into the Woods",
    songs: ["Prologue: Into the Woods", "I Know Things Now", "Agony", "It Takes Two", "No One Is Alone"] },
  { id: 15, show: "The Book of Mormon",
    songs: ["Hello!", "Hasa Diga Eebowai", "Turn It Off", "I Believe", "Tomorrow Is a Latter Day"] },
  { id: 16, show: "In the Heights",
    songs: ["In the Heights", "96,000", "Paciencia y Fe", "Blackout", "Finale"] },
  { id: 17, show: "Sweeney Todd",
    songs: ["The Ballad of Sweeney Todd", "The Worst Pies in London", "A Little Priest", "God, That's Good!", "Final Sequence"] },
  { id: 18, show: "Oklahoma!",
    songs: ["Oh, What a Beautiful Mornin'", "The Surrey with the Fringe on Top", "People Will Say We're in Love", "Oklahoma", "Finale Ultimo"] },
  { id: 19, show: "Guys and Dolls",
    songs: ["Fugue for Tinhorns", "A Bushel and a Peck", "If I Were a Bell", "Luck Be a Lady", "Sit Down, You're Rockin' the Boat"] },
  { id: 20, show: "Fiddler on the Roof",
    songs: ["Tradition", "Matchmaker", "If I Were a Rich Man", "Sunrise, Sunset", "Anatevka"] },
  { id: 21, show: "A Chorus Line",
    songs: ["I Hope I Get It", "At the Ballet", "The Music and the Mirror", "What I Did for Love", "One"] },
  { id: 22, show: "Mamma Mia!",
    songs: ["Money, Money, Money", "Mamma Mia", "Dancing Queen", "Voulez-Vous", "The Winner Takes It All"] },
  { id: 23, show: "Jersey Boys",
    songs: ["Sherry", "Big Girls Don't Cry", "Walk Like a Man", "Can't Take My Eyes Off You", "December, 1963 (Oh, What a Night)"] },
  { id: 24, show: "Newsies",
    songs: ["Carrying the Banner", "The World Will Know", "Seize the Day", "Santa Fe", "King of New York"] },
  { id: 25, show: "Jesus Christ Superstar",
    songs: ["Heaven on Their Minds", "Everything's Alright", "I Don't Know How to Love Him", "Gethsemane", "Superstar"] },
  { id: 26, show: "Evita",
    songs: ["Oh What a Circus", "Buenos Aires", "Another Suitcase in Another Hall", "Don't Cry for Me Argentina", "You Must Love Me"] },
  { id: 27, show: "Come From Away",
    songs: ["Welcome to the Rock", "38 Planes", "Me and the Sky", "Something's Missing", "Finale"] },
  { id: 28, show: "Gypsy",
    songs: ["Let Me Entertain You", "Some People", "Everything's Coming Up Roses", "You Gotta Get a Gimmick", "Rose's Turn"] },
  { id: 29, show: "Funny Girl",
    songs: ["I'm the Greatest Star", "People", "Don't Rain on My Parade", "Sadie, Sadie", "The Music That Makes Me Dance"] },
  { id: 30, show: "Pippin",
    songs: ["Magic to Do", "Corner of the Sky", "Morning Glow", "No Time at All", "Finale"] }
];
