/* Setlist — daily puzzles. AUTO-GENERATED from data/shows.js.
   The show is given; put its songs in the order they're performed. Each
   `songs` array is the CORRECT running order (the game shuffles it for play):
   5 songs spread across the show (opening number ... finale), so the order is
   unambiguous.

   Do NOT hand-edit this file. Fix the song order in data/shows.js and re-run
   tools/build-setlists.js.
*/
window.SetlistPuzzles = [
  { id: 1, show: "Hamilton",
    songs: ["Alexander Hamilton","You'll Be Back","Guns and Ships","One Last Time","Who Lives, Who Dies, Who Tells Your Story"] },
  { id: 2, show: "Wicked",
    songs: ["No One Mourns the Wicked","Dancing Through Life","I'm Not That Girl","Wonderful","For Good"] },
  { id: 3, show: "The Phantom of the Opera",
    songs: ["Think of Me","The Phantom of the Opera","The Music of the Night","Masquerade","The Point of No Return"] },
  { id: 4, show: "Les Misérables",
    songs: ["I Dreamed a Dream","Master of the House","Do You Hear the People Sing?","On My Own","Empty Chairs at Empty Tables"] },
  { id: 5, show: "Rent",
    songs: ["Rent","Today 4 U","La Vie Bohème","Without You","Finale B"] },
  { id: 6, show: "Dear Evan Hansen",
    songs: ["Anybody Have a Map?","For Forever","Requiem","To Break in a Glove","So Big / So Small"] },
  { id: 7, show: "The Book of Mormon",
    songs: ["Hello!","Hasa Diga Eebowai","Man Up","Spooky Mormon Hell Dream","Tomorrow Is a Latter Day"] },
  { id: 8, show: "Hadestown",
    songs: ["Road to Hell","Wedding Song","Wait for Me","Epic III","Road to Hell (Reprise)"] },
  { id: 9, show: "Into the Woods",
    songs: ["Prologue: Into the Woods","A Very Nice Prince","Stay with Me","Last Midnight","Children Will Listen"] },
  { id: 10, show: "Sweeney Todd",
    songs: ["The Ballad of Sweeney Todd","My Friends","Pretty Women","A Little Priest","Final Sequence"] },
  { id: 11, show: "Chicago",
    songs: ["All That Jazz","Cell Block Tango","Roxie","Razzle Dazzle","Nowadays"] },
  { id: 12, show: "Cats",
    songs: ["Jellicle Songs for Jellicle Cats","The Old Gumbie Cat","Grizabella the Glamour Cat","Mr. Mistoffelees","The Journey to the Heaviside Layer"] },
  { id: 13, show: "The Lion King",
    songs: ["Circle of Life","Be Prepared","Shadowland","Endless Night","He Lives in You"] },
  { id: 14, show: "Cabaret",
    songs: ["Willkommen","Don't Tell Mama","Money","Tomorrow Belongs to Me","Cabaret"] },
  { id: 15, show: "West Side Story",
    songs: ["Something's Coming","Tonight","Cool","I Feel Pretty","Gee, Officer Krupke"] },
  { id: 16, show: "Fiddler on the Roof",
    songs: ["Tradition","If I Were a Rich Man","To Life","Do You Love Me?","Anatevka"] },
  { id: 17, show: "A Chorus Line",
    songs: ["I Hope I Get It","At the Ballet","The Music and the Mirror","What I Did for Love","One"] },
  { id: 18, show: "The Sound of Music",
    songs: ["The Sound of Music","Do-Re-Mi","The Lonely Goatherd","Climb Ev'ry Mountain","So Long, Farewell"] },
  { id: 19, show: "Oklahoma!",
    songs: ["Oh, What a Beautiful Mornin'","The Surrey with the Fringe on Top","I Cain't Say No","People Will Say We're in Love","Oklahoma"] },
  { id: 20, show: "Guys and Dolls",
    songs: ["Fugue for Tinhorns","I'll Know","I've Never Been in Love Before","Luck Be a Lady","Sit Down, You're Rockin' the Boat"] },
  { id: 21, show: "Annie",
    songs: ["Maybe","Tomorrow","Little Girls","Easy Street","I Don't Need Anything but You"] },
  { id: 22, show: "In the Heights",
    songs: ["In the Heights","96,000","Paciencia y Fe","Carnaval del Barrio","Finale"] },
  { id: 23, show: "Hairspray",
    songs: ["Good Morning Baltimore","Welcome to the 60's","Big, Blonde and Beautiful","Without Love","You Can't Stop the Beat"] },
  { id: 24, show: "Mamma Mia!",
    songs: ["Honey, Honey","Mamma Mia","Voulez-Vous","S.O.S.","Take a Chance on Me"] },
  { id: 25, show: "Six",
    songs: ["Ex-Wives","Don't Lose Ur Head","Get Down","All You Wanna Do","Six"] },
  { id: 26, show: "Newsies",
    songs: ["Santa Fe (Prologue)","The World Will Know","Seize the Day","Santa Fe","Once and for All"] },
  { id: 27, show: "Avenue Q",
    songs: ["It Sucks to Be Me","Purpose","The Internet Is for Porn","There's a Fine, Fine Line","For Now"] },
  { id: 28, show: "Jesus Christ Superstar",
    songs: ["Heaven on Their Minds","Everything's Alright","The Last Supper","Gethsemane","John Nineteen: Forty-One"] },
  { id: 29, show: "Evita",
    songs: ["Oh What a Circus","Another Suitcase in Another Hall","Don't Cry for Me Argentina","High Flying, Adored","The Money Kept Rolling In"] },
  { id: 30, show: "Funny Girl",
    songs: ["I'm the Greatest Star","People","Don't Rain on My Parade","Sadie, Sadie","The Music That Makes Me Dance"] },
  { id: 31, show: "Gypsy",
    songs: ["Let Me Entertain You","Small World","Everything's Coming Up Roses","Together (Wherever We Go)","Rose's Turn"] },
  { id: 32, show: "Pippin",
    songs: ["Magic to Do","Glory","Morning Glow","On the Right Track","Finale"] },
  { id: 33, show: "Come From Away",
    songs: ["Welcome to the Rock","38 Planes","Me and the Sky","Something's Missing","Finale"] },
  { id: 34, show: "Jersey Boys",
    songs: ["Sherry","Big Girls Don't Cry","Walk Like a Man","Can't Take My Eyes Off You","December, 1963 (Oh, What a Night)"] }
];
