/* AUTO-GENERATED by tools/showdown-generator/generate.js — do not edit by hand.
   60 opening-year puzzles appended to the 7 curated ones in matchups.js. */
(function () {
  var GEN = [
  {
    id: 8,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Beetlejuice", value: 2019, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Beetlejuice: 2019.  Grease: 1972." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Miss Saigon", value: 1991, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "Miss Saigon: 1991.  Hamilton: 2015." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Sunset Boulevard", value: 1994, label: "opened" }, note: "Gypsy: 1959.  Sunset Boulevard: 1994." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Sound of Music", value: 1959, label: "opened" }, b: { name: "Dreamgirls", value: 1981, label: "opened" }, note: "The Sound of Music: 1959.  Dreamgirls: 1981." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "A Chorus Line: 1975.  Camelot: 1960." }
    ]
  },
  {
    id: 9,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "South Pacific", value: 1949, label: "opened" }, b: { name: "Man of La Mancha", value: 1965, label: "opened" }, note: "South Pacific: 1949.  Man of La Mancha: 1965." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "Moulin Rouge!", value: 2019, label: "opened" }, note: "Aida: 2000.  Moulin Rouge!: 2019." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Wiz", value: 1975, label: "opened" }, b: { name: "Titanic", value: 1997, label: "opened" }, note: "The Wiz: 1975.  Titanic: 1997." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Carousel", value: 1945, label: "opened" }, b: { name: "Into the Woods", value: 1987, label: "opened" }, note: "Carousel: 1945.  Into the Woods: 1987." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Ragtime", value: 1998, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Ragtime: 1998.  Gypsy: 1959." }
    ]
  },
  {
    id: 10,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "A Funny Thing Happened on the Way to the Forum: 1962.  Hairspray: 2002." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "La Cage aux Folles", value: 1983, label: "opened" }, b: { name: "Carousel", value: 1945, label: "opened" }, note: "La Cage aux Folles: 1983.  Carousel: 1945." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "Guys and Dolls: 1950.  Damn Yankees: 1955." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Frozen", value: 2018, label: "opened" }, b: { name: "Cats", value: 1982, label: "opened" }, note: "Frozen: 2018.  Cats: 1982." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Sound of Music", value: 1959, label: "opened" }, b: { name: "42nd Street", value: 1980, label: "opened" }, note: "The Sound of Music: 1959.  42nd Street: 1980." }
    ]
  },
  {
    id: 11,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Book of Mormon", value: 2011, label: "opened" }, b: { name: "The Color Purple", value: 2005, label: "opened" }, note: "The Book of Mormon: 2011.  The Color Purple: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "The King and I", value: 1951, label: "opened" }, note: "Aida: 2000.  The King and I: 1951." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Ragtime", value: 1998, label: "opened" }, b: { name: "Hello, Dolly!", value: 1964, label: "opened" }, note: "Ragtime: 1998.  Hello, Dolly!: 1964." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Newsies", value: 2012, label: "opened" }, b: { name: "Company", value: 1970, label: "opened" }, note: "Newsies: 2012.  Company: 1970." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, note: "West Side Story: 1957.  Annie Get Your Gun: 1946." }
    ]
  },
  {
    id: 12,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "South Pacific", value: 1949, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "South Pacific: 1949.  Sweeney Todd: 1979." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The King and I", value: 1951, label: "opened" }, b: { name: "Mean Girls", value: 2018, label: "opened" }, note: "The King and I: 1951.  Mean Girls: 2018." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "Company", value: 1970, label: "opened" }, note: "The Producers: 2001.  Company: 1970." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, note: "Moulin Rouge!: 2019.  Bye Bye Birdie: 1960." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "Spring Awakening", value: 2006, label: "opened" }, note: "Waitress: 2016.  Spring Awakening: 2006." }
    ]
  },
  {
    id: 13,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "South Pacific", value: 1949, label: "opened" }, b: { name: "The Color Purple", value: 2005, label: "opened" }, note: "South Pacific: 1949.  The Color Purple: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "A Chorus Line: 1975.  Avenue Q: 2003." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Camelot", value: 1960, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "Camelot: 1960.  Sweeney Todd: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Evita", value: 1979, label: "opened" }, b: { name: "Mame", value: 1966, label: "opened" }, note: "Evita: 1979.  Mame: 1966." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Annie", value: 1977, label: "opened" }, b: { name: "My Fair Lady", value: 1956, label: "opened" }, note: "Annie: 1977.  My Fair Lady: 1956." }
    ]
  },
  {
    id: 14,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Miss Saigon", value: 1991, label: "opened" }, note: "Fun Home: 2015.  Miss Saigon: 1991." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Ragtime", value: 1998, label: "opened" }, note: "The Phantom of the Opera: 1988.  Ragtime: 1998." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "Pippin", value: 1972, label: "opened" }, note: "My Fair Lady: 1956.  Pippin: 1972." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Damn Yankees", value: 1955, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "Damn Yankees: 1955.  Hadestown: 2019." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Rent", value: 1996, label: "opened" }, b: { name: "Mamma Mia!", value: 2001, label: "opened" }, note: "Rent: 1996.  Mamma Mia!: 2001." }
    ]
  },
  {
    id: 15,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Little Night Music", value: 1973, label: "opened" }, b: { name: "Come From Away", value: 2017, label: "opened" }, note: "A Little Night Music: 1973.  Come From Away: 2017." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, b: { name: "The Sound of Music", value: 1959, label: "opened" }, note: "Fiddler on the Roof: 1964.  The Sound of Music: 1959." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Titanic", value: 1997, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Titanic: 1997.  Grease: 1972." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "Crazy for You", value: 1992, label: "opened" }, note: "Hadestown: 2019.  Crazy for You: 1992." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Chicago", value: 1975, label: "opened" }, note: "Cabaret: 1966.  Chicago: 1975." }
    ]
  },
  {
    id: 16,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Bye Bye Birdie: 1960.  Kiss Me, Kate: 1948." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "Fun Home", value: 2015, label: "opened" }, note: "Moulin Rouge!: 2019.  Fun Home: 2015." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "Beetlejuice", value: 2019, label: "opened" }, note: "Next to Normal: 2009.  Beetlejuice: 2019." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "Hello, Dolly!", value: 1964, label: "opened" }, note: "West Side Story: 1957.  Hello, Dolly!: 1964." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Ragtime", value: 1998, label: "opened" }, b: { name: "The Producers", value: 2001, label: "opened" }, note: "Ragtime: 1998.  The Producers: 2001." }
    ]
  },
  {
    id: 17,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mame", value: 1966, label: "opened" }, b: { name: "My Fair Lady", value: 1956, label: "opened" }, note: "Mame: 1966.  My Fair Lady: 1956." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "The Music Man: 1957.  Hairspray: 2002." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Sound of Music", value: 1959, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "The Sound of Music: 1959.  The Phantom of the Opera: 1988." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Pippin", value: 1972, label: "opened" }, b: { name: "A Chorus Line", value: 1975, label: "opened" }, note: "Pippin: 1972.  A Chorus Line: 1975." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "Fun Home: 2015.  Guys and Dolls: 1950." }
    ]
  },
  {
    id: 18,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mean Girls", value: 2018, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "Mean Girls: 2018.  The Phantom of the Opera: 1988." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Avenue Q", value: 2003, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Avenue Q: 2003.  In the Heights: 2008." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Kinky Boots", value: 2013, label: "opened" }, b: { name: "The Producers", value: 2001, label: "opened" }, note: "Kinky Boots: 2013.  The Producers: 2001." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "American Idiot", value: 2010, label: "opened" }, b: { name: "Mamma Mia!", value: 2001, label: "opened" }, note: "American Idiot: 2010.  Mamma Mia!: 2001." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Wicked", value: 2003, label: "opened" }, b: { name: "The Music Man", value: 1957, label: "opened" }, note: "Wicked: 2003.  The Music Man: 1957." }
    ]
  },
  {
    id: 19,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, note: "Mamma Mia!: 2001.  A Funny Thing Happened on the Way to the Forum: 1962." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Sweeney Todd", value: 1979, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "Sweeney Todd: 1979.  Avenue Q: 2003." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Memphis", value: 2009, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Memphis: 2009.  Les Misérables: 1987." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "The Music Man: 1957.  Jersey Boys: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "Matilda", value: 2013, label: "opened" }, note: "A Chorus Line: 1975.  Matilda: 2013." }
    ]
  },
  {
    id: 20,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Titanic", value: 1997, label: "opened" }, note: "Gypsy: 1959.  Titanic: 1997." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Carousel", value: 1945, label: "opened" }, note: "Company: 1970.  Carousel: 1945." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "The Band's Visit", value: 2017, label: "opened" }, note: "A Chorus Line: 1975.  The Band's Visit: 2017." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Pajama Game", value: 1954, label: "opened" }, b: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, note: "The Pajama Game: 1954.  Sunday in the Park with George: 1984." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "A Funny Thing Happened on the Way to the Forum: 1962.  Les Misérables: 1987." }
    ]
  },
  {
    id: 21,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, b: { name: "A Little Night Music", value: 1973, label: "opened" }, note: "Bye Bye Birdie: 1960.  A Little Night Music: 1973." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Follies", value: 1971, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "Follies: 1971.  Evita: 1979." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "Kiss Me, Kate: 1948.  Sweeney Todd: 1979." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Chicago", value: 1975, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "Chicago: 1975.  Hadestown: 2019." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Grease", value: 1972, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "Grease: 1972.  The Book of Mormon: 2011." }
    ]
  },
  {
    id: 22,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "Moulin Rouge!: 2019.  The Book of Mormon: 2011." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "Spring Awakening", value: 2006, label: "opened" }, note: "My Fair Lady: 1956.  Spring Awakening: 2006." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Legally Blonde: 2007.  Les Misérables: 1987." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "42nd Street", value: 1980, label: "opened" }, b: { name: "Company", value: 1970, label: "opened" }, note: "42nd Street: 1980.  Company: 1970." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Spamalot", value: 2005, label: "opened" }, b: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, note: "Spamalot: 2005.  Annie Get Your Gun: 1946." }
    ]
  },
  {
    id: 23,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Ragtime", value: 1998, label: "opened" }, note: "Cabaret: 1966.  Ragtime: 1998." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Moulin Rouge!: 2019.  Grease: 1972." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Book of Mormon", value: 2011, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "The Book of Mormon: 2011.  Camelot: 1960." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, note: "Guys and Dolls: 1950.  Bye Bye Birdie: 1960." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "A Chorus Line", value: 1975, label: "opened" }, note: "My Fair Lady: 1956.  A Chorus Line: 1975." }
    ]
  },
  {
    id: 24,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, b: { name: "The Pajama Game", value: 1954, label: "opened" }, note: "Kiss Me, Kate: 1948.  The Pajama Game: 1954." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Beautiful", value: 2014, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "Beautiful: 2014.  Guys and Dolls: 1950." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "The Producers: 2001.  Sweeney Todd: 1979." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, b: { name: "Wicked", value: 2003, label: "opened" }, note: "A Funny Thing Happened on the Way to the Forum: 1962.  Wicked: 2003." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Book of Mormon", value: 2011, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "The Book of Mormon: 2011.  Hairspray: 2002." }
    ]
  },
  {
    id: 25,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Hadestown: 2019.  Grease: 1972." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Lion King", value: 1997, label: "opened" }, b: { name: "Mame", value: 1966, label: "opened" }, note: "The Lion King: 1997.  Mame: 1966." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Kinky Boots", value: 2013, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Kinky Boots: 2013.  Hairspray: 2002." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Beetlejuice", value: 2019, label: "opened" }, b: { name: "Legally Blonde", value: 2007, label: "opened" }, note: "Beetlejuice: 2019.  Legally Blonde: 2007." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "Chicago", value: 1975, label: "opened" }, note: "Aida: 2000.  Chicago: 1975." }
    ]
  },
  {
    id: 26,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Crazy for You", value: 1992, label: "opened" }, b: { name: "Rent", value: 1996, label: "opened" }, note: "Crazy for You: 1992.  Rent: 1996." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Once", value: 2012, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "Once: 2012.  Follies: 1971." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "A Little Night Music", value: 1973, label: "opened" }, b: { name: "The Music Man", value: 1957, label: "opened" }, note: "A Little Night Music: 1973.  The Music Man: 1957." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Beauty and the Beast", value: 1994, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Beauty and the Beast: 1994.  In the Heights: 2008." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "Cabaret: 1966.  Hadestown: 2019." }
    ]
  },
  {
    id: 27,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Company: 1970.  Les Misérables: 1987." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Man of La Mancha", value: 1965, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Man of La Mancha: 1965.  Grease: 1972." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Spamalot", value: 2005, label: "opened" }, note: "Mamma Mia!: 2001.  Spamalot: 2005." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Pippin", value: 1972, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Pippin: 1972.  Hairspray: 2002." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "Fun Home: 2015.  Avenue Q: 2003." }
    ]
  },
  {
    id: 28,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "Newsies", value: 2012, label: "opened" }, note: "The Producers: 2001.  Newsies: 2012." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "The Sound of Music", value: 1959, label: "opened" }, note: "Hadestown: 2019.  The Sound of Music: 1959." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Hamilton", value: 2015, label: "opened" }, b: { name: "The Wiz", value: 1975, label: "opened" }, note: "Hamilton: 2015.  The Wiz: 1975." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Spamalot", value: 2005, label: "opened" }, b: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, note: "Spamalot: 2005.  Dear Evan Hansen: 2016." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "American Idiot", value: 2010, label: "opened" }, b: { name: "The Band's Visit", value: 2017, label: "opened" }, note: "American Idiot: 2010.  The Band's Visit: 2017." }
    ]
  },
  {
    id: 29,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "South Pacific", value: 1949, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "South Pacific: 1949.  Jersey Boys: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, b: { name: "The Band's Visit", value: 2017, label: "opened" }, note: "Sunday in the Park with George: 1984.  The Band's Visit: 2017." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Rent", value: 1996, label: "opened" }, b: { name: "Company", value: 1970, label: "opened" }, note: "Rent: 1996.  Company: 1970." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Miss Saigon", value: 1991, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Miss Saigon: 1991.  Kiss Me, Kate: 1948." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Mame", value: 1966, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "Mame: 1966.  Damn Yankees: 1955." }
    ]
  },
  {
    id: 30,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Camelot", value: 1960, label: "opened" }, b: { name: "Miss Saigon", value: 1991, label: "opened" }, note: "Camelot: 1960.  Miss Saigon: 1991." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Mean Girls", value: 2018, label: "opened" }, note: "Gypsy: 1959.  Mean Girls: 2018." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, b: { name: "Into the Woods", value: 1987, label: "opened" }, note: "Dear Evan Hansen: 2016.  Into the Woods: 1987." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "Legally Blonde: 2007.  Damn Yankees: 1955." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Guys and Dolls: 1950.  In the Heights: 2008." }
    ]
  },
  {
    id: 31,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "Pippin", value: 1972, label: "opened" }, note: "Waitress: 2016.  Pippin: 1972." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "Cabaret: 1966.  Evita: 1979." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Man of La Mancha", value: 1965, label: "opened" }, note: "Company: 1970.  Man of La Mancha: 1965." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Miss Saigon", value: 1991, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "Miss Saigon: 1991.  Sweeney Todd: 1979." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "Beauty and the Beast", value: 1994, label: "opened" }, note: "Legally Blonde: 2007.  Beauty and the Beast: 1994." }
    ]
  },
  {
    id: 32,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Little Night Music", value: 1973, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "A Little Night Music: 1973.  Hamilton: 2015." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Lion King", value: 1997, label: "opened" }, b: { name: "The Producers", value: 2001, label: "opened" }, note: "The Lion King: 1997.  The Producers: 2001." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Memphis", value: 2009, label: "opened" }, note: "The Phantom of the Opera: 1988.  Memphis: 2009." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Kiss Me, Kate: 1948.  Grease: 1972." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Hair", value: 1968, label: "opened" }, b: { name: "Spring Awakening", value: 2006, label: "opened" }, note: "Hair: 1968.  Spring Awakening: 2006." }
    ]
  },
  {
    id: 33,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Sound of Music", value: 1959, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "The Sound of Music: 1959.  Follies: 1971." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, b: { name: "Cabaret", value: 1966, label: "opened" }, note: "Annie Get Your Gun: 1946.  Cabaret: 1966." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Carousel", value: 1945, label: "opened" }, b: { name: "A Little Night Music", value: 1973, label: "opened" }, note: "Carousel: 1945.  A Little Night Music: 1973." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Mean Girls", value: 2018, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Mean Girls: 2018.  Hairspray: 2002." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "Gypsy: 1959.  Hadestown: 2019." }
    ]
  },
  {
    id: 34,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Mame", value: 1966, label: "opened" }, b: { name: "The Producers", value: 2001, label: "opened" }, note: "Mame: 1966.  The Producers: 2001." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "Beauty and the Beast", value: 1994, label: "opened" }, note: "Aida: 2000.  Beauty and the Beast: 1994." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Hamilton", value: 2015, label: "opened" }, b: { name: "Carousel", value: 1945, label: "opened" }, note: "Hamilton: 2015.  Carousel: 1945." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Six", value: 2021, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "Six: 2021.  The Phantom of the Opera: 1988." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Evita", value: 1979, label: "opened" }, b: { name: "Aladdin", value: 2014, label: "opened" }, note: "Evita: 1979.  Aladdin: 2014." }
    ]
  },
  {
    id: 35,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Six", value: 2021, label: "opened" }, b: { name: "Rent", value: 1996, label: "opened" }, note: "Six: 2021.  Rent: 1996." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Wiz", value: 1975, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "The Wiz: 1975.  Evita: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Grease", value: 1972, label: "opened" }, b: { name: "American Idiot", value: 2010, label: "opened" }, note: "Grease: 1972.  American Idiot: 2010." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "In the Heights: 2008.  Hamilton: 2015." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Sunset Boulevard", value: 1994, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Sunset Boulevard: 1994.  Kiss Me, Kate: 1948." }
    ]
  },
  {
    id: 36,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "Dreamgirls", value: 1981, label: "opened" }, note: "Legally Blonde: 2007.  Dreamgirls: 1981." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "Aladdin", value: 2014, label: "opened" }, note: "Next to Normal: 2009.  Aladdin: 2014." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Wicked", value: 2003, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "Wicked: 2003.  Evita: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Carousel", value: 1945, label: "opened" }, b: { name: "South Pacific", value: 1949, label: "opened" }, note: "Carousel: 1945.  South Pacific: 1949." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "42nd Street", value: 1980, label: "opened" }, b: { name: "Oklahoma!", value: 1943, label: "opened" }, note: "42nd Street: 1980.  Oklahoma!: 1943." }
    ]
  },
  {
    id: 37,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "The King and I", value: 1951, label: "opened" }, b: { name: "The Band's Visit", value: 2017, label: "opened" }, note: "The King and I: 1951.  The Band's Visit: 2017." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Damn Yankees", value: 1955, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Damn Yankees: 1955.  Gypsy: 1959." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Spamalot", value: 2005, label: "opened" }, note: "Company: 1970.  Spamalot: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Crazy for You", value: 1992, label: "opened" }, b: { name: "A Little Night Music", value: 1973, label: "opened" }, note: "Crazy for You: 1992.  A Little Night Music: 1973." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, note: "The Music Man: 1957.  Annie Get Your Gun: 1946." }
    ]
  },
  {
    id: 38,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, note: "The Music Man: 1957.  Dear Evan Hansen: 2016." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "The Phantom of the Opera: 1988.  Annie: 1977." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Hair", value: 1968, label: "opened" }, b: { name: "Sunset Boulevard", value: 1994, label: "opened" }, note: "Hair: 1968.  Sunset Boulevard: 1994." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Cabaret: 1966.  Gypsy: 1959." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Titanic", value: 1997, label: "opened" }, b: { name: "Pippin", value: 1972, label: "opened" }, note: "Titanic: 1997.  Pippin: 1972." }
    ]
  },
  {
    id: 39,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "A Funny Thing Happened on the Way to the Forum: 1962.  Damn Yankees: 1955." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Beautiful", value: 2014, label: "opened" }, b: { name: "Legally Blonde", value: 2007, label: "opened" }, note: "Beautiful: 2014.  Legally Blonde: 2007." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Frozen", value: 2018, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "Frozen: 2018.  Jersey Boys: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, b: { name: "Spring Awakening", value: 2006, label: "opened" }, note: "Bye Bye Birdie: 1960.  Spring Awakening: 2006." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Hairspray", value: 2002, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Hairspray: 2002.  In the Heights: 2008." }
    ]
  },
  {
    id: 40,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Jersey Boys", value: 2005, label: "opened" }, b: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, note: "Jersey Boys: 2005.  Sunday in the Park with George: 1984." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Into the Woods", value: 1987, label: "opened" }, b: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, note: "Into the Woods: 1987.  Bye Bye Birdie: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Matilda", value: 2013, label: "opened" }, note: "The Music Man: 1957.  Matilda: 2013." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Wiz", value: 1975, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "The Wiz: 1975.  Sweeney Todd: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Gypsy: 1959.  Kiss Me, Kate: 1948." }
    ]
  },
  {
    id: 41,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "American Idiot", value: 2010, label: "opened" }, note: "The Producers: 2001.  American Idiot: 2010." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "Sunday in the Park with George: 1984.  Fiddler on the Roof: 1964." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "The Music Man: 1957.  Avenue Q: 2003." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "A Chorus Line: 1975.  The Book of Mormon: 2011." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "Pippin", value: 1972, label: "opened" }, note: "Next to Normal: 2009.  Pippin: 1972." }
    ]
  },
  {
    id: 42,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Spring Awakening", value: 2006, label: "opened" }, note: "Fun Home: 2015.  Spring Awakening: 2006." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, b: { name: "Once", value: 2012, label: "opened" }, note: "Sunday in the Park with George: 1984.  Once: 2012." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "Next to Normal: 2009.  Jersey Boys: 2005." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Waitress: 2016.  Camelot: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Newsies", value: 2012, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Newsies: 2012.  Les Misérables: 1987." }
    ]
  },
  {
    id: 43,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "Sunday in the Park with George: 1984.  Damn Yankees: 1955." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Avenue Q", value: 2003, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Avenue Q: 2003.  Grease: 1972." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "La Cage aux Folles", value: 1983, label: "opened" }, note: "Fun Home: 2015.  La Cage aux Folles: 1983." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Into the Woods", value: 1987, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "Into the Woods: 1987.  Follies: 1971." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Beauty and the Beast", value: 1994, label: "opened" }, b: { name: "Company", value: 1970, label: "opened" }, note: "Beauty and the Beast: 1994.  Company: 1970." }
    ]
  },
  {
    id: 44,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Wicked", value: 2003, label: "opened" }, b: { name: "American Idiot", value: 2010, label: "opened" }, note: "Wicked: 2003.  American Idiot: 2010." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mame", value: 1966, label: "opened" }, b: { name: "Spamalot", value: 2005, label: "opened" }, note: "Mame: 1966.  Spamalot: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Memphis", value: 2009, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "Memphis: 2009.  Annie: 1977." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Oklahoma!", value: 1943, label: "opened" }, b: { name: "The Music Man", value: 1957, label: "opened" }, note: "Oklahoma!: 1943.  The Music Man: 1957." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Jersey Boys", value: 2005, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Jersey Boys: 2005.  Hairspray: 2002." }
    ]
  },
  {
    id: 45,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The King and I", value: 1951, label: "opened" }, b: { name: "Spamalot", value: 2005, label: "opened" }, note: "The King and I: 1951.  Spamalot: 2005." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Lion King", value: 1997, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "The Lion King: 1997.  Fiddler on the Roof: 1964." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Into the Woods", value: 1987, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "Into the Woods: 1987.  The Book of Mormon: 2011." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Pajama Game", value: 1954, label: "opened" }, b: { name: "Legally Blonde", value: 2007, label: "opened" }, note: "The Pajama Game: 1954.  Legally Blonde: 2007." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Wicked", value: 2003, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Wicked: 2003.  Kiss Me, Kate: 1948." }
    ]
  },
  {
    id: 46,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, note: "Fun Home: 2015.  Annie Get Your Gun: 1946." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Beautiful", value: 2014, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Beautiful: 2014.  Camelot: 1960." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Once", value: 2012, label: "opened" }, b: { name: "Mean Girls", value: 2018, label: "opened" }, note: "Once: 2012.  Mean Girls: 2018." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "Cabaret", value: 1966, label: "opened" }, note: "Aida: 2000.  Cabaret: 1966." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Oklahoma!", value: 1943, label: "opened" }, b: { name: "Pippin", value: 1972, label: "opened" }, note: "Oklahoma!: 1943.  Pippin: 1972." }
    ]
  },
  {
    id: 47,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Annie Get Your Gun", value: 1946, label: "opened" }, b: { name: "Sunset Boulevard", value: 1994, label: "opened" }, note: "Annie Get Your Gun: 1946.  Sunset Boulevard: 1994." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "Mamma Mia!", value: 2001, label: "opened" }, note: "West Side Story: 1957.  Mamma Mia!: 2001." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Beetlejuice", value: 2019, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "Beetlejuice: 2019.  Evita: 1979." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Man of La Mancha", value: 1965, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "Man of La Mancha: 1965.  Follies: 1971." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Cats", value: 1982, label: "opened" }, note: "Cabaret: 1966.  Cats: 1982." }
    ]
  },
  {
    id: 48,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Les Misérables", value: 1987, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Les Misérables: 1987.  In the Heights: 2008." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "A Funny Thing Happened on the Way to the Forum: 1962.  The Book of Mormon: 2011." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Fun Home", value: 2015, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "Fun Home: 2015.  Jersey Boys: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Ragtime", value: 1998, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Ragtime: 1998.  Camelot: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Frozen", value: 2018, label: "opened" }, b: { name: "The Lion King", value: 1997, label: "opened" }, note: "Frozen: 2018.  The Lion King: 1997." }
    ]
  },
  {
    id: 49,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sweeney Todd", value: 1979, label: "opened" }, b: { name: "Beauty and the Beast", value: 1994, label: "opened" }, note: "Sweeney Todd: 1979.  Beauty and the Beast: 1994." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Matilda", value: 2013, label: "opened" }, b: { name: "Waitress", value: 2016, label: "opened" }, note: "Matilda: 2013.  Waitress: 2016." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "South Pacific", value: 1949, label: "opened" }, note: "Hadestown: 2019.  South Pacific: 1949." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Follies", value: 1971, label: "opened" }, b: { name: "American Idiot", value: 2010, label: "opened" }, note: "Follies: 1971.  American Idiot: 2010." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Come From Away", value: 2017, label: "opened" }, b: { name: "Sunday in the Park with George", value: 1984, label: "opened" }, note: "Come From Away: 2017.  Sunday in the Park with George: 1984." }
    ]
  },
  {
    id: 50,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Titanic", value: 1997, label: "opened" }, b: { name: "Man of La Mancha", value: 1965, label: "opened" }, note: "Titanic: 1997.  Man of La Mancha: 1965." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "The Producers: 2001.  Guys and Dolls: 1950." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Newsies", value: 2012, label: "opened" }, b: { name: "Fun Home", value: 2015, label: "opened" }, note: "Newsies: 2012.  Fun Home: 2015." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, b: { name: "Frozen", value: 2018, label: "opened" }, note: "Bye Bye Birdie: 1960.  Frozen: 2018." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "Cabaret: 1966.  Hamilton: 2015." }
    ]
  },
  {
    id: 51,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, b: { name: "Crazy for You", value: 1992, label: "opened" }, note: "Fiddler on the Roof: 1964.  Crazy for You: 1992." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "Man of La Mancha", value: 1965, label: "opened" }, note: "In the Heights: 2008.  Man of La Mancha: 1965." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "The Phantom of the Opera: 1988.  Follies: 1971." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Annie", value: 1977, label: "opened" }, b: { name: "Frozen", value: 2018, label: "opened" }, note: "Annie: 1977.  Frozen: 2018." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, b: { name: "Legally Blonde", value: 2007, label: "opened" }, note: "Dear Evan Hansen: 2016.  Legally Blonde: 2007." }
    ]
  },
  {
    id: 52,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "Rent", value: 1996, label: "opened" }, note: "A Chorus Line: 1975.  Rent: 1996." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Beautiful", value: 2014, label: "opened" }, b: { name: "A Funny Thing Happened on the Way to the Forum", value: 1962, label: "opened" }, note: "Beautiful: 2014.  A Funny Thing Happened on the Way to the Forum: 1962." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Grease", value: 1972, label: "opened" }, b: { name: "West Side Story", value: 1957, label: "opened" }, note: "Grease: 1972.  West Side Story: 1957." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Oklahoma!", value: 1943, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Oklahoma!: 1943.  Camelot: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Man of La Mancha", value: 1965, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "Man of La Mancha: 1965.  Annie: 1977." }
    ]
  },
  {
    id: 53,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Music Man", value: 1957, label: "opened" }, b: { name: "South Pacific", value: 1949, label: "opened" }, note: "The Music Man: 1957.  South Pacific: 1949." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, note: "My Fair Lady: 1956.  Dear Evan Hansen: 2016." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Lion King", value: 1997, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "The Lion King: 1997.  Evita: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "Man of La Mancha", value: 1965, label: "opened" }, note: "Moulin Rouge!: 2019.  Man of La Mancha: 1965." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunset Boulevard", value: 1994, label: "opened" }, b: { name: "Six", value: 2021, label: "opened" }, note: "Sunset Boulevard: 1994.  Six: 2021." }
    ]
  },
  {
    id: 54,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Band's Visit", value: 2017, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "The Band's Visit: 2017.  Sweeney Todd: 1979." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Company: 1970.  Camelot: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "South Pacific", value: 1949, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "South Pacific: 1949.  The Book of Mormon: 2011." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Miss Saigon", value: 1991, label: "opened" }, b: { name: "Cats", value: 1982, label: "opened" }, note: "Miss Saigon: 1991.  Cats: 1982." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Les Misérables", value: 1987, label: "opened" }, b: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, note: "Les Misérables: 1987.  Dear Evan Hansen: 2016." }
    ]
  },
  {
    id: 55,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, b: { name: "Once", value: 2012, label: "opened" }, note: "Dear Evan Hansen: 2016.  Once: 2012." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "Ragtime", value: 1998, label: "opened" }, note: "In the Heights: 2008.  Ragtime: 1998." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "Titanic", value: 1997, label: "opened" }, note: "Waitress: 2016.  Titanic: 1997." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Grease", value: 1972, label: "opened" }, b: { name: "Matilda", value: 2013, label: "opened" }, note: "Grease: 1972.  Matilda: 2013." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Aladdin", value: 2014, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "Aladdin: 2014.  The Phantom of the Opera: 1988." }
    ]
  },
  {
    id: 56,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Matilda", value: 2013, label: "opened" }, b: { name: "Hair", value: 1968, label: "opened" }, note: "Matilda: 2013.  Hair: 1968." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Damn Yankees", value: 1955, label: "opened" }, b: { name: "The Wiz", value: 1975, label: "opened" }, note: "Damn Yankees: 1955.  The Wiz: 1975." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mame", value: 1966, label: "opened" }, b: { name: "South Pacific", value: 1949, label: "opened" }, note: "Mame: 1966.  South Pacific: 1949." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Spamalot", value: 2005, label: "opened" }, b: { name: "The Lion King", value: 1997, label: "opened" }, note: "Spamalot: 2005.  The Lion King: 1997." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Avenue Q", value: 2003, label: "opened" }, b: { name: "Camelot", value: 1960, label: "opened" }, note: "Avenue Q: 2003.  Camelot: 1960." }
    ]
  },
  {
    id: 57,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "42nd Street", value: 1980, label: "opened" }, note: "My Fair Lady: 1956.  42nd Street: 1980." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Wiz", value: 1975, label: "opened" }, b: { name: "Crazy for You", value: 1992, label: "opened" }, note: "The Wiz: 1975.  Crazy for You: 1992." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "The Color Purple", value: 2005, label: "opened" }, note: "Waitress: 2016.  The Color Purple: 2005." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "Company: 1970.  Hamilton: 2015." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Frozen", value: 2018, label: "opened" }, b: { name: "The Sound of Music", value: 1959, label: "opened" }, note: "Frozen: 2018.  The Sound of Music: 1959." }
    ]
  },
  {
    id: 58,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Mean Girls", value: 2018, label: "opened" }, b: { name: "Ragtime", value: 1998, label: "opened" }, note: "Mean Girls: 2018.  Ragtime: 1998." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "Matilda", value: 2013, label: "opened" }, note: "My Fair Lady: 1956.  Matilda: 2013." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Pippin", value: 1972, label: "opened" }, b: { name: "Damn Yankees", value: 1955, label: "opened" }, note: "Pippin: 1972.  Damn Yankees: 1955." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "Kiss Me, Kate: 1948.  The Phantom of the Opera: 1988." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Aladdin", value: 2014, label: "opened" }, b: { name: "Titanic", value: 1997, label: "opened" }, note: "Aladdin: 2014.  Titanic: 1997." }
    ]
  },
  {
    id: 59,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "My Fair Lady", value: 1956, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "My Fair Lady: 1956.  Hairspray: 2002." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "In the Heights: 2008.  Fiddler on the Roof: 1964." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Aida", value: 2000, label: "opened" }, b: { name: "The Wiz", value: 1975, label: "opened" }, note: "Aida: 2000.  The Wiz: 1975." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Moulin Rouge!", value: 2019, label: "opened" }, note: "Mamma Mia!: 2001.  Moulin Rouge!: 2019." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "The Color Purple", value: 2005, label: "opened" }, note: "Next to Normal: 2009.  The Color Purple: 2005." }
    ]
  },
  {
    id: 60,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Hair", value: 1968, label: "opened" }, b: { name: "La Cage aux Folles", value: 1983, label: "opened" }, note: "Hair: 1968.  La Cage aux Folles: 1983." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Cats", value: 1982, label: "opened" }, b: { name: "Sunset Boulevard", value: 1994, label: "opened" }, note: "Cats: 1982.  Sunset Boulevard: 1994." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "The Band's Visit", value: 2017, label: "opened" }, note: "Legally Blonde: 2007.  The Band's Visit: 2017." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Annie", value: 1977, label: "opened" }, b: { name: "Aladdin", value: 2014, label: "opened" }, note: "Annie: 1977.  Aladdin: 2014." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Pippin", value: 1972, label: "opened" }, b: { name: "The Color Purple", value: 2005, label: "opened" }, note: "Pippin: 1972.  The Color Purple: 2005." }
    ]
  },
  {
    id: 61,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "A Little Night Music", value: 1973, label: "opened" }, note: "Guys and Dolls: 1950.  A Little Night Music: 1973." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Legally Blonde", value: 2007, label: "opened" }, b: { name: "Kiss Me, Kate", value: 1948, label: "opened" }, note: "Legally Blonde: 2007.  Kiss Me, Kate: 1948." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Dreamgirls", value: 1981, label: "opened" }, b: { name: "Follies", value: 1971, label: "opened" }, note: "Dreamgirls: 1981.  Follies: 1971." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Carousel", value: 1945, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Carousel: 1945.  Gypsy: 1959." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, b: { name: "Six", value: 2021, label: "opened" }, note: "Dear Evan Hansen: 2016.  Six: 2021." }
    ]
  },
  {
    id: 62,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Annie", value: 1977, label: "opened" }, b: { name: "Kinky Boots", value: 2013, label: "opened" }, note: "Annie: 1977.  Kinky Boots: 2013." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Mean Girls", value: 2018, label: "opened" }, b: { name: "La Cage aux Folles", value: 1983, label: "opened" }, note: "Mean Girls: 2018.  La Cage aux Folles: 1983." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Cats", value: 1982, label: "opened" }, b: { name: "American Idiot", value: 2010, label: "opened" }, note: "Cats: 1982.  American Idiot: 2010." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Memphis", value: 2009, label: "opened" }, b: { name: "Crazy for You", value: 1992, label: "opened" }, note: "Memphis: 2009.  Crazy for You: 1992." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Frozen", value: 2018, label: "opened" }, note: "Company: 1970.  Frozen: 2018." }
    ]
  },
  {
    id: 63,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Dreamgirls", value: 1981, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Dreamgirls: 1981.  Les Misérables: 1987." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Company", value: 1970, label: "opened" }, b: { name: "Bye Bye Birdie", value: 1960, label: "opened" }, note: "Company: 1970.  Bye Bye Birdie: 1960." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Crazy for You", value: 1992, label: "opened" }, b: { name: "Moulin Rouge!", value: 2019, label: "opened" }, note: "Crazy for You: 1992.  Moulin Rouge!: 2019." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Spring Awakening", value: 2006, label: "opened" }, b: { name: "La Cage aux Folles", value: 1983, label: "opened" }, note: "Spring Awakening: 2006.  La Cage aux Folles: 1983." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, note: "West Side Story: 1957.  The Phantom of the Opera: 1988." }
    ]
  },
  {
    id: 64,
    matchups: [
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Camelot", value: 1960, label: "opened" }, b: { name: "Next to Normal", value: 2009, label: "opened" }, note: "Camelot: 1960.  Next to Normal: 2009." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Into the Woods", value: 1987, label: "opened" }, b: { name: "Mean Girls", value: 2018, label: "opened" }, note: "Into the Woods: 1987.  Mean Girls: 2018." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Spamalot", value: 2005, label: "opened" }, b: { name: "Six", value: 2021, label: "opened" }, note: "Spamalot: 2005.  Six: 2021." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Beetlejuice", value: 2019, label: "opened" }, b: { name: "42nd Street", value: 1980, label: "opened" }, note: "Beetlejuice: 2019.  42nd Street: 1980." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunset Boulevard", value: 1994, label: "opened" }, b: { name: "Fun Home", value: 2015, label: "opened" }, note: "Sunset Boulevard: 1994.  Fun Home: 2015." }
    ]
  },
  {
    id: 65,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Dreamgirls", value: 1981, label: "opened" }, b: { name: "Beautiful", value: 2014, label: "opened" }, note: "Dreamgirls: 1981.  Beautiful: 2014." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Camelot", value: 1960, label: "opened" }, b: { name: "Chicago", value: 1975, label: "opened" }, note: "Camelot: 1960.  Chicago: 1975." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Newsies", value: 2012, label: "opened" }, b: { name: "Mamma Mia!", value: 2001, label: "opened" }, note: "Newsies: 2012.  Mamma Mia!: 2001." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Next to Normal", value: 2009, label: "opened" }, b: { name: "Grease", value: 1972, label: "opened" }, note: "Next to Normal: 2009.  Grease: 1972." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Man of La Mancha", value: 1965, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "Man of La Mancha: 1965.  Guys and Dolls: 1950." }
    ]
  },
  {
    id: 66,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Producers", value: 2001, label: "opened" }, b: { name: "The Pajama Game", value: 1954, label: "opened" }, note: "The Producers: 2001.  The Pajama Game: 1954." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Rent", value: 1996, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Rent: 1996.  Hairspray: 2002." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Sunset Boulevard", value: 1994, label: "opened" }, b: { name: "Kinky Boots", value: 2013, label: "opened" }, note: "Sunset Boulevard: 1994.  Kinky Boots: 2013." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Jersey Boys", value: 2005, label: "opened" }, b: { name: "Into the Woods", value: 1987, label: "opened" }, note: "Jersey Boys: 2005.  Into the Woods: 1987." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "Moulin Rouge!", value: 2019, label: "opened" }, b: { name: "Titanic", value: 1997, label: "opened" }, note: "Moulin Rouge!: 2019.  Titanic: 1997." }
    ]
  },
  {
    id: 67,
    matchups: [
      { prompt: "Which is the more recent Broadway opening?", a: { name: "The Sound of Music", value: 1959, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "The Sound of Music: 1959.  Evita: 1979." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "The Phantom of the Opera: 1988.  Hamilton: 2015." },
      { prompt: "Which is the more recent Broadway opening?", a: { name: "La Cage aux Folles", value: 1983, label: "opened" }, b: { name: "West Side Story", value: 1957, label: "opened" }, note: "La Cage aux Folles: 1983.  West Side Story: 1957." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Waitress", value: 2016, label: "opened" }, b: { name: "Jersey Boys", value: 2005, label: "opened" }, note: "Waitress: 2016.  Jersey Boys: 2005." },
      { prompt: "Which premiered on Broadway LATER?", a: { name: "Carousel", value: 1945, label: "opened" }, b: { name: "Hair", value: 1968, label: "opened" }, note: "Carousel: 1945.  Hair: 1968." }
    ]
  }
  ];
  window.ShowdownPuzzles = (window.ShowdownPuzzles || []).concat(GEN);
})();
