/* AUTO-GENERATED by tools/build-showdown.js from data/shows.js + data/stats.js.
   Do not edit by hand. 43 database-derived matchup puzzles
   (opening year, original-run performances, Tony wins) appended to the 7
   curated puzzles in matchups.js. Re-run the generator after the database changes. */
(function () {
  var GEN = [
  {
    id: 8,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hamilton", value: 11, label: "Tony wins" }, b: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, note: "Hamilton: 11.  Fiddler on the Roof: 9." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "Oklahoma!", value: 1943, label: "opened" }, note: "West Side Story: 1957.  Oklahoma!: 1943." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "A Chorus Line", value: 9, label: "Tony wins" }, b: { name: "Chicago", value: 6, label: "Tony wins" }, note: "A Chorus Line: 9.  Chicago: 6." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Pippin", value: 1944, label: "performances" }, b: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, note: "Pippin: 1,944.  Fiddler on the Roof: 3,242." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Rent", value: 5123, label: "performances" }, b: { name: "Cats", value: 7485, label: "performances" }, note: "Rent: 5,123.  Cats: 7,485." }
    ]
  },
  {
    id: 9,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Come From Away", value: 1, label: "Tony wins" }, b: { name: "Avenue Q", value: 3, label: "Tony wins" }, note: "Come From Away: 1.  Avenue Q: 3." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Jesus Christ Superstar", value: 1971, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Jesus Christ Superstar: 1971.  Gypsy: 1959." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Pippin", value: 1944, label: "performances" }, b: { name: "Annie", value: 2377, label: "performances" }, note: "Pippin: 1,944.  Annie: 2,377." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Into the Woods", value: 3, label: "Tony wins" }, b: { name: "Chicago", value: 6, label: "Tony wins" }, note: "Into the Woods: 3.  Chicago: 6." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Mamma Mia!", value: 5758, label: "performances" }, note: "Jersey Boys: 4,642.  Mamma Mia!: 5,758." }
    ]
  },
  {
    id: 10,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Newsies", value: 2, label: "Tony wins" }, b: { name: "Wicked", value: 3, label: "Tony wins" }, note: "Newsies: 2.  Wicked: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, b: { name: "Funny Girl", value: 1348, label: "performances" }, note: "Fiddler on the Roof: 3,242.  Funny Girl: 1,348." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Funny Girl", value: 1348, label: "performances" }, note: "Jersey Boys: 4,642.  Funny Girl: 1,348." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Phantom of the Opera", value: 7, label: "Tony wins" }, b: { name: "The Lion King", value: 6, label: "Tony wins" }, note: "The Phantom of the Opera: 7.  The Lion King: 6." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Sweeney Todd", value: 1979, label: "opened" }, b: { name: "In the Heights", value: 2008, label: "opened" }, note: "Sweeney Todd: 1979.  In the Heights: 2008." }
    ]
  },
  {
    id: 11,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "In the Heights", value: 4, label: "Tony wins" }, b: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, note: "In the Heights: 4.  Mamma Mia!: 0." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "The Book of Mormon", value: 2011, label: "opened" }, note: "In the Heights: 2008.  The Book of Mormon: 2011." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Funny Girl", value: 1348, label: "performances" }, b: { name: "Guys and Dolls", value: 1200, label: "performances" }, note: "Funny Girl: 1,348.  Guys and Dolls: 1,200." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Dear Evan Hansen", value: 6, label: "Tony wins" }, b: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, note: "Dear Evan Hansen: 6.  Fiddler on the Roof: 9." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Cats", value: 7485, label: "performances" }, note: "Jersey Boys: 4,642.  Cats: 7,485." }
    ]
  },
  {
    id: 12,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Book of Mormon", value: 2011, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "The Book of Mormon: 2011.  Fiddler on the Roof: 1964." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, b: { name: "In the Heights", value: 1185, label: "performances" }, note: "Dear Evan Hansen: 1,678.  In the Heights: 1,185." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Pippin", value: 5, label: "Tony wins" }, b: { name: "Dear Evan Hansen", value: 6, label: "Tony wins" }, note: "Pippin: 5.  Dear Evan Hansen: 6." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Pippin", value: 5, label: "Tony wins" }, b: { name: "A Chorus Line", value: 9, label: "Tony wins" }, note: "Pippin: 5.  A Chorus Line: 9." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Funny Girl", value: 1348, label: "performances" }, b: { name: "Rent", value: 5123, label: "performances" }, note: "Funny Girl: 1,348.  Rent: 5,123." }
    ]
  },
  {
    id: 13,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "Cabaret", value: 8, label: "Tony wins" }, note: "Cats: 7.  Cabaret: 8." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, b: { name: "Cats", value: 7, label: "Tony wins" }, note: "Fiddler on the Roof: 9.  Cats: 7." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Hairspray", value: 2642, label: "performances" }, b: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, note: "Hairspray: 2,642.  The Phantom of the Opera: 13,981." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Les Misérables", value: 1987, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Les Misérables: 1987.  Hairspray: 2002." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jesus Christ Superstar", value: 711, label: "performances" }, b: { name: "Gypsy", value: 702, label: "performances" }, note: "Jesus Christ Superstar: 711.  Gypsy: 702." }
    ]
  },
  {
    id: 14,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Hairspray", value: 2642, label: "performances" }, b: { name: "Pippin", value: 1944, label: "performances" }, note: "Hairspray: 2,642.  Pippin: 1,944." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Six", value: 2021, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "Six: 2021.  Avenue Q: 2003." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hadestown", value: 8, label: "Tony wins" }, b: { name: "Evita", value: 7, label: "Tony wins" }, note: "Hadestown: 8.  Evita: 7." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Evita", value: 1567, label: "performances" }, b: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, note: "Evita: 1,567.  Fiddler on the Roof: 3,242." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Newsies", value: 2, label: "Tony wins" }, note: "Sweeney Todd: 8.  Newsies: 2." }
    ]
  },
  {
    id: 15,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Les Misérables", value: 1987, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "Les Misérables: 1987.  Guys and Dolls: 1950." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Les Misérables", value: 6680, label: "performances" }, b: { name: "A Chorus Line", value: 6137, label: "performances" }, note: "Les Misérables: 6,680.  A Chorus Line: 6,137." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Oklahoma!", value: 2212, label: "performances" }, b: { name: "Pippin", value: 1944, label: "performances" }, note: "Oklahoma!: 2,212.  Pippin: 1,944." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, b: { name: "Guys and Dolls", value: 5, label: "Tony wins" }, note: "The Book of Mormon: 9.  Guys and Dolls: 5." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, b: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, note: "Mamma Mia!: 0.  Sweeney Todd: 8." }
    ]
  },
  {
    id: 16,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Les Misérables", value: 1987, label: "opened" }, b: { name: "West Side Story", value: 1957, label: "opened" }, note: "Les Misérables: 1987.  West Side Story: 1957." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Avenue Q", value: 3, label: "Tony wins" }, b: { name: "Hamilton", value: 11, label: "Tony wins" }, note: "Avenue Q: 3.  Hamilton: 11." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Hairspray", value: 2642, label: "performances" }, b: { name: "Come From Away", value: 1669, label: "performances" }, note: "Hairspray: 2,642.  Come From Away: 1,669." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, b: { name: "Evita", value: 1567, label: "performances" }, note: "Dear Evan Hansen: 1,678.  Evita: 1,567." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hadestown", value: 8, label: "Tony wins" }, b: { name: "Avenue Q", value: 3, label: "Tony wins" }, note: "Hadestown: 8.  Avenue Q: 3." }
    ]
  },
  {
    id: 17,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "A Chorus Line", value: 6137, label: "performances" }, b: { name: "Jesus Christ Superstar", value: 711, label: "performances" }, note: "A Chorus Line: 6,137.  Jesus Christ Superstar: 711." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Annie", value: 7, label: "Tony wins" }, b: { name: "Hadestown", value: 8, label: "Tony wins" }, note: "Annie: 7.  Hadestown: 8." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hamilton", value: 11, label: "Tony wins" }, b: { name: "Hadestown", value: 8, label: "Tony wins" }, note: "Hamilton: 11.  Hadestown: 8." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Annie", value: 2377, label: "performances" }, b: { name: "A Chorus Line", value: 6137, label: "performances" }, note: "Annie: 2,377.  A Chorus Line: 6,137." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "West Side Story", value: 1957, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "West Side Story: 1957.  Annie: 1977." }
    ]
  },
  {
    id: 18,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Evita", value: 1567, label: "performances" }, b: { name: "Hairspray", value: 2642, label: "performances" }, note: "Evita: 1,567.  Hairspray: 2,642." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Sound of Music", value: 5, label: "Tony wins" }, b: { name: "Six", value: 2, label: "Tony wins" }, note: "The Sound of Music: 5.  Six: 2." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Funny Girl", value: 1348, label: "performances" }, b: { name: "Gypsy", value: 702, label: "performances" }, note: "Funny Girl: 1,348.  Gypsy: 702." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Funny Girl", value: 0, label: "Tony wins" }, b: { name: "The Lion King", value: 6, label: "Tony wins" }, note: "Funny Girl: 0.  The Lion King: 6." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, b: { name: "Hamilton", value: 2015, label: "opened" }, note: "Fiddler on the Roof: 1964.  Hamilton: 2015." }
    ]
  },
  {
    id: 19,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "Funny Girl", value: 1964, label: "opened" }, note: "Hadestown: 2019.  Funny Girl: 1964." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Avenue Q", value: 2534, label: "performances" }, note: "Jersey Boys: 4,642.  Avenue Q: 2,534." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "In the Heights", value: 4, label: "Tony wins" }, b: { name: "Dear Evan Hansen", value: 6, label: "Tony wins" }, note: "In the Heights: 4.  Dear Evan Hansen: 6." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, b: { name: "The Phantom of the Opera", value: 7, label: "Tony wins" }, note: "Fiddler on the Roof: 9.  The Phantom of the Opera: 7." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Avenue Q", value: 2534, label: "performances" }, b: { name: "Hairspray", value: 2642, label: "performances" }, note: "Avenue Q: 2,534.  Hairspray: 2,642." }
    ]
  },
  {
    id: 20,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Jesus Christ Superstar", value: 0, label: "Tony wins" }, note: "Sweeney Todd: 8.  Jesus Christ Superstar: 0." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Cabaret", value: 1165, label: "performances" }, note: "Jersey Boys: 4,642.  Cabaret: 1,165." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Annie", value: 7, label: "Tony wins" }, b: { name: "The Sound of Music", value: 5, label: "Tony wins" }, note: "Annie: 7.  The Sound of Music: 5." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Phantom of the Opera", value: 1988, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "The Phantom of the Opera: 1988.  Fiddler on the Roof: 1964." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "West Side Story", value: 732, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "West Side Story: 732.  Into the Woods: 765." }
    ]
  },
  {
    id: 21,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "In the Heights", value: 1185, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "In the Heights: 1,185.  Into the Woods: 765." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "West Side Story", value: 2, label: "Tony wins" }, b: { name: "Hadestown", value: 8, label: "Tony wins" }, note: "West Side Story: 2.  Hadestown: 8." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Sweeney Todd", value: 1979, label: "opened" }, b: { name: "Les Misérables", value: 1987, label: "opened" }, note: "Sweeney Todd: 1979.  Les Misérables: 1987." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Gypsy", value: 702, label: "performances" }, b: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, note: "Gypsy: 702.  The Phantom of the Opera: 13,981." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "In the Heights", value: 4, label: "Tony wins" }, note: "Cats: 7.  In the Heights: 4." }
    ]
  },
  {
    id: 22,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, b: { name: "Hairspray", value: 8, label: "Tony wins" }, note: "Fiddler on the Roof: 9.  Hairspray: 8." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "In the Heights", value: 1185, label: "performances" }, b: { name: "Newsies", value: 1004, label: "performances" }, note: "In the Heights: 1,185.  Newsies: 1,004." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "Newsies", value: 2012, label: "opened" }, note: "Guys and Dolls: 1950.  Newsies: 2012." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Come From Away", value: 1669, label: "performances" }, b: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, note: "Come From Away: 1,669.  Fiddler on the Roof: 3,242." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Dear Evan Hansen", value: 6, label: "Tony wins" }, b: { name: "Guys and Dolls", value: 5, label: "Tony wins" }, note: "Dear Evan Hansen: 6.  Guys and Dolls: 5." }
    ]
  },
  {
    id: 23,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Pippin", value: 1944, label: "performances" }, b: { name: "Newsies", value: 1004, label: "performances" }, note: "Pippin: 1,944.  Newsies: 1,004." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Come From Away", value: 2017, label: "opened" }, note: "Mamma Mia!: 2001.  Come From Away: 2017." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, b: { name: "Gypsy", value: 702, label: "performances" }, note: "Dear Evan Hansen: 1,678.  Gypsy: 702." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Jesus Christ Superstar", value: 0, label: "Tony wins" }, b: { name: "Hamilton", value: 11, label: "Tony wins" }, note: "Jesus Christ Superstar: 0.  Hamilton: 11." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Six", value: 2, label: "Tony wins" }, b: { name: "Jesus Christ Superstar", value: 0, label: "Tony wins" }, note: "Six: 2.  Jesus Christ Superstar: 0." }
    ]
  },
  {
    id: 24,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "In the Heights", value: 4, label: "Tony wins" }, b: { name: "Come From Away", value: 1, label: "Tony wins" }, note: "In the Heights: 4.  Come From Away: 1." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cabaret", value: 1165, label: "performances" }, b: { name: "West Side Story", value: 732, label: "performances" }, note: "Cabaret: 1,165.  West Side Story: 732." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, b: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, note: "Mamma Mia!: 0.  The Book of Mormon: 9." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Sweeney Todd", value: 1979, label: "opened" }, b: { name: "The Lion King", value: 1997, label: "opened" }, note: "Sweeney Todd: 1979.  The Lion King: 1997." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "The Sound of Music", value: 1443, label: "performances" }, b: { name: "Newsies", value: 1004, label: "performances" }, note: "The Sound of Music: 1,443.  Newsies: 1,004." }
    ]
  },
  {
    id: 25,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cabaret", value: 1165, label: "performances" }, b: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, note: "Cabaret: 1,165.  Dear Evan Hansen: 1,678." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Into the Woods", value: 3, label: "Tony wins" }, b: { name: "Les Misérables", value: 8, label: "Tony wins" }, note: "Into the Woods: 3.  Les Misérables: 8." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Phantom of the Opera", value: 7, label: "Tony wins" }, b: { name: "Chicago", value: 6, label: "Tony wins" }, note: "The Phantom of the Opera: 7.  Chicago: 6." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Avenue Q", value: 2534, label: "performances" }, b: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, note: "Avenue Q: 2,534.  Dear Evan Hansen: 1,678." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Avenue Q", value: 2003, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Avenue Q: 2003.  Gypsy: 1959." }
    ]
  },
  {
    id: 26,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Wicked", value: 3, label: "Tony wins" }, note: "Sweeney Todd: 8.  Wicked: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cabaret", value: 1165, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "Cabaret: 1,165.  Into the Woods: 765." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jesus Christ Superstar", value: 711, label: "performances" }, b: { name: "Come From Away", value: 1669, label: "performances" }, note: "Jesus Christ Superstar: 711.  Come From Away: 1,669." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Gypsy", value: 1959, label: "opened" }, note: "Cabaret: 1966.  Gypsy: 1959." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "Rent", value: 4, label: "Tony wins" }, note: "Cats: 7.  Rent: 4." }
    ]
  },
  {
    id: 27,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, b: { name: "The Sound of Music", value: 5, label: "Tony wins" }, note: "The Book of Mormon: 9.  The Sound of Music: 5." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Funny Girl", value: 1348, label: "performances" }, b: { name: "Oklahoma!", value: 2212, label: "performances" }, note: "Funny Girl: 1,348.  Oklahoma!: 2,212." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Sweeney Todd", value: 557, label: "performances" }, b: { name: "Evita", value: 1567, label: "performances" }, note: "Sweeney Todd: 557.  Evita: 1,567." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Hadestown", value: 2019, label: "opened" }, b: { name: "Hairspray", value: 2002, label: "opened" }, note: "Hadestown: 2019.  Hairspray: 2002." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, b: { name: "Six", value: 2, label: "Tony wins" }, note: "Mamma Mia!: 0.  Six: 2." }
    ]
  },
  {
    id: 28,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "The Sound of Music", value: 1443, label: "performances" }, b: { name: "Sweeney Todd", value: 557, label: "performances" }, note: "The Sound of Music: 1,443.  Sweeney Todd: 557." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Hairspray", value: 2002, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "Hairspray: 2002.  Sweeney Todd: 1979." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Rent", value: 4, label: "Tony wins" }, b: { name: "Les Misérables", value: 8, label: "Tony wins" }, note: "Rent: 4.  Les Misérables: 8." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, b: { name: "Pippin", value: 5, label: "Tony wins" }, note: "Fiddler on the Roof: 9.  Pippin: 5." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cats", value: 7485, label: "performances" }, b: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, note: "Cats: 7,485.  Fiddler on the Roof: 3,242." }
    ]
  },
  {
    id: 29,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Jersey Boys", value: 2005, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "Jersey Boys: 2005.  Hadestown: 2019." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Evita", value: 1567, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "Evita: 1,567.  Into the Woods: 765." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Funny Girl", value: 0, label: "Tony wins" }, b: { name: "In the Heights", value: 4, label: "Tony wins" }, note: "Funny Girl: 0.  In the Heights: 4." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Funny Girl", value: 1348, label: "performances" }, b: { name: "Newsies", value: 1004, label: "performances" }, note: "Funny Girl: 1,348.  Newsies: 1,004." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "Les Misérables", value: 8, label: "Tony wins" }, note: "Cats: 7.  Les Misérables: 8." }
    ]
  },
  {
    id: 30,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "Mamma Mia!: 2001.  Annie: 1977." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Evita", value: 1567, label: "performances" }, b: { name: "Gypsy", value: 702, label: "performances" }, note: "Evita: 1,567.  Gypsy: 702." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Funny Girl", value: 0, label: "Tony wins" }, note: "Sweeney Todd: 8.  Funny Girl: 0." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Sweeney Todd", value: 557, label: "performances" }, b: { name: "Pippin", value: 1944, label: "performances" }, note: "Sweeney Todd: 557.  Pippin: 1,944." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Into the Woods", value: 3, label: "Tony wins" }, b: { name: "Rent", value: 4, label: "Tony wins" }, note: "Into the Woods: 3.  Rent: 4." }
    ]
  },
  {
    id: 31,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, b: { name: "West Side Story", value: 1957, label: "opened" }, note: "Fiddler on the Roof: 1964.  West Side Story: 1957." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Newsies", value: 2, label: "Tony wins" }, b: { name: "Into the Woods", value: 3, label: "Tony wins" }, note: "Newsies: 2.  Into the Woods: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "Jersey Boys: 4,642.  Into the Woods: 765." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Sound of Music", value: 5, label: "Tony wins" }, b: { name: "Cabaret", value: 8, label: "Tony wins" }, note: "The Sound of Music: 5.  Cabaret: 8." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "In the Heights", value: 1185, label: "performances" }, b: { name: "Fiddler on the Roof", value: 3242, label: "performances" }, note: "In the Heights: 1,185.  Fiddler on the Roof: 3,242." }
    ]
  },
  {
    id: 32,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "In the Heights", value: 2008, label: "opened" }, b: { name: "Annie", value: 1977, label: "opened" }, note: "In the Heights: 2008.  Annie: 1977." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Evita", value: 7, label: "Tony wins" }, b: { name: "Hamilton", value: 11, label: "Tony wins" }, note: "Evita: 7.  Hamilton: 11." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Evita", value: 7, label: "Tony wins" }, b: { name: "West Side Story", value: 2, label: "Tony wins" }, note: "Evita: 7.  West Side Story: 2." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Les Misérables", value: 6680, label: "performances" }, b: { name: "The Sound of Music", value: 1443, label: "performances" }, note: "Les Misérables: 6,680.  The Sound of Music: 1,443." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Newsies", value: 1004, label: "performances" }, b: { name: "Cabaret", value: 1165, label: "performances" }, note: "Newsies: 1,004.  Cabaret: 1,165." }
    ]
  },
  {
    id: 33,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Gypsy", value: 1959, label: "opened" }, b: { name: "Six", value: 2021, label: "opened" }, note: "Gypsy: 1959.  Six: 2021." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Come From Away", value: 1669, label: "performances" }, b: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, note: "Come From Away: 1,669.  The Phantom of the Opera: 13,981." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, note: "Cats: 7.  Sweeney Todd: 8." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Rent", value: 5123, label: "performances" }, b: { name: "Jersey Boys", value: 4642, label: "performances" }, note: "Rent: 5,123.  Jersey Boys: 4,642." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hadestown", value: 8, label: "Tony wins" }, b: { name: "Wicked", value: 3, label: "Tony wins" }, note: "Hadestown: 8.  Wicked: 3." }
    ]
  },
  {
    id: 34,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Come From Away", value: 2017, label: "opened" }, b: { name: "Rent", value: 1996, label: "opened" }, note: "Come From Away: 2017.  Rent: 1996." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Sweeney Todd", value: 557, label: "performances" }, note: "Jersey Boys: 4,642.  Sweeney Todd: 557." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Sound of Music", value: 5, label: "Tony wins" }, b: { name: "Chicago", value: 6, label: "Tony wins" }, note: "The Sound of Music: 5.  Chicago: 6." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cabaret", value: 8, label: "Tony wins" }, b: { name: "A Chorus Line", value: 9, label: "Tony wins" }, note: "Cabaret: 8.  A Chorus Line: 9." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Newsies", value: 1004, label: "performances" }, b: { name: "Hairspray", value: 2642, label: "performances" }, note: "Newsies: 1,004.  Hairspray: 2,642." }
    ]
  },
  {
    id: 35,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "Mamma Mia!: 2001.  Avenue Q: 2003." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Sound of Music", value: 5, label: "Tony wins" }, b: { name: "Jesus Christ Superstar", value: 0, label: "Tony wins" }, note: "The Sound of Music: 5.  Jesus Christ Superstar: 0." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Jersey Boys", value: 4, label: "Tony wins" }, b: { name: "Newsies", value: 2, label: "Tony wins" }, note: "Jersey Boys: 4.  Newsies: 2." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "A Chorus Line", value: 6137, label: "performances" }, b: { name: "Evita", value: 1567, label: "performances" }, note: "A Chorus Line: 6,137.  Evita: 1,567." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Evita", value: 1567, label: "performances" }, b: { name: "Funny Girl", value: 1348, label: "performances" }, note: "Evita: 1,567.  Funny Girl: 1,348." }
    ]
  },
  {
    id: 36,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Les Misérables", value: 6680, label: "performances" }, b: { name: "Avenue Q", value: 2534, label: "performances" }, note: "Les Misérables: 6,680.  Avenue Q: 2,534." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Rent", value: 5123, label: "performances" }, b: { name: "Avenue Q", value: 2534, label: "performances" }, note: "Rent: 5,123.  Avenue Q: 2,534." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Avenue Q", value: 3, label: "Tony wins" }, b: { name: "West Side Story", value: 2, label: "Tony wins" }, note: "Avenue Q: 3.  West Side Story: 2." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Lion King", value: 6, label: "Tony wins" }, b: { name: "Jersey Boys", value: 4, label: "Tony wins" }, note: "The Lion King: 6.  Jersey Boys: 4." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "The Lion King", value: 1997, label: "opened" }, note: "A Chorus Line: 1975.  The Lion King: 1997." }
    ]
  },
  {
    id: 37,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Into the Woods", value: 3, label: "Tony wins" }, b: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, note: "Into the Woods: 3.  The Book of Mormon: 9." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "West Side Story", value: 2, label: "Tony wins" }, b: { name: "Gypsy", value: 0, label: "Tony wins" }, note: "West Side Story: 2.  Gypsy: 0." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Guys and Dolls", value: 1950, label: "opened" }, b: { name: "Sweeney Todd", value: 1979, label: "opened" }, note: "Guys and Dolls: 1950.  Sweeney Todd: 1979." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Les Misérables", value: 6680, label: "performances" }, b: { name: "Gypsy", value: 702, label: "performances" }, note: "Les Misérables: 6,680.  Gypsy: 702." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Come From Away", value: 1669, label: "performances" }, b: { name: "Cats", value: 7485, label: "performances" }, note: "Come From Away: 1,669.  Cats: 7,485." }
    ]
  },
  {
    id: 38,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "A Chorus Line", value: 9, label: "Tony wins" }, b: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, note: "A Chorus Line: 9.  Sweeney Todd: 8." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Evita", value: 1979, label: "opened" }, b: { name: "Cats", value: 1982, label: "opened" }, note: "Evita: 1979.  Cats: 1982." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Guys and Dolls", value: 5, label: "Tony wins" }, b: { name: "Come From Away", value: 1, label: "Tony wins" }, note: "Guys and Dolls: 5.  Come From Away: 1." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jesus Christ Superstar", value: 711, label: "performances" }, b: { name: "Les Misérables", value: 6680, label: "performances" }, note: "Jesus Christ Superstar: 711.  Les Misérables: 6,680." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Pippin", value: 1944, label: "performances" }, b: { name: "Dear Evan Hansen", value: 1678, label: "performances" }, note: "Pippin: 1,944.  Dear Evan Hansen: 1,678." }
    ]
  },
  {
    id: 39,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Wicked", value: 2003, label: "opened" }, b: { name: "Guys and Dolls", value: 1950, label: "opened" }, note: "Wicked: 2003.  Guys and Dolls: 1950." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Annie", value: 7, label: "Tony wins" }, note: "Sweeney Todd: 8.  Annie: 7." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Come From Away", value: 1669, label: "performances" }, b: { name: "Into the Woods", value: 765, label: "performances" }, note: "Come From Away: 1,669.  Into the Woods: 765." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "In the Heights", value: 4, label: "Tony wins" }, note: "Sweeney Todd: 8.  In the Heights: 4." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Come From Away", value: 1669, label: "performances" }, b: { name: "Rent", value: 5123, label: "performances" }, note: "Come From Away: 1,669.  Rent: 5,123." }
    ]
  },
  {
    id: 40,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Annie", value: 2377, label: "performances" }, b: { name: "Cabaret", value: 1165, label: "performances" }, note: "Annie: 2,377.  Cabaret: 1,165." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Pippin", value: 1944, label: "performances" }, b: { name: "The Sound of Music", value: 1443, label: "performances" }, note: "Pippin: 1,944.  The Sound of Music: 1,443." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hamilton", value: 11, label: "Tony wins" }, b: { name: "Chicago", value: 6, label: "Tony wins" }, note: "Hamilton: 11.  Chicago: 6." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Into the Woods", value: 1987, label: "opened" }, b: { name: "Jesus Christ Superstar", value: 1971, label: "opened" }, note: "Into the Woods: 1987.  Jesus Christ Superstar: 1971." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Guys and Dolls", value: 5, label: "Tony wins" }, b: { name: "Rent", value: 4, label: "Tony wins" }, note: "Guys and Dolls: 5.  Rent: 4." }
    ]
  },
  {
    id: 41,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, b: { name: "A Chorus Line", value: 6137, label: "performances" }, note: "The Phantom of the Opera: 13,981.  A Chorus Line: 6,137." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Avenue Q", value: 2534, label: "performances" }, b: { name: "Evita", value: 1567, label: "performances" }, note: "Avenue Q: 2,534.  Evita: 1,567." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Pippin", value: 5, label: "Tony wins" }, b: { name: "Gypsy", value: 0, label: "Tony wins" }, note: "Pippin: 5.  Gypsy: 0." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Cabaret", value: 1966, label: "opened" }, b: { name: "Jesus Christ Superstar", value: 1971, label: "opened" }, note: "Cabaret: 1966.  Jesus Christ Superstar: 1971." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Guys and Dolls", value: 5, label: "Tony wins" }, b: { name: "Jersey Boys", value: 4, label: "Tony wins" }, note: "Guys and Dolls: 5.  Jersey Boys: 4." }
    ]
  },
  {
    id: 42,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Annie", value: 2377, label: "performances" }, b: { name: "In the Heights", value: 1185, label: "performances" }, note: "Annie: 2,377.  In the Heights: 1,185." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cabaret", value: 1165, label: "performances" }, b: { name: "Avenue Q", value: 2534, label: "performances" }, note: "Cabaret: 1,165.  Avenue Q: 2,534." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "West Side Story", value: 2, label: "Tony wins" }, b: { name: "Hamilton", value: 11, label: "Tony wins" }, note: "West Side Story: 2.  Hamilton: 11." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Fiddler on the Roof", value: 1964, label: "opened" }, note: "Mamma Mia!: 2001.  Fiddler on the Roof: 1964." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Lion King", value: 6, label: "Tony wins" }, b: { name: "Fiddler on the Roof", value: 9, label: "Tony wins" }, note: "The Lion King: 6.  Fiddler on the Roof: 9." }
    ]
  },
  {
    id: 43,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hadestown", value: 8, label: "Tony wins" }, b: { name: "Gypsy", value: 0, label: "Tony wins" }, note: "Hadestown: 8.  Gypsy: 0." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "A Chorus Line", value: 1975, label: "opened" }, b: { name: "West Side Story", value: 1957, label: "opened" }, note: "A Chorus Line: 1975.  West Side Story: 1957." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "A Chorus Line", value: 6137, label: "performances" }, b: { name: "The Sound of Music", value: 1443, label: "performances" }, note: "A Chorus Line: 6,137.  The Sound of Music: 1,443." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Sweeney Todd", value: 8, label: "Tony wins" }, b: { name: "Into the Woods", value: 3, label: "Tony wins" }, note: "Sweeney Todd: 8.  Into the Woods: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Guys and Dolls", value: 1200, label: "performances" }, b: { name: "Newsies", value: 1004, label: "performances" }, note: "Guys and Dolls: 1,200.  Newsies: 1,004." }
    ]
  },
  {
    id: 44,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "West Side Story", value: 732, label: "performances" }, b: { name: "Avenue Q", value: 2534, label: "performances" }, note: "West Side Story: 732.  Avenue Q: 2,534." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Rent", value: 4, label: "Tony wins" }, b: { name: "Dear Evan Hansen", value: 6, label: "Tony wins" }, note: "Rent: 4.  Dear Evan Hansen: 6." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Oklahoma!", value: 1943, label: "opened" }, b: { name: "Dear Evan Hansen", value: 2016, label: "opened" }, note: "Oklahoma!: 1943.  Dear Evan Hansen: 2016." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Lion King", value: 6, label: "Tony wins" }, b: { name: "Into the Woods", value: 3, label: "Tony wins" }, note: "The Lion King: 6.  Into the Woods: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Guys and Dolls", value: 1200, label: "performances" }, b: { name: "Pippin", value: 1944, label: "performances" }, note: "Guys and Dolls: 1,200.  Pippin: 1,944." }
    ]
  },
  {
    id: 45,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Cabaret", value: 1165, label: "performances" }, b: { name: "Funny Girl", value: 1348, label: "performances" }, note: "Cabaret: 1,165.  Funny Girl: 1,348." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Jesus Christ Superstar", value: 1971, label: "opened" }, b: { name: "Avenue Q", value: 2003, label: "opened" }, note: "Jesus Christ Superstar: 1971.  Avenue Q: 2003." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hamilton", value: 11, label: "Tony wins" }, b: { name: "Funny Girl", value: 0, label: "Tony wins" }, note: "Hamilton: 11.  Funny Girl: 0." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Oklahoma!", value: 2212, label: "performances" }, b: { name: "Cabaret", value: 1165, label: "performances" }, note: "Oklahoma!: 2,212.  Cabaret: 1,165." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Newsies", value: 2, label: "Tony wins" }, b: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, note: "Newsies: 2.  The Book of Mormon: 9." }
    ]
  },
  {
    id: 46,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Avenue Q", value: 2534, label: "performances" }, b: { name: "Oklahoma!", value: 2212, label: "performances" }, note: "Avenue Q: 2,534.  Oklahoma!: 2,212." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "A Chorus Line", value: 9, label: "Tony wins" }, b: { name: "Gypsy", value: 0, label: "Tony wins" }, note: "A Chorus Line: 9.  Gypsy: 0." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Oklahoma!", value: 2212, label: "performances" }, note: "Jersey Boys: 4,642.  Oklahoma!: 2,212." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Six", value: 2021, label: "opened" }, note: "Mamma Mia!: 2001.  Six: 2021." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Rent", value: 4, label: "Tony wins" }, b: { name: "A Chorus Line", value: 9, label: "Tony wins" }, note: "Rent: 4.  A Chorus Line: 9." }
    ]
  },
  {
    id: 47,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Rent", value: 4, label: "Tony wins" }, b: { name: "Evita", value: 7, label: "Tony wins" }, note: "Rent: 4.  Evita: 7." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Annie", value: 2377, label: "performances" }, b: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, note: "Annie: 2,377.  The Phantom of the Opera: 13,981." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "The Book of Mormon", value: 2011, label: "opened" }, b: { name: "Hadestown", value: 2019, label: "opened" }, note: "The Book of Mormon: 2011.  Hadestown: 2019." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Hamilton", value: 11, label: "Tony wins" }, b: { name: "Cabaret", value: 8, label: "Tony wins" }, note: "Hamilton: 11.  Cabaret: 8." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Gypsy", value: 702, label: "performances" }, b: { name: "A Chorus Line", value: 6137, label: "performances" }, note: "Gypsy: 702.  A Chorus Line: 6,137." }
    ]
  },
  {
    id: 48,
    matchups: [
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Rent", value: 5123, label: "performances" }, b: { name: "The Phantom of the Opera", value: 13981, label: "performances" }, note: "Rent: 5,123.  The Phantom of the Opera: 13,981." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "In the Heights", value: 1185, label: "performances" }, b: { name: "West Side Story", value: 732, label: "performances" }, note: "In the Heights: 1,185.  West Side Story: 732." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Come From Away", value: 2017, label: "opened" }, b: { name: "A Chorus Line", value: 1975, label: "opened" }, note: "Come From Away: 2017.  A Chorus Line: 1975." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Cats", value: 7, label: "Tony wins" }, b: { name: "Avenue Q", value: 3, label: "Tony wins" }, note: "Cats: 7.  Avenue Q: 3." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Les Misérables", value: 8, label: "Tony wins" }, b: { name: "Annie", value: 7, label: "Tony wins" }, note: "Les Misérables: 8.  Annie: 7." }
    ]
  },
  {
    id: 49,
    matchups: [
      { prompt: "Which opened on Broadway LATER?", a: { name: "Mamma Mia!", value: 2001, label: "opened" }, b: { name: "Evita", value: 1979, label: "opened" }, note: "Mamma Mia!: 2001.  Evita: 1979." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, b: { name: "The Lion King", value: 6, label: "Tony wins" }, note: "Mamma Mia!: 0.  The Lion King: 6." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "Mamma Mia!", value: 0, label: "Tony wins" }, b: { name: "Into the Woods", value: 3, label: "Tony wins" }, note: "Mamma Mia!: 0.  Into the Woods: 3." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Into the Woods", value: 765, label: "performances" }, b: { name: "Les Misérables", value: 6680, label: "performances" }, note: "Into the Woods: 765.  Les Misérables: 6,680." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jersey Boys", value: 4642, label: "performances" }, b: { name: "Hairspray", value: 2642, label: "performances" }, note: "Jersey Boys: 4,642.  Hairspray: 2,642." }
    ]
  },
  {
    id: 50,
    matchups: [
      { prompt: "Which won MORE Tony Awards?", a: { name: "Come From Away", value: 1, label: "Tony wins" }, b: { name: "Wicked", value: 3, label: "Tony wins" }, note: "Come From Away: 1.  Wicked: 3." },
      { prompt: "Which opened on Broadway LATER?", a: { name: "Avenue Q", value: 2003, label: "opened" }, b: { name: "Newsies", value: 2012, label: "opened" }, note: "Avenue Q: 2003.  Newsies: 2012." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Gypsy", value: 702, label: "performances" }, b: { name: "Annie", value: 2377, label: "performances" }, note: "Gypsy: 702.  Annie: 2,377." },
      { prompt: "Which had MORE original-run Broadway performances?", a: { name: "Jesus Christ Superstar", value: 711, label: "performances" }, b: { name: "Guys and Dolls", value: 1200, label: "performances" }, note: "Jesus Christ Superstar: 711.  Guys and Dolls: 1,200." },
      { prompt: "Which won MORE Tony Awards?", a: { name: "The Book of Mormon", value: 9, label: "Tony wins" }, b: { name: "Gypsy", value: 0, label: "Tony wins" }, note: "The Book of Mormon: 9.  Gypsy: 0." }
    ]
  }
  ];
  window.ShowdownPuzzles = (window.ShowdownPuzzles || []).concat(GEN);
})();
