/* 5-letter word list for the grid generator.
   Roughly 1000 hand-picked common English words plus a tail of theater-leaning
   ones. To expand: paste more words (space- or newline-separated, any case)
   into the string below. Anything that's not exactly 5 letters is filtered out.

   Larger public-domain word lists are easy to find (search "english 5 letter
   words txt"). Drop in 3000+ for richer grid variety.
*/
window.WORDS_5 = (`
ABACK ABATE ABBEY ABBOT ABETS ABIDE ABLED ABODE ABORT ABOUT ABOVE ABUSE ABYSS
ACORN ACRID ACTOR ACUTE ADAGE ADAPT ADEPT ADMIT ADOPT ADORE ADORN ADULT AFIRE
AFOOT AFOUL AFTER AGAIN AGAPE AGATE AGENT AGING AGLOW AGONY AGREE AHEAD AIDED
AIDES AIMED AISLE ALARM ALBUM ALERT ALGAE ALIBI ALIEN ALIGN ALIKE ALIVE ALLAY
ALLEY ALLOT ALLOW ALLOY ALOFT ALOHA ALONE ALONG ALOOF ALOUD ALPHA ALTAR ALTER
AMASS AMBER AMBLE AMEND AMISS AMITY AMONG AMPLE AMPLY AMUSE ANGEL ANGER ANGLE
ANGRY ANGST ANIME ANKLE ANNEX ANNOY ANNUL ANODE ANTIC ANVIL AORTA APART APHID
APING APPLE APPLY APRON APTLY ARBOR ARDOR ARENA ARGUE ARISE ARMED AROMA AROSE
ARRAY ARROW ARSON ARTSY ASIDE ASKED ASKEW ASSAY ASSET ATLAS ATOLL ATTIC AUDIO
AUDIT AUNTS AVAIL AVERT AVIAN AVOID AWAIT AWAKE AWARD AWARE AWASH AWFUL AWOKE
AXIAL AZURE
BACON BADGE BADLY BAGEL BAGGY BAKED BAKER BALES BALLS BANAL BANDS BANJO BANKS
BARGE BASIC BASIN BASKS BASSO BASTE BATCH BATHS BATON BATTY BEACH BEADS BEAKS
BEAMS BEANS BEARD BEARS BEAST BEATS BEEFY BEERS BEFIT BEGAN BEGET BEGIN BEGUN
BEING BELCH BELIE BELLS BELLY BELOW BELTS BENCH BENDS BERTH BERYL BESET BIBLE
BIDES BIGOT BIKED BIKER BIKES BILGE BILLS BILLY BINGE BINGO BIRCH BIRDS BIRTH
BISON BITES BLACK BLADE BLAME BLAND BLANK BLARE BLAST BLAZE BLEAK BLEAT BLEED
BLEEP BLEND BLESS BLIMP BLIND BLINK BLISS BLITZ BLOAT BLOCK BLOCS BLOND BLOOD
BLOOM BLOWN BLOWS BLUER BLUES BLUFF BLUNT BLURB BLURT BLUSH BOARD BOARS BOAST
BOATS BOBBY BODES BOGEY BOGGY BOILS BOLTS BOMBS BONDS BONES BONUS BOOBY BOOKS
BOOST BOOTH BOOTS BOOTY BOOZE BOOZY BORED BORES BORIC BORNE BORON BOSOM BOSSY
BOSUN BOTCH BOUGH BOUND BOWED BOWEL BOWER BOWLS BOXED BOXER BOXES BRACE BRAID
BRAIN BRAKE BRAND BRASH BRASS BRAVE BRAWL BRAWN BREAD BREAK BREED BRIBE BRICK
BRIDE BRIEF BRINE BRING BRINK BRINY BRISK BROAD BROIL BROKE BROOD BROOK BROOM
BROTH BROWN BROWS BRUNT BRUSH BRUTE BUCKS BUDGE BUGGY BUILD BUILT BULBS BULGE
BULKY BULLS BULLY BUMPS BUMPY BUNCH BUNNY BURLY BURNS BURRO BURRS BURST BUSED
BUSES BUSHY BUSTS BUTTE BUTTS BUYER BYLAW
CABAL CABIN CABLE CACHE CACTI CADET CAGED CAGES CAKED CAKES CAMEL CAMEO CAMPS
CANAL CANDY CANES CANNY CANOE CANON CAPED CAPER CAPES CARDS CARED CARES CARGO
CAROL CARPS CARRY CARTS CARVE CASED CASES CASTE CASTS CATCH CATER CATTY CAULK
CAUSE CAVED CAVES CEASE CECUM CEDAR CELLO CELLS CENTS CHAFE CHAFF CHAIN CHAIR
CHALK CHAMP CHANT CHAOS CHAPS CHARD CHARM CHART CHASE CHASM CHEAP CHEAT CHECK
CHEEK CHEER CHEFS CHESS CHEST CHEWS CHEWY CHICK CHIDE CHIEF CHILD CHILE CHILI
CHILL CHIME CHIMP CHINA CHINS CHIPS CHIRP CHOCK CHOIR CHOKE CHOMP CHOPS CHORD
CHORE CHOSE CHUCK CHUMP CHUNK CHURN CHUTE CIDER CIGAR CINCH CIRCA CIRCS CITED
CITES CIVIC CIVIL CLACK CLAIM CLAMP CLAMS CLANG CLANK CLANS CLAPS CLASH CLASP
CLASS CLAVE CLAWS CLEAN CLEAR CLEAT CLERK CLICK CLIFF CLIMB CLINE CLING CLINK
CLIPS CLOAK CLOCK CLODS CLOGS CLONE CLOSE CLOTH CLOTS CLOUD CLOUT CLOVE CLOWN
CLUBS CLUCK CLUED CLUES CLUMP CLUNG CLUNK COACH COALS COARS COASR COATS COBRA
COCOA CODED CODES COILS COINS COLAS COLDS COLON COLOR COMET COMFY COMIC COMMA
CONCH CONDO CONES CONIC COOED COOKS COOLS COOPS COPED COPES COPRA CORAL CORDS
CORED CORES CORGI CORKS CORNS CORNY CORPS CORYS COSTS COUCH COUGH COULD COUNT
COUPE COURT COVEN COVER COVES COVET COWED COWER COZEN CRABS CRACK CRAFT CRAGS
CRAMP CRANE CRANK CRASH CRATE CRAVE CRAZE CRAZY CREAK CREAM CREDO CREEK CREEL
CREEP CREPE CRESS CREST CREWS CRIBS CRICK CRIED CRIER CRIES CRIME CRIMP CRISP
CROAK CROCK CROFT CRONE CRONY CROOK CROON CROPS CROSS CROUP CROWD CROWN CROWS
CRUDE CRUEL CRUET CRUMB CRUMP CRUSH CRUST CRYPT CUBED CUBES CUBIC CUDDL CUFFS
CULLS CULTS CUMIN CUPID CURBS CURDS CURED CURER CURES CURIO CURLS CURLY CURRY
CURSE CURVE CURVY CUSPS CYCLE CYNIC
DADDY DAILY DAIRY DAISY DALES DAMES DAMPS DANCE DANDY DARED DARES DARTS DATED
DATES DAUNT DAZED DEALS DEALT DEANS DEARS DEATH DEBIT DEBTS DEBUG DEBUT DECAF
DECAL DECAY DECKS DECOR DECOY DECRY DEEDS DEEMS DEEPS DEERS DEFER DEIFY DEIST
DEITY DELAY DELLS DELTA DELVE DEMOS DEMUR DENIM DENSE DEPOT DEPTH DERBY DESKS
DETER DEUCE DEVIL DEWED DIALS DICED DICES DIDST DIETS DIGIT DILLY DIMER DIMES
DIMLY DINED DINER DINES DINGO DINGY DINKY DIODE DIRGE DIRTY DISCO DISCS DISHY
DITCH DITTO DITTY DIVAS DIVED DIVER DIVES DIZZY DOCKS DODGE DODGY DOERS DOES'
DOGMA DOILY DOING DOLLS DOLLY DOLTS DOMED DOMES DONOR DONUT DOPED DOPES DORKY
DORMS DOSED DOSES DOTED DOTES DOUBT DOUGH DOUSE DOWEL DOWER DOWNS DOWNY DOWRY
DOZED DOZEN DOZES DRAFT DRAIN DRAKE DRAMA DRANK DRAPE DRAWL DRAWN DRAWS DREAD
DREAM DREAR DRESS DRIED DRIER DRIES DRIFT DRILL DRINK DRIPS DRIVE DROIT DROLL
DRONE DROOL DROOP DROPS DROSS DROVE DROWN DRUGS DRUMS DRUNK DRYAD DRYER DRYLY
DUCAT DUCHY DUCKS DUCKY DUDES DUELS DUETS DULLY DUMBO DUMMY DUMPS DUMPY DUNCE
DUNES DUSKY DUSTS DUSTY DUTCH DWARF DWELL DWELT DYING DYNES
EAGER EAGLE EARED EARLS EARLY EARNS EARTH EASEL EASES EATEN EATER EAVES EBBED
EBONS EBONY ECHOS EDGED EDGES EDICT EDIFY EDITS EERIE EGRET EIGHT EJECT EKING
ELATE ELBOW ELDER ELECT ELEGY ELFIN ELIDE ELITE ELOPE ELUDE ELVES EMAIL EMBED
EMBER EMITS EMPTY ENACT ENDED ENDOW ENEMA ENEMY ENJOY ENNUI ENROL ENSUE ENTER
ENTRY ENVOY EPICS EPOCH EPOXY EQUAL EQUIP ERASE ERECT ERROR ERUPT ESSAY ESTER
ETHER ETHIC ETHOS EVADE EVENT EVERY EVICT EVILS EVOKE EXACT EXALT EXAMS EXCEL
EXERT EXILE EXIST EXITS EXPEL EXTOL EXTRA EXUDE EXULT EYING
FABLE FACED FACES FACET FACTS FADED FADER FADES FAILS FAINT FAIRS FAIRY FAITH
FAKED FAKER FAKES FALLS FALSE FAMED FANCY FANGS FANNY FARCE FARED FARES FARMS
FATAL FATED FATES FATTY FAULT FAUNA FAVOR FAWNS FAXES FEARS FEAST FEATS FECAL
FEDS' FEEDS FEELS FELON FENCE FENDS FERAL FERNS FERRY FETAL FETCH FETED FETID
FEUDS FEVER FEWER FIBER FICUS FIEFS FIELD FIEND FIERY FIFTH FIFTY FIGHT FILED
FILER FILES FILLS FILLY FILMS FILMY FILTH FINAL FINCH FINDS FINED FINES FINIS
FIRED FIRER FIRES FIRMS FIRST FISHY FISTS FIVES FIXED FIXER FIXES FJORD FLACK
FLAGS FLAIL FLAIR FLAKE FLAKY FLAME FLANK FLAPS FLARE FLASH FLASK FLATS FLECK
FLED FLEDS FLEES FLEET FLESH FLICK FLIER FLIES FLING FLINT FLIPS FLIRT FLITS
FLOAT FLOCK FLOES FLOGS FLOOD FLOOR FLOPS FLORA FLOSS FLOUR FLOUT FLOWN FLOWS
FLUFF FLUID FLUKE FLUNG FLUNK FLUSH FLUTE FLYBY FOAMS FOAMY FOCAL FOCUS FOGGY
FOIBL FOILS FOIST FOLDS FOLIO FOLKS FOLKY FONTS FORAY FORCE FORDS FORGE FORGO
FORKS FORMS FORTE FORTH FORTS FORTY FORUM FOSSA FOULS FOUND FOURS FOWLS FOXED
FOYER FRAIL FRAME FRANK FRAUD FREAK FREED FREER FREES FRESH FRETS FRIAR FRIED
FRIES FRILL FRISK FROCK FROGS FROND FRONT FROST FROTH FROWN FROZE FRUIT FUDGE
FUGUE FULLY FUMED FUMES FUNDS FUNKY FUNNY FURLS FURRY FURZE FUSED FUSES FUSSY
FUSTY FUZZY
GABBY GAFFE GAILY GAINS GALAS GALES GALLS GAMED GAMER GAMES GAMEY GAMMA GAMUT
GAPED GAPES GARBS GASES GASPS GATES GAUDY GAUGE GAUNT GAUZE GAUZY GAVEL GAWKS
GAWKY GAYER GAYLY GAZED GAZES GECKO GEEKS GEEKY GEESE GELDS GEMMY GENES GENIE
GENRE GENTS GENUS GERMS GETUP GHOST GHOUL GIANT GIDDY GIFTS GILDS GILLS GIMME
GIRDS GIRLS GIRLY GIRTH GIVEN GIVER GIVES GLADE GLADS GLAND GLARE GLASS GLAZE
GLEAM GLEAN GLEES GLENS GLIBS GLIDE GLINT GLOAT GLOBE GLOBS GLOOM GLORY GLOSS
GLOVE GLOWS GLUED GLUES GLUEY GLUTS GNARL GNASH GNATS GNAWS GNOME GOADS GOALS
GOATS GODLY GOFER GOING GOLDS GOLEM GOLFS GONER GONGS GOODS GOODY GOOEY GOOFS
GOOFY GOOSE GORED GORES GORGE GORSE GOUGE GOURD GRACE GRADE GRADS GRAFT GRAIL
GRAIN GRAMS GRAND GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAYS GRAZE
GREAT GREED GREEN GREET GREYS GRIEF GRILL GRIME GRIMY GRIND GRIPE GRIPS GRIST
GRITS GROAN GROIN GROOM GROPE GROSS GROUP GROUT GROVE GROWL GROWN GROWS GRUBS
GRUEL GRUFF GRUMP GRUNT GUARD GUAVA GUESS GUEST GUFFS GUIDE GUIDS GUILD GUILE
GUILT GULFS GULLS GULLY GULPS GUMBO GUMMY GUPPY GURUS GUSHY GUSTO GUSTS GUSTY
GUTSY GUYED GYPSY GYRES GYRO'
HABIT HACKS HADJI HAIKU HAIRS HAIRY HALES HALLS HALVE HANDS HANDY HANGS HARDY
HARED HARES HARMS HARPS HARSH HASTE HASTY HATCH HATED HATER HATES HAULS HAUNT
HAVEN HAVOC HAWKS HAYED HAZEL HAZER HAZES HEADS HEADY HEALS HEAPS HEARD HEARS
HEART HEATH HEATS HEAVE HEAVY HEDGE HEEDS HEELS HEFTS HEFTY HEIRS HELIO HELIX
HELLO HELMS HELPS HENCE HERBS HERDS HERON HEWED HIDED HIDER HIDES HIGHS HIKED
HIKER HIKES HILLS HILLY HILTS HINDS HINGE HINTS HIPPO HIPPY HIRED HIRES HITCH
HIVES HOARD HOARS HOARY HOBBY HOCKS HOIST HOLDS HOLES HOLLY HOMED HOMES HONED
HONES HONEY HONKS HONOR HOODS HOOFS HOOKS HOOKY HOOPS HOOTS HOPED HOPES HORDE
HORNS HORNY HORSE HOSED HOSES HOTEL HOUND HOURS HOUSE HOVEL HOVER HOWLS HUBBY
HUFFS HUFFY HULAS HULKS HULLS HUMAN HUMID HUMOR HUMPS HUMUS HUNCH HUNKS HUNKY
HUNTS HURLS HURTS HUSKS HUSKY HUSSY HUTCH HYENA HYMEN HYMNS HYPED HYPER HYPES
IAMBS ICIER ICILY ICING IDEAL IDEAS IDIOM IDIOT IDLED IDLER IDLES IDOLS IGLOO
ILIUM IMAGE IMBUE IMPEL IMPLY INANE INDEX INDIA INEPT INERT INFER INGOT INKED
INKER INLAY INLET INPUT INTEL INTER INTRO IRATE IRKED IRONS IRONY ISLES ISLET
ISSUE ITCHY ITEMS IVORY
JABS' JACKS JADED JADES JAGGY JAILS JAMBS JARED JARS' JAUNT JAWED JAZZY JEANS
JELLY JEMMY JERKS JERKY JEST' JESTS JESUS JETTY JEWEL JIBES JIFFY JIHAD JILTS
JINKS JIVED JIVES JOINS JOINT JOIST JOKED JOKER JOKES JOLLY JOLTS JOULE JOUST
JOWLS JOYED JOYS' JUDGE JUICE JUICY JUMBO JUMPS JUMPY JUNCO JUNKS JUNKY JURAL
JURIE JUROR
KAYAK KAZOO KEEPS KELLY KELPS KENDO KEYED KICKS KILLS KILNS KILOS KILTS KINDS
KINGS KINKS KINKY KIOSK KITES KITTY KIWIS KNACK KNAVE KNEAD KNEED KNEEL KNELL
KNELT KNIFE KNOBS KNOCK KNOLL KNOTS KNOWN KNOWS KOALA KOOKS KOOKY KOREA KUDOS
LABEL LABOR LACED LACES LACKS LADED LADEN LADLE LAGER LAIRS LAKES LAMBS LAMED
LAMER LAMPS LANCE LANDS LANES LAPEL LAPSE LARCH LARGE LARGO LARKS LASER LASTS
LATCH LATER LATEX LATHE LAUGH LAVAS LAYED LAYER LAZED LAZES LAZIE LEACH LEADS
LEAFS LEAFY LEAKS LEAKY LEANS LEAPS LEAPT LEARN LEASE LEASH LEAST LEAVE LEERY
LEERY LEFTS LEFTY LEGAL LEGOS LEMMA LEMON LEMUR LEND' LENDS LEPER LEVEE LEVEL
LEVER LIARS LIBEL LIBYA LICKS LIDDED LIEGE LIENS LIFER LIFTS LIGHT LIKED LIKEN
LIKES LILAC LILTS LIMBO LIMBS LIMED LIMES LIMEY LIMIT LIMPS LINED LINEN LINER
LINES LINGO LINKS LINTS LIONS LIPID LISLE LISPS LISTS LIVED LIVEN LIVER LIVES
LLAMA LOADS LOAFS LOANS LOATH LOBBY LOBED LOBES LOCAL LOCKS LOCUS LODGE LOFTS
LOFTY LOGGY LOGIC LOGOS LOINS LOLLY LONER LONGS LOOKS LOOMS LOONS LOOPS LOOPY
LOOSE LOOTS LOPED LOPES LORDS LORES LORRY LOSER LOSES LOTUS LOUSE LOUSY LOUTS
LOVED LOVER LOVES LOWED LOWER LOWLY LOYAL LUCID LUCKY LULLS LULUS LUMPS LUMPY
LUNAR LUNCH LUNGE LUNGS LUPUS LURCH LURED LURES LURID LUSTS LUSTY LUTES LYING
LYMPH LYNCH LYRES LYRIC
MACAW MACES MACHO MACRO MADAM MADLY MAFIA MAGIC MAGUS MAIDS MAILS MAIMS MAINS
MAJOR MAKER MAKES MALES MAMBO MAMMA MAMMY MANED MANES MANGO MANGY MANIA MANIC
MANLY MANNA MANOR MANSE MAPLE MARCH MARES MARKS MARRY MARSH MASKS MASON MASSE
MASTS MATCH MATED MATES MATHS MATTE MAUVE MAVEN MAXED MAYBE MAYOR MAYAS MAZED
MAZES MEALS MEALY MEANS MEANT MEATS MEATY MECCA MEDAL MEDIA MEDIC MEEKS MEETS
MELDS MELEE MELON MELTS MEMOS MENDS MENSA MENUS MERCY MERGE MERIT MERRY MESHY
MESON MESSY METAL METED METER METRO MEWED MICAS MICRO MIDGE MIDST MIGHT MILES
MILKS MILKY MILLS MIMED MIMES MIMIC MINCE MINDS MINED MINER MINES MINGS MINIM
MINKS MINOR MINTS MINTY MINUS MIRED MIRES MIRTH MISER MISES MISSY MISTS MISTY
MITER MITES MITTS MIXED MIXER MIXES MIXUP MOANS MOATS MOCHA MOCKS MODAL MODEL
MODEM MODES MOIST MOLAR MOLDS MOLDY MOLES MOLTS MONEY MONKS MONTH MOOCH MOODS
MOODY MOONS MOORS MOOSE MOPED MOPES MORAL MORES MORONS MORPH MORSE MOSSY MOTEL
MOTHS MOTHY MOTIF MOTOR MOTTO MOUND MOUNT MOURN MOUSE MOUTH MOVED MOVER MOVES
MOVIE MOWED MOWER MUCKY MUDDY MUFTI MUGGY MULCH MULES MUMBO MUMMY MUMPS MUNCH
MURAL MUSED MUSES MUSHY MUSIC MUSKS MUSKY MUSTS MUSTY MUTED MUTES MUTTS MUZZY
MYRIAD MYTHS
NABBED NADIR NAILS NAIVE NAKED NAMED NAMES NANNY NAPES NARKS NASAL NASTY NATAL
NAVAL NAVES NAVEL NAVES NEATS NECKS NEEDS NEEDY NEIGH NERDS NERDY NERVE NESTS
NEVER NEWER NEWLY NEWSY NEXUS NICER NICHE NICKS NIECE NIFTY NIGHT NIHIL NIMBI
NINES NINNY NINTH NIPPY NITER NITRO NOBLE NOBLY NODAL NODDED NODES NOISE NOISY
NOMAD NONCE NONES NOOKS NOONS NOOSE NORMS NORTH NOSED NOSES NOSEY NOTCH NOTED
NOTES NOUNS NOVAS NOVEL NUDES NUDGE NULLS NUMBS NURSE NUTSY NYLON NYMPH
OARED OARS' OASES OASIS OATEN OATHS OBESE OBEYS OBOES OCEAN OCHER OCTAL OCTET
ODDLY ODORS OFFAL OFFER OFTEN OGLED OGLER OGLES OGRES OILED OILER OINKS OKAPI
OKAYS OLDEN OLDER OLDIE OLIVE OLIVES OMBRE OMEGA ONCES ONION ONSET OOZED OOZES
OPALS OPENS OPERA OPINE OPIUM OPTIC OPTED ORALS ORANG ORATE ORBIT ORCAS ORDER
OREOS ORGAN OSIER OTHER OTTER OUGHT OUNCE OUSTS OUTDO OUTED OUTER OUTGO OUTRE
OVALS OVARY OVATE OVENS OVERS OWING OWLET OWNED OWNER OXBOW OXIDE OXLIP OZONE
PACED PACER PACES PACKS PACTS PAGAN PAGED PAGER PAGES PAILS PAINS PAINT PAIRS
PALED PALES PALMS PALMY PALSY PANDA PANED PANEL PANES PANGS PANIC PANTS PAPAS
PAPAL PAPER PARES PARKA PARKS PARRY PARSE PARTS PARTY PASSE PASTA PASTE PASTS
PASTY PATCH PATED PATES PATHS PATIO PATSY PATTY PAUSE PAVED PAVES PAWED PAWNS
PAYED PAYEE PAYER PEACE PEACH PEAKS PEALS PEARL PEARS PEASE PECAN PECKS PEDAL
PEEKS PEELS PEEPS PEERS PEEVE PEKOE PELTS PENAL PENCE PENNE PENNY PEONS PEONY
PERCH PERIL PERKS PERKY PERMS PESKY PESOS PESTO PETAL PETER PETIT PETTY PEWEE
PHASE PHIAL PHONE PHONO PHONY PHOTO PHYLA PIANO PICKS PIECE PIERS PIETY PIGGY
PILED PILES PILLS PIMPS PINCH PINED PINES PINEY PINGS PINKS PINKY PINTO PINTS
PIOUS PIPED PIPER PIPES PIPIT PIQUE PISTON PITAS PITCH PITHY PITIES PITON PIVOT
PIXEL PIXIE PIZZA PLACE PLAID PLAIN PLAIT PLANE PLANK PLANS PLANT PLATE PLATS
PLAYS PLAZA PLEAD PLEAS PLEAT PLEBE PLIED PLIES PLOPS PLOTS PLOWS PLOYS PLUCK
PLUGS PLUMB PLUME PLUMP PLUMS PLUNK PLUSH POACH POCKS PODGY POEMS POETS POINT
POISE POKED POKER POKES POKEY POLED POLES POLIO POLKA POLLS POLOS POLYP PONDS
PONGY POOCH POOPS POORS POPES POPPY PORCH PORED PORES PORKY POSED POSER POSES
POSIT POSSE POSTS POSTY POTSY POTTY POUCH POULT POUND POURS POUTS POUTY POWER
PRAMS PRANK PRAWN PRAYS PREEN PRESS PREST PREYS PRICE PRICK PRICY PRIDE PRIED
PRIES PRIGS PRIMA PRIME PRIMP PRINT PRION PRIOR PRISM PRIVY PRIZE PROBE PRODS
PROFS PRONE PRONG PROOF PROPS PROSE PROSY PROUD PROVE PROVO PROWL PROWS PROXY
PRUDE PRUDS PRUNE PSALM PSEUD PSYCH PUDGY PUFFS PUFFY PUKED PUKES PULLS PULPS
PULPY PULSE PUMAS PUMPS PUNCH PUNKS PUNKY PUNTS PUPAS PUPIL PUPPY PUREE PURER
PURGE PURRS PURSE PURSY PUSHY PUSSY PUTTS PUTTY PYGMY PYRES PYREX
QUACK QUADS QUAFF QUAIL QUAKE QUAKY QUALM QUARK QUART QUASH QUASI QUAYS QUEEN
QUEER QUELL QUERY QUEST QUEUE QUICK QUIDS QUIET QUIFF QUILL QUILT QUINT QUIPS
QUIRE QUIRK QUIRT QUITE QUITS QUOIT QUOTA QUOTE QUOTH
RABBI RABID RACED RACER RACES RACKS RADAR RADII RADIO RADON RAFTS RAGED RAGES
RAIDS RAILS RAINS RAINY RAISE RAJAH RAKED RAKES RALLY RAMMY RAMPS RANCH RANDOM
RANDS RANGE RANGY RANKS RANTS RAPED RAPES RAPID RARER RASPS RASPY RATED RATER
RATES RATIO RATTY RAVED RAVEL RAVEN RAVER RAVES RAYED RAZED RAZER RAZES RAZOR
REACH REACT READS READY REALM REAMS REAPS REARS REBAR REBEL REBID REBUS REBUT
RECAP RECON RECUR REDOX REEDS REEDY REEFS REEKS REEKY REELS REFER REFIT REIGN
REINS RELAX RELAY RELIC REMIT RENAL RENDS RENEW RENTS REPAY REPEL REPLY RERAN
RERUN RESET RESIN RESTS RETCH RETRY REUSE REVEL REVUE RHINO RHOMB RHYME RICED
RICER RICES RICHT RICIN RIDER RIDES RIDGE RIFER RIFFS RIFLE RIFTS RIGGS RIGHT
RIGID RILED RILES RIMES RIMED RINDS RINGS RINKS RINSE RIPED RIPEN RIPER RIPES
RISEN RISES RISKS RISKY RIVAL RIVED RIVER RIVES RIVET ROACH ROADS ROAMS ROARS
ROAST ROBED ROBES ROBIN ROBOT ROCKS ROCKY RODEO ROGER ROGUE ROILS ROLES ROLLS
ROMAN ROMEO ROOFS ROOKS ROOKY ROOMS ROOMY ROOST ROOTS ROOTY ROPED ROPES ROSIN
ROSEN ROSES ROTAS ROTOR ROUGE ROUGH ROUND ROUSE ROUTE ROUTS ROVED ROVER ROVES
ROWED ROWER ROYAL RUBLE RUDDY RUDER RUFFS RUGBY RUINS RULED RULER RULES RUMBA
RUMMY RUMOR RUMPS RUNES RUNGS RUNIC RUNNY RUNTS RUNTY RUNWAY RUPEE RURAL RUSES
RUSHY RUSTS RUSTY RUTTY
SABER SABLE SABRE SACKS SADLY SAFER SAFES SAGAS SAGES SAILS SAINT SALAD SALES
SALLY SALON SALSA SALTS SALTY SALVE SALVO SAMBA SANDS SANDY SANER SANGS SAPPY
SARGE SASSY SATED SATIN SATYR SAUCE SAUCY SAUNA SAVED SAVER SAVES SAVOR SAVVY
SAWED SAYER SCABS SCADS SCALD SCALE SCALP SCALY SCAMP SCAMS SCANT SCARE SCARF
SCARS SCARY SCATS SCENE SCENT SCION SCOFF SCOLD SCONE SCOOP SCOOT SCOPE SCORE
SCORN SCOTS SCOUR SCOUT SCOWL SCRAM SCRAP SCREE SCREW SCRIM SCRIP SCRUB SCUBA
SCUDS SCUFF SCULL SCURF SEALS SEAMS SEAMY SEARS SEATS SEDAN SEDGE SEEDS SEEDY
SEEKS SEEMS SEEPS SEERS SEINE SEIZE SELLS SEMIS SENDS SENOR SENSE SEPIA SEPSI
SERFS SERGE SERIF SERUM SERVE SETUP SEVEN SEVER SEWED SEWER SEXES SHACK SHADE
SHADY SHAFT SHAGS SHAH' SHAKE SHAKY SHALE SHALL SHALT SHAME SHAMS SHANK SHAPE
SHARD SHARE SHARK SHARP SHAVE SHAWL SHAYS SHEAR SHEDS SHEEN SHEEP SHEER SHEET
SHEIK SHELF SHELL SHEWN SHIED SHIFT SHIMS SHINE SHINS SHINY SHIPS SHIRE SHIRK
SHIRT SHITS SHIVA SHOAL SHOCK SHOED SHOES SHONE SHOOK SHOOS SHOOT SHOPS SHORE
SHORN SHORT SHOTS SHOUT SHOVE SHOWN SHOWS SHOWY SHRED SHREW SHRUB SHRUG SHUCK
SHUNS SHUNT SHUSH SHUTS SHYER SHYLY SICKS SIDED SIDES SIDLE SIEGE SIEVE SIFTS
SIGHS SIGHT SIGMA SIGNS SILKS SILKY SILLY SILOS SILTS SILTY SINCE SINEW SINGS
SINKS SIRED SIREN SIRES SISAL SISSY SITAR SIXES SIXTH SIXTY SIZED SIZER SIZES
SKATE SKEET SKEIN SKIDS SKIED SKIER SKIES SKIFF SKILL SKIMP SKIMS SKINS SKINY
SKIPS SKIRT SKULK SKULL SKUNK SLABS SLACK SLAIN SLAKE SLAMS SLANG SLANT SLAPS
SLASH SLATE SLATS SLAVE SLAWS SLAYS SLEDS SLEEK SLEEP SLEET SLEPT SLICE SLICK
SLIDE SLIME SLIMY SLING SLINK SLIPS SLITS SLOBS SLOES SLOGS SLOOP SLOPE SLOPS
SLOSH SLOTH SLOTS SLOWS SLUGS SLUMP SLUMS SLUNG SLURS SLUSH SMACK SMALL SMART
SMASH SMEAR SMELL SMELT SMILE SMIRK SMITE SMITH SMOCK SMOGS SMOKE SMOKY SMOTE
SNACK SNAFU SNAGS SNAIL SNAKE SNAKY SNAPS SNARE SNARL SNEAK SNEER SNIDE SNIFF
SNIPE SNIPS SNITS SNOBS SNOOP SNORE SNORT SNOUT SNOWS SNOWY SNUBS SNUFF SOAKS
SOAPS SOAPY SOARS SOBER SOCKS SODAS SOFAS SOFTY SOGGY SOILS SOLAR SOLDS SOLES
SOLID SOLOS SOLVE SONAR SONGS SONIC SOOTH SOOTS SOOTY SOPPY SOREL SORES SORRY
SORTS SOULS SOUND SOUPS SOUPY SOURS SOUTH SOWED SPACE SPADE SPANK SPANS SPARE
SPARK SPARS SPASM SPATE SPATS SPAWN SPAYS SPEAK SPEAR SPECK SPECS SPEED SPELL
SPELT SPEND SPENT SPERM SPEWS SPICE SPICY SPIED SPIES SPIKE SPIKY SPILL SPILT
SPINE SPINS SPINY SPIRE SPITE SPITS SPLAT SPLIT SPOIL SPOKE SPOOF SPOOK SPOOL
SPOON SPORE SPORT SPOTS SPOUT SPRAY SPREE SPRIG SPUDS SPUNK SPURN SPURS SPURT
SPYUP SQUAB SQUAD SQUAT SQUAW SQUIB SQUID STABS STACK STAFF STAGE STAGS STAID
STAIN STAIR STAKE STALE STALK STALL STAMP STAND STANK STAPH STARE STARK STARS
START STASH STATE STATS STAVE STAYS STEAD STEAK STEAL STEAM STEED STEEL STEEP
STEER STEMS STENO STEPS STERN STEW' STEWS STICK STIES STIFF STILE STILL STILT
STING STINK STINT STIRS STOAT STOCK STOIC STOKE STOLE STOMP STONE STONY STOOD
STOOL STOOP STOPS STORE STORK STORM STORY STOUT STOVE STOWS STRAP STRAW STRAY
STREP STREW STRIP STROP STRUT STUBS STUCK STUDS STUDY STUFF STUMP STUNG STUNK
STUNS STUNT STYLE STYLI SUAVE SUCKS SUEDE SUGAR SUING SUITE SUITS SULKS SULKY
SUMAC SUMOS SUMPS SUNNY SUNUP SUPER SURER SURFS SURFY SURGE SUSHI SWABS SWAGS
SWAIN SWAMI SWAMP SWANS SWAPS SWARD SWARM SWASH SWATH SWATS SWAYS SWEAR SWEAT
SWEEP SWEET SWELL SWEPT SWIFT SWIGS SWILL SWIMS SWINE SWING SWIPE SWIRL SWISH
SWISS SWOON SWOOP SWORD SWORE SWORN SWUNG SYLPH SYNCH SYNCS SYNOD SYRUP
TABBY TABLE TABOO TACIT TACKS TACKY TACOS TAFFY TAILS TAINT TAKEN TAKER TAKES
TALCS TALES TALKS TALKY TALLY TAMER TAMED TAMES TANGO TANGS TANGY TANKS TAPAS
TAPED TAPER TAPES TAPIR TARDY TARES TARNS TAROT TARPS TARRY TARTS TARTY TASKS
TASTE TASTY TATTY TAUNT TAUPE TAUTS TAWNY TAXED TAXER TAXES TAXIS TEACH TEAKS
TEALS TEAMS TEARS TEARY TEASE TECHS TEEMS TEENS TEENY TEETH TELLS TEMPO TEMPS
TEMPT TENDS TENET TENON TENOR TENSE TENTH TENTS TEPEE TEPID TERMS TERNS TERRA
TERSE TESTS TESTY TEXTS THANE THANK THATS THAWS THEFT THEIR THEME THERE THESE
THETA THICK THIEF THIGH THINE THING THINK THINS THIRD THONG THORN THOSE THOUS
THREE THREW THROB THROE THROW THRUM THUDS THUGS THUMB THUMP THYME TIARA TIBIA
TICKS TIDAL TIDED TIDES TIERS TIFFS TIGER TIGHT TILDE TILED TILER TILES TILLS
TILTS TIMED TIMER TIMES TIMID TINES TINGE TINNY TINTS TIPPY TIPSY TIRED TIRES
TITAN TITHE TITLE TIZZY TOADS TOAST TODAY TODDY TOFFS TOILS TOKEN TOKES TOLLS
TOMBS TOMES TONAL TONED TONER TONES TONGA TONGS TONIC TOOLS TOOTH TOOTS TOPAZ
TOPIC TOQUE TORAH TORCH TORIC TORSO TORTE TORUS TOTAL TOTED TOTES TOTEM TOUCH
TOUGH TOURS TOUTS TOWED TOWEL TOWER TOWNS TOXIC TOXIN TOYED TRACE TRACK TRACT
TRADE TRAIL TRAIN TRAIT TRAMP TRAMS TRAPS TRASH TRAYS TREAD TREAT TREED TREES
TREKS TREND TRESS TRIAD TRIAL TRIBE TRICE TRICK TRIED TRIER TRIES TRILL TRIMS
TRIOS TRIPE TRIPS TRITE TROLL TROOP TROOPS TROPE TROTH TROTS TROUT TROVE TRUCE
TRUCK TRULY TRUMP TRUNK TRUSS TRUST TRUTH TRYST TUBAS TUBED TUBER TUBES TUCKS
TUFTS TUFTY TULIP TULLE TUMID TUMMY TUNAS TUNED TUNER TUNES TUNGS TUNIC TURBO
TURFS TURFY TURKS TURNS TURNT TUSKS TUTOR TUTTI TUTUS TWAIN TWANG TWEAK TWEED
TWEET TWERP TWICE TWIGS TWINE TWINS TWIRL TWIST TWITS TYING TYKES TYPED TYPES
TYROS TZARS
UDDER ULCER ULTRA UMBRA UNAPT UNARM UNBAR UNCAP UNCLE UNDID UNDUE UNFED UNFIT
UNFIX UNIFY UNION UNITE UNITS UNITY UNLIT UNMAN UNMET UNPEG UNSET UNTIE UNTIL
UNWED UNZIP UPEND UPPED UPPER UPSET URBAN URGED URGES URINE USAGE USERS USHER
USING USUAL USURP USURY UTERI UTILE UTTER
VACUA VAGUE VAIRS VALES VALET VALID VALOR VALUE VALVE VAMPS VANES VAPID VAPOR
VAULT VAUNT VEERS VEILS VEINS VELAR VENAL VENDS VENOM VENTS VERBS VERGE VERSE
VERSO VERVE VERY' VESTS VETCH VETOS VEXED VEXES VIALS VIBES VICAR VIDEO VIEWS
VIGIL VIGOR VILER VILLA VINES VINYL VIPER VIRAL VIRUS VISAS VISED VISES VISIT
VISOR VISTA VITAL VIVID VIXEN VOCAL VODKA VOGUE VOICE VOIDS VOILE VOLES VOLTS
VOMIT VOTED VOTER VOTES VOUCH VOWED VOWEL VOWER VYING
WACKO WACKY WADED WADER WADES WAFER WAFTS WAGED WAGER WAGES WAGGY WAGON WAIFS
WAILS WAIST WAITS WAIVE WAKED WAKEN WAKER WAKES WALES WALKS WALLA WALLS WALTZ
WANDS WANED WANES WANNA WANTS WARDS WARES WARMS WARNS WARPS WARTS WARTY WARYS
WASHY WASPS WASTE WATCH WATER WATTS WAVED WAVER WAVES WAXED WAXEN WAXES WEALD
WEANS WEARS WEARY WEAVE WEBBY WEDGE WEEDS WEEDY WEEKS WEEPS WEEPY WEIGH WEIRD
WEIRS WELDS WELLS WELLY WELSH WELTS WENCH WHACK WHALE WHAMS WHANG WHARF WHEAL
WHEAT WHEEL WHELP WHENS WHEYS WHICH WHIFF WHILE WHIMS WHINE WHINY WHIPS WHIRL
WHIRR WHIRS WHISK WHIST WHITE WHITS WHOLE WHOMP WHOOP WHOPS WHORE WHORL WHOSE
WIDEN WIDER WIDOW WIDTH WIELD WIFEY WIGHT WILDS WILES WILLS WILLY WILTS WIMPS
WIMPY WINCE WINCH WINDS WINDY WINED WINES WINGS WINKS WINOS WIPED WIPES WIRED
WIRES WIRRY WISER WISES WISPS WISPY WISTS WITCH WITHE WITHY WIVES WOKEN WOLFS
WOMAN WOMBS WOMEN WONKS WONKY WOODS WOODY WOOED WOOER WOOLS WOOLY WORDS WORDY
WORLD WORMS WORMY WORRY WORSE WORST WORTH WOULD WOUND WOVEN WRACK WRAPS WRATH
WREAK WRECK WRENS WREST WRING WRIST WRITE WRITS WROTE WROTH WRUNG WRYLY
XENON XERIC X-RAY XYLEM
YACHT YACKS YANKS YARDS YARNS YAWNS YEARN YEARS YEAST YELLS YELPS YETIS YIELD
YODEL YOGAS YOGIC YOGIN YOKEL YOKES YOLKS YOLKY YOURS YOUTH YOWLS YUCCA YUCKY
YULES YUMMY
ZEALS ZEBRA ZEROS ZESTS ZESTY ZILCH ZINCS ZINES ZINGS ZIPPY ZONAL ZONED ZONES
ZOOMS

ARIAS BELTS CHOIR CHORD DANCE FLUTE OPERA ORGAN PIANO SCENE SCORE SHOWS SOLOS
STAGE TANGO TENOR USHER VOICE WALTZ DIVAS PARTS PROPS SCRIM ENTER EXITS RANGE
HORNS HARPS DRUMS REEDS BATON PITCH ROBES THORN PERTH TIARA CROWN STARS TRAIL
TIMER OPERAS
`).toUpperCase().split(/\s+/).filter(w => /^[A-Z]{5}$/.test(w));
