/* Connections Grid — 3x3 puzzles.
   Each row and column is a CONSTRAINT. A cell is satisfied by an actor who
   meets BOTH the row and column constraint. Each actor can only be used once.

   The actor DB has been hand-curated. Players will type names that aren't
   in the DB — those are treated as "not recognized" rather than rejected.

   Verification: every cell in every puzzle below has at least one actor in
   the DB who satisfies both constraints. The preview/validate tool flags
   any cell with 0 valid actors.
*/

window.ConnectionsData = (function () {

  // ---------- Show sets (used by category constraints) ----------
  const SONDHEIM_SHOWS = new Set([
    "Sweeney Todd","Sunday in the Park with George","Into the Woods",
    "Company","Follies","A Little Night Music","Merrily We Roll Along",
    "Assassins","Passion","Pacific Overtures","Anyone Can Whistle"
  ]);

  const DISNEY_SHOWS = new Set([
    "Beauty and the Beast","The Lion King","Aida","Tarzan","Mary Poppins",
    "The Little Mermaid","Newsies","Aladdin","Frozen"
  ]);

  // Shows with 5,000+ original-run Broadway performances (closed) OR still
  // running long enough to clear that bar. Conservative list.
  const LONG_RUNNERS = new Set([
    "The Phantom of the Opera","Chicago","The Lion King","Cats","Wicked",
    "Les Misérables","A Chorus Line","Mamma Mia!","Beauty and the Beast",
    "Rent","The Book of Mormon"
  ]);

  // ---------- Actor DB ----------
  // Fields:
  //   shows:   Broadway productions the actor has appeared in (any run)
  //   obcOf:   Original Broadway Cast productions
  //   tony:    Won at least one competitive Tony Award
  //   screen:  Has a notable film or TV role
  //   grammy:  Has won a Grammy (incl. cast album wins)
  //   aliases: alternate spellings / common shortenings
  const ACTORS = [
    // -- existing 18 --
    { name: "Idina Menzel",            shows: ["Rent","Wicked","If/Then"],                                                                                   obcOf: ["Rent","Wicked","If/Then"], tony: true,  screen: true, grammy: true,  aliases: [] },
    { name: "Lin-Manuel Miranda",      shows: ["In the Heights","Hamilton"],                                                                                  obcOf: ["In the Heights","Hamilton"], tony: true, screen: true, grammy: true, aliases: ["lin manuel miranda"] },
    { name: "Leslie Odom Jr.",         shows: ["Hamilton","Rent"],                                                                                            obcOf: ["Hamilton"], tony: true, screen: true, grammy: true, aliases: ["leslie odom jr","leslie odom"] },
    { name: "Renée Elise Goldsberry",  shows: ["Hamilton","Rent","The Lion King","Good People"],                                                              obcOf: ["Hamilton"], tony: true, screen: true, grammy: true, aliases: ["renee elise goldsberry"] },
    { name: "Daveed Diggs",            shows: ["Hamilton"],                                                                                                   obcOf: ["Hamilton"], tony: true, screen: true, grammy: true, aliases: [] },
    { name: "Jonathan Groff",          shows: ["Spring Awakening","Hamilton","Hair","Merrily We Roll Along"],                                                 obcOf: ["Spring Awakening","Merrily We Roll Along"], tony: true, screen: true, grammy: false, aliases: [] },
    { name: "Phillipa Soo",            shows: ["Hamilton","The Great Comet","Amélie"],                                                                         obcOf: ["Hamilton","Amélie"], tony: false, screen: true, grammy: true, aliases: ["philippa soo"] },
    { name: "Christopher Jackson",     shows: ["In the Heights","Hamilton"],                                                                                  obcOf: ["In the Heights","Hamilton"], tony: false, screen: true, grammy: true, aliases: [] },
    { name: "Mandy Gonzalez",          shows: ["In the Heights","Hamilton","Wicked"],                                                                         obcOf: ["In the Heights"], tony: false, screen: true, grammy: false, aliases: [] },
    { name: "Kristin Chenoweth",       shows: ["Wicked","You're a Good Man, Charlie Brown","On the Twentieth Century","Promises Promises"],                  obcOf: ["Wicked"], tony: true, screen: true, grammy: false, aliases: [] },
    { name: "Norbert Leo Butz",        shows: ["Wicked","Dirty Rotten Scoundrels","Big Fish","Catch Me If You Can"],                                          obcOf: ["Dirty Rotten Scoundrels","Catch Me If You Can"], tony: true, screen: true, grammy: false, aliases: [] },
    { name: "Joel Grey",               shows: ["Cabaret","Wicked"],                                                                                            obcOf: ["Cabaret"], tony: true, screen: true, grammy: false, aliases: [] },
    { name: "Adam Pascal",             shows: ["Rent","Aida","Memphis","Chicago"],                                                                            obcOf: ["Rent","Aida"], tony: false, screen: true, grammy: false, aliases: [] },
    { name: "Anthony Rapp",            shows: ["Rent","If/Then","You're a Good Man, Charlie Brown"],                                                          obcOf: ["Rent","If/Then"], tony: false, screen: true, grammy: false, aliases: [] },
    { name: "Wilson Jermaine Heredia", shows: ["Rent"],                                                                                                       obcOf: ["Rent"], tony: true, screen: true, grammy: false, aliases: ["wilson heredia"] },
    { name: "Megan Hilty",             shows: ["Wicked","9 to 5","Noises Off"],                                                                                obcOf: ["9 to 5"], tony: false, screen: true, grammy: false, aliases: [] },
    { name: "Stephanie J. Block",      shows: ["Wicked","Falsettos","The Cher Show"],                                                                          obcOf: ["The Cher Show"], tony: true, screen: false, grammy: false, aliases: ["stephanie block"] },
    { name: "Aaron Tveit",             shows: ["Wicked","Catch Me If You Can","Next to Normal","Moulin Rouge!"],                                              obcOf: ["Catch Me If You Can","Moulin Rouge!","Next to Normal"], tony: true, screen: true, grammy: false, aliases: [] },

    // -- 20 new actors --
    { name: "Audra McDonald",          shows: ["Carousel","Ragtime","Marie Christine","Master Class","Lady Day at Emerson's Bar and Grill","The Gershwins' Porgy and Bess","Shuffle Along","A Raisin in the Sun","110 in the Shade","Frankie and Johnny in the Clair de Lune"], obcOf: ["Marie Christine","Lady Day at Emerson's Bar and Grill","Shuffle Along"], tony: true, screen: true, grammy: true, aliases: ["audra mcdonald"] },
    { name: "Patti LuPone",            shows: ["Evita","Anything Goes","Sunset Boulevard","Gypsy","Sweeney Todd","Company"],                                  obcOf: ["Evita"], tony: true, screen: true, grammy: true, aliases: ["patti lupone"] },
    { name: "Bernadette Peters",       shows: ["Sunday in the Park with George","Into the Woods","Annie Get Your Gun","Hello, Dolly!","Gypsy","A Little Night Music","Song and Dance","Mack and Mabel","Follies"], obcOf: ["Sunday in the Park with George","Into the Woods","Song and Dance","Mack and Mabel"], tony: true, screen: true, grammy: false, aliases: ["bernadette peters"] },
    { name: "Sutton Foster",           shows: ["Anything Goes","Thoroughly Modern Millie","The Music Man","Little Women","Shrek the Musical","Violet","Young Frankenstein"], obcOf: ["Thoroughly Modern Millie","Little Women","Shrek the Musical","Violet","Young Frankenstein"], tony: true, screen: true, grammy: false, aliases: ["sutton foster"] },
    { name: "Lea Salonga",             shows: ["Miss Saigon","Les Misérables","Flower Drum Song","Once on This Island","Here Lies Love","Allegiance"],         obcOf: ["Miss Saigon","Flower Drum Song","Allegiance","Here Lies Love"], tony: true, screen: true, grammy: false, aliases: ["lea salonga"] },
    { name: "Hugh Jackman",            shows: ["The Boy from Oz","The Music Man"],                                                                             obcOf: ["The Boy from Oz"], tony: true, screen: true, grammy: false, aliases: ["hugh jackman"] },
    { name: "Ben Platt",               shows: ["Dear Evan Hansen","Parade","The Book of Mormon"],                                                              obcOf: ["Dear Evan Hansen"], tony: true, screen: true, grammy: true, aliases: ["ben platt"] },
    { name: "Andrew Rannells",         shows: ["The Book of Mormon","Hairspray","Jersey Boys","Hedwig and the Angry Inch","Falsettos","The Boys in the Band"], obcOf: ["The Book of Mormon"], tony: false, screen: true, grammy: true, aliases: ["andrew rannells"] },
    { name: "Cynthia Erivo",           shows: ["The Color Purple"],                                                                                            obcOf: [], tony: true, screen: true, grammy: true, aliases: ["cynthia erivo"] },
    { name: "Sara Bareilles",          shows: ["Waitress","Into the Woods"],                                                                                    obcOf: [], tony: false, screen: true, grammy: true, aliases: ["sara bareilles"] },
    { name: "Jessie Mueller",          shows: ["Beautiful: The Carole King Musical","Waitress","Carousel","On a Clear Day You Can See Forever","The Mystery of Edwin Drood"], obcOf: ["Beautiful: The Carole King Musical","Waitress"], tony: true, screen: false, grammy: false, aliases: ["jessie mueller"] },
    { name: "Heather Headley",         shows: ["Aida","The Lion King","The Color Purple"],                                                                     obcOf: ["Aida","The Lion King"], tony: true, screen: true, grammy: true, aliases: ["heather headley"] },
    { name: "Chita Rivera",            shows: ["West Side Story","Bye Bye Birdie","Chicago","Sweet Charity","The Rink","Kiss of the Spider Woman","Nine","The Visit"], obcOf: ["West Side Story","Bye Bye Birdie","Chicago","The Rink","Kiss of the Spider Woman","The Visit"], tony: true, screen: true, grammy: false, aliases: ["chita rivera"] },
    { name: "Liza Minnelli",           shows: ["Flora the Red Menace","The Act","The Rink"],                                                                   obcOf: ["Flora the Red Menace","The Act","The Rink"], tony: true, screen: true, grammy: true, aliases: ["liza minnelli"] },
    { name: "Nathan Lane",             shows: ["Guys and Dolls","A Funny Thing Happened on the Way to the Forum","The Producers","The Frogs","The Iceman Cometh","Angels in America","The Nance"], obcOf: ["The Producers","The Frogs","The Nance"], tony: true, screen: true, grammy: false, aliases: ["nathan lane"] },
    { name: "Matthew Broderick",       shows: ["Brighton Beach Memoirs","How to Succeed in Business Without Really Trying","The Producers","The Odd Couple"], obcOf: ["Brighton Beach Memoirs","The Producers"], tony: true, screen: true, grammy: false, aliases: ["matthew broderick"] },
    { name: "Brian Stokes Mitchell",   shows: ["Ragtime","Kiss Me, Kate","Man of La Mancha","Women on the Verge of a Nervous Breakdown","Shuffle Along"],      obcOf: ["Ragtime"], tony: true, screen: true, grammy: false, aliases: ["brian stokes mitchell"] },
    { name: "Christine Ebersole",      shows: ["On the Twentieth Century","42nd Street","Grey Gardens","War Paint"],                                          obcOf: ["Grey Gardens","War Paint"], tony: true, screen: true, grammy: false, aliases: ["christine ebersole"] },
    { name: "Caissie Levy",            shows: ["Frozen","Wicked","Les Misérables","Hair","Hairspray","Ghost"],                                                obcOf: ["Frozen","Ghost"], tony: false, screen: false, grammy: false, aliases: ["caissie levy"] },
    { name: "Jeremy Jordan",           shows: ["Newsies","Bonnie & Clyde","West Side Story","Waitress","Rock of Ages"],                                       obcOf: ["Newsies","Bonnie & Clyde"], tony: false, screen: true, grammy: false, aliases: ["jeremy jordan"] }
  ];

  // ---------- Constraint catalog ----------
  const CONSTRAINTS = {
    // Specific-show constraints
    wicked:       { label: "Wicked",            test: a => a.shows.includes("Wicked") },
    hamilton:     { label: "Hamilton",          test: a => a.shows.includes("Hamilton") },
    rent:         { label: "Rent",              test: a => a.shows.includes("Rent") },
    inTheHeights: { label: "In the Heights",    test: a => a.shows.includes("In the Heights") },
    bookOfMormon: { label: "Book of Mormon",    test: a => a.shows.includes("The Book of Mormon") },

    // Category constraints
    sondheim:     { label: "Sondheim show",     test: a => a.shows.some(s => SONDHEIM_SHOWS.has(s)) },
    disney:       { label: "Disney show",       test: a => a.shows.some(s => DISNEY_SHOWS.has(s)) },
    longRunner:   { label: "5000+ perf run",    test: a => a.shows.some(s => LONG_RUNNERS.has(s)) },

    // Award / industry constraints
    tonyWinner:   { label: "Tony winner",       test: a => !!a.tony },
    originatedRole: { label: "OBC of any show", test: a => (a.obcOf || []).length > 0 },
    screenCredit: { label: "Film/TV credit",    test: a => !!a.screen },
    grammyWinner: { label: "Grammy winner",     test: a => !!a.grammy }
  };

  // ---------- Puzzles ----------
  const PUZZLES = [
    { id: 1, title: "Class of", rows: ["rent", "grammyWinner", "hamilton"], cols: ["screenCredit", "tonyWinner", "originatedRole"] },
    { id: 2, title: "Crossover", rows: ["hamilton", "grammyWinner", "screenCredit"], cols: ["longRunner", "rent", "inTheHeights"] },
    { id: 3, title: "Double Bill", rows: ["wicked", "sondheim", "grammyWinner"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 4, title: "Triple Threat", rows: ["rent", "longRunner", "disney"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 5, title: "The Long Run", rows: ["hamilton", "rent", "longRunner"], cols: ["grammyWinner", "screenCredit", "tonyWinner"] },
    { id: 6, title: "Opening Night", rows: ["wicked", "sondheim", "longRunner"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 7, title: "Standing Room Only", rows: ["grammyWinner", "hamilton", "originatedRole"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 8, title: "Curtain Up", rows: ["tonyWinner", "hamilton", "originatedRole"], cols: ["grammyWinner", "screenCredit", "longRunner"] },
    { id: 9, title: "Ensemble", rows: ["longRunner", "disney", "grammyWinner"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 10, title: "Understudies", rows: ["tonyWinner", "originatedRole", "rent"], cols: ["grammyWinner", "screenCredit", "disney"] },
    { id: 11, title: "Headliners", rows: ["hamilton", "originatedRole", "screenCredit"], cols: ["grammyWinner", "rent", "longRunner"] },
    { id: 12, title: "Marquee Names", rows: ["hamilton", "screenCredit", "grammyWinner"], cols: ["originatedRole", "rent", "tonyWinner"] },
    { id: 13, title: "Two Shows a Day", rows: ["screenCredit", "hamilton", "originatedRole"], cols: ["inTheHeights", "longRunner", "grammyWinner"] },
    { id: 14, title: "Eleven O'Clock", rows: ["hamilton", "grammyWinner", "originatedRole"], cols: ["inTheHeights", "longRunner", "tonyWinner"] },
    { id: 15, title: "Act One", rows: ["rent", "hamilton", "disney"], cols: ["tonyWinner", "originatedRole", "grammyWinner"] },
    { id: 16, title: "Act Two", rows: ["hamilton", "longRunner", "sondheim"], cols: ["originatedRole", "tonyWinner", "screenCredit"] },
    { id: 17, title: "Intermission", rows: ["hamilton", "screenCredit", "grammyWinner"], cols: ["originatedRole", "longRunner", "inTheHeights"] },
    { id: 18, title: "Stage Left", rows: ["rent", "wicked", "grammyWinner"], cols: ["screenCredit", "originatedRole", "longRunner"] },
    { id: 19, title: "Stage Right", rows: ["rent", "hamilton", "disney"], cols: ["originatedRole", "screenCredit", "grammyWinner"] },
    { id: 20, title: "Center Stage", rows: ["disney", "rent", "tonyWinner"], cols: ["originatedRole", "screenCredit", "longRunner"] },
    { id: 21, title: "The Revival", rows: ["screenCredit", "disney", "sondheim"], cols: ["originatedRole", "grammyWinner", "tonyWinner"] },
    { id: 22, title: "Limited Engagement", rows: ["screenCredit", "rent", "disney"], cols: ["tonyWinner", "longRunner", "originatedRole"] },
    { id: 23, title: "Sold Out", rows: ["rent", "longRunner", "hamilton"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 24, title: "Encore", rows: ["longRunner", "grammyWinner", "rent"], cols: ["screenCredit", "originatedRole", "disney"] },
    { id: 25, title: "Bows", rows: ["longRunner", "rent", "disney"], cols: ["tonyWinner", "originatedRole", "grammyWinner"] },
    { id: 26, title: "Tony Bait", rows: ["screenCredit", "rent", "grammyWinner"], cols: ["originatedRole", "tonyWinner", "disney"] },
    { id: 27, title: "Dressing Room", rows: ["disney", "longRunner", "hamilton"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 28, title: "The Pit", rows: ["hamilton", "originatedRole", "grammyWinner"], cols: ["screenCredit", "longRunner", "rent"] },
    { id: 29, title: "Downstage", rows: ["tonyWinner", "originatedRole", "disney"], cols: ["screenCredit", "grammyWinner", "longRunner"] },
    { id: 30, title: "Upstage", rows: ["longRunner", "grammyWinner", "rent"], cols: ["screenCredit", "tonyWinner", "disney"] },
    { id: 31, title: "Class of", rows: ["hamilton", "longRunner", "originatedRole"], cols: ["screenCredit", "grammyWinner", "tonyWinner"] },
    { id: 32, title: "Crossover", rows: ["inTheHeights", "longRunner", "tonyWinner"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 33, title: "Double Bill", rows: ["hamilton", "originatedRole", "screenCredit"], cols: ["longRunner", "tonyWinner", "rent"] },
    { id: 34, title: "Triple Threat", rows: ["inTheHeights", "sondheim", "hamilton"], cols: ["originatedRole", "screenCredit", "grammyWinner"] },
    { id: 35, title: "The Long Run", rows: ["rent", "sondheim", "disney"], cols: ["tonyWinner", "grammyWinner", "originatedRole"] },
    { id: 36, title: "Opening Night", rows: ["disney", "originatedRole", "hamilton"], cols: ["rent", "longRunner", "grammyWinner"] },
    { id: 37, title: "Standing Room Only", rows: ["disney", "originatedRole", "hamilton"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 38, title: "Curtain Up", rows: ["hamilton", "rent", "tonyWinner"], cols: ["originatedRole", "grammyWinner", "longRunner"] },
    { id: 39, title: "Ensemble", rows: ["longRunner", "hamilton", "tonyWinner"], cols: ["screenCredit", "originatedRole", "rent"] },
    { id: 40, title: "Understudies", rows: ["sondheim", "disney", "hamilton"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 41, title: "Headliners", rows: ["screenCredit", "hamilton", "tonyWinner"], cols: ["grammyWinner", "longRunner", "rent"] },
    { id: 42, title: "Marquee Names", rows: ["inTheHeights", "disney", "longRunner"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 43, title: "Two Shows a Day", rows: ["rent", "screenCredit", "longRunner"], cols: ["disney", "grammyWinner", "tonyWinner"] },
    { id: 44, title: "Eleven O'Clock", rows: ["grammyWinner", "disney", "hamilton"], cols: ["tonyWinner", "screenCredit", "longRunner"] },
    { id: 45, title: "Act One", rows: ["screenCredit", "rent", "grammyWinner"], cols: ["originatedRole", "disney", "longRunner"] },
    { id: 46, title: "Act Two", rows: ["originatedRole", "hamilton", "screenCredit"], cols: ["rent", "inTheHeights", "grammyWinner"] },
    { id: 47, title: "Intermission", rows: ["rent", "hamilton", "sondheim"], cols: ["tonyWinner", "grammyWinner", "originatedRole"] },
    { id: 48, title: "Stage Left", rows: ["tonyWinner", "longRunner", "hamilton"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 49, title: "Stage Right", rows: ["longRunner", "rent", "tonyWinner"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 50, title: "Center Stage", rows: ["grammyWinner", "longRunner", "rent"], cols: ["disney", "tonyWinner", "originatedRole"] },
    { id: 51, title: "The Revival", rows: ["hamilton", "longRunner", "sondheim"], cols: ["originatedRole", "screenCredit", "grammyWinner"] },
    { id: 52, title: "Limited Engagement", rows: ["rent", "originatedRole", "longRunner"], cols: ["grammyWinner", "disney", "screenCredit"] },
    { id: 53, title: "Sold Out", rows: ["tonyWinner", "grammyWinner", "rent"], cols: ["screenCredit", "disney", "longRunner"] },
    { id: 54, title: "Encore", rows: ["longRunner", "disney", "sondheim"], cols: ["grammyWinner", "screenCredit", "tonyWinner"] },
    { id: 55, title: "Bows", rows: ["tonyWinner", "originatedRole", "hamilton"], cols: ["grammyWinner", "rent", "screenCredit"] },
    { id: 56, title: "Tony Bait", rows: ["disney", "longRunner", "sondheim"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 57, title: "Dressing Room", rows: ["hamilton", "longRunner", "rent"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 58, title: "The Pit", rows: ["rent", "inTheHeights", "hamilton"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 59, title: "Downstage", rows: ["rent", "wicked", "sondheim"], cols: ["screenCredit", "tonyWinner", "originatedRole"] },
    { id: 60, title: "Upstage", rows: ["inTheHeights", "rent", "longRunner"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 61, title: "Class of", rows: ["tonyWinner", "originatedRole", "hamilton"], cols: ["rent", "grammyWinner", "longRunner"] },
    { id: 62, title: "Crossover", rows: ["rent", "disney", "wicked"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 63, title: "Double Bill", rows: ["hamilton", "sondheim", "grammyWinner"], cols: ["tonyWinner", "originatedRole", "screenCredit"] },
    { id: 64, title: "Triple Threat", rows: ["hamilton", "originatedRole", "grammyWinner"], cols: ["longRunner", "screenCredit", "inTheHeights"] },
    { id: 65, title: "The Long Run", rows: ["originatedRole", "hamilton", "screenCredit"], cols: ["inTheHeights", "grammyWinner", "tonyWinner"] },
    { id: 66, title: "Opening Night", rows: ["rent", "disney", "tonyWinner"], cols: ["grammyWinner", "longRunner", "screenCredit"] },
    { id: 67, title: "Standing Room Only", rows: ["longRunner", "hamilton", "disney"], cols: ["screenCredit", "grammyWinner", "rent"] },
    { id: 68, title: "Curtain Up", rows: ["originatedRole", "hamilton", "grammyWinner"], cols: ["longRunner", "rent", "inTheHeights"] },
    { id: 69, title: "Ensemble", rows: ["rent", "wicked", "grammyWinner"], cols: ["tonyWinner", "originatedRole", "longRunner"] },
    { id: 70, title: "Understudies", rows: ["hamilton", "screenCredit", "longRunner"], cols: ["originatedRole", "tonyWinner", "grammyWinner"] },
    { id: 71, title: "Headliners", rows: ["sondheim", "disney", "rent"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 72, title: "Marquee Names", rows: ["grammyWinner", "hamilton", "screenCredit"], cols: ["longRunner", "inTheHeights", "tonyWinner"] },
    { id: 73, title: "Two Shows a Day", rows: ["originatedRole", "rent", "disney"], cols: ["longRunner", "screenCredit", "tonyWinner"] },
    { id: 74, title: "Eleven O'Clock", rows: ["hamilton", "grammyWinner", "wicked"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 75, title: "Act One", rows: ["hamilton", "inTheHeights", "tonyWinner"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 76, title: "Act Two", rows: ["wicked", "disney", "tonyWinner"], cols: ["longRunner", "originatedRole", "screenCredit"] },
    { id: 77, title: "Intermission", rows: ["hamilton", "originatedRole", "screenCredit"], cols: ["tonyWinner", "grammyWinner", "longRunner"] },
    { id: 78, title: "Stage Left", rows: ["disney", "hamilton", "screenCredit"], cols: ["originatedRole", "grammyWinner", "rent"] },
    { id: 79, title: "Stage Right", rows: ["disney", "tonyWinner", "hamilton"], cols: ["screenCredit", "rent", "originatedRole"] },
    { id: 80, title: "Center Stage", rows: ["grammyWinner", "rent", "wicked"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 81, title: "The Revival", rows: ["tonyWinner", "wicked", "hamilton"], cols: ["screenCredit", "originatedRole", "longRunner"] },
    { id: 82, title: "Limited Engagement", rows: ["wicked", "hamilton", "rent"], cols: ["originatedRole", "tonyWinner", "longRunner"] },
    { id: 83, title: "Sold Out", rows: ["grammyWinner", "hamilton", "originatedRole"], cols: ["inTheHeights", "tonyWinner", "screenCredit"] },
    { id: 84, title: "Encore", rows: ["hamilton", "wicked", "longRunner"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 85, title: "Bows", rows: ["grammyWinner", "screenCredit", "disney"], cols: ["originatedRole", "longRunner", "tonyWinner"] },
    { id: 86, title: "Tony Bait", rows: ["wicked", "rent", "originatedRole"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 87, title: "Dressing Room", rows: ["screenCredit", "wicked", "disney"], cols: ["originatedRole", "tonyWinner", "longRunner"] },
    { id: 88, title: "The Pit", rows: ["hamilton", "disney", "screenCredit"], cols: ["tonyWinner", "longRunner", "grammyWinner"] },
    { id: 89, title: "Downstage", rows: ["disney", "hamilton", "longRunner"], cols: ["grammyWinner", "rent", "tonyWinner"] },
    { id: 90, title: "Upstage", rows: ["originatedRole", "screenCredit", "hamilton"], cols: ["tonyWinner", "rent", "grammyWinner"] },
    { id: 91, title: "Class of", rows: ["grammyWinner", "disney", "hamilton"], cols: ["rent", "screenCredit", "originatedRole"] },
    { id: 92, title: "Crossover", rows: ["originatedRole", "longRunner", "disney"], cols: ["screenCredit", "tonyWinner", "grammyWinner"] },
    { id: 93, title: "Double Bill", rows: ["wicked", "rent", "hamilton"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 94, title: "Triple Threat", rows: ["wicked", "screenCredit", "grammyWinner"], cols: ["longRunner", "tonyWinner", "originatedRole"] },
    { id: 95, title: "The Long Run", rows: ["longRunner", "hamilton", "disney"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 96, title: "Opening Night", rows: ["grammyWinner", "longRunner", "rent"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 97, title: "Standing Room Only", rows: ["tonyWinner", "hamilton", "disney"], cols: ["originatedRole", "rent", "longRunner"] },
    { id: 98, title: "Curtain Up", rows: ["longRunner", "sondheim", "rent"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 99, title: "Ensemble", rows: ["hamilton", "tonyWinner", "disney"], cols: ["grammyWinner", "rent", "longRunner"] },
    { id: 100, title: "Understudies", rows: ["sondheim", "hamilton", "rent"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 101, title: "Headliners", rows: ["rent", "grammyWinner", "hamilton"], cols: ["tonyWinner", "longRunner", "originatedRole"] },
    { id: 102, title: "Marquee Names", rows: ["disney", "hamilton", "grammyWinner"], cols: ["tonyWinner", "longRunner", "rent"] },
    { id: 103, title: "Two Shows a Day", rows: ["sondheim", "disney", "longRunner"], cols: ["originatedRole", "tonyWinner", "screenCredit"] },
    { id: 104, title: "Eleven O'Clock", rows: ["grammyWinner", "rent", "originatedRole"], cols: ["disney", "screenCredit", "tonyWinner"] },
    { id: 105, title: "Act One", rows: ["longRunner", "hamilton", "disney"], cols: ["rent", "screenCredit", "originatedRole"] },
    { id: 106, title: "Act Two", rows: ["rent", "originatedRole", "disney"], cols: ["screenCredit", "longRunner", "grammyWinner"] },
    { id: 107, title: "Intermission", rows: ["inTheHeights", "rent", "disney"], cols: ["screenCredit", "grammyWinner", "originatedRole"] },
    { id: 108, title: "Stage Left", rows: ["sondheim", "rent", "originatedRole"], cols: ["screenCredit", "tonyWinner", "grammyWinner"] },
    { id: 109, title: "Stage Right", rows: ["originatedRole", "hamilton", "grammyWinner"], cols: ["rent", "inTheHeights", "tonyWinner"] },
    { id: 110, title: "Center Stage", rows: ["screenCredit", "rent", "hamilton"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 111, title: "The Revival", rows: ["screenCredit", "hamilton", "tonyWinner"], cols: ["originatedRole", "longRunner", "rent"] },
    { id: 112, title: "Limited Engagement", rows: ["hamilton", "originatedRole", "screenCredit"], cols: ["tonyWinner", "longRunner", "inTheHeights"] },
    { id: 113, title: "Sold Out", rows: ["screenCredit", "hamilton", "longRunner"], cols: ["tonyWinner", "rent", "originatedRole"] },
    { id: 114, title: "Encore", rows: ["originatedRole", "disney", "hamilton"], cols: ["longRunner", "screenCredit", "grammyWinner"] },
    { id: 115, title: "Bows", rows: ["hamilton", "rent", "originatedRole"], cols: ["screenCredit", "grammyWinner", "longRunner"] },
    { id: 116, title: "Tony Bait", rows: ["grammyWinner", "disney", "originatedRole"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 117, title: "Dressing Room", rows: ["hamilton", "disney", "screenCredit"], cols: ["originatedRole", "tonyWinner", "rent"] },
    { id: 118, title: "The Pit", rows: ["hamilton", "disney", "sondheim"], cols: ["screenCredit", "tonyWinner", "grammyWinner"] },
    { id: 119, title: "Downstage", rows: ["rent", "longRunner", "sondheim"], cols: ["tonyWinner", "grammyWinner", "screenCredit"] },
    { id: 120, title: "Upstage", rows: ["screenCredit", "grammyWinner", "hamilton"], cols: ["tonyWinner", "originatedRole", "longRunner"] },
    { id: 121, title: "Class of", rows: ["longRunner", "rent", "screenCredit"], cols: ["originatedRole", "tonyWinner", "disney"] },
    { id: 122, title: "Crossover", rows: ["disney", "screenCredit", "hamilton"], cols: ["longRunner", "originatedRole", "rent"] },
    { id: 123, title: "Double Bill", rows: ["rent", "longRunner", "hamilton"], cols: ["originatedRole", "grammyWinner", "tonyWinner"] },
    { id: 124, title: "Triple Threat", rows: ["originatedRole", "disney", "hamilton"], cols: ["screenCredit", "longRunner", "rent"] },
    { id: 125, title: "The Long Run", rows: ["screenCredit", "hamilton", "disney"], cols: ["rent", "longRunner", "grammyWinner"] },
    { id: 126, title: "Opening Night", rows: ["disney", "hamilton", "originatedRole"], cols: ["rent", "grammyWinner", "screenCredit"] },
    { id: 127, title: "Standing Room Only", rows: ["rent", "longRunner", "originatedRole"], cols: ["tonyWinner", "disney", "grammyWinner"] },
    { id: 128, title: "Curtain Up", rows: ["screenCredit", "hamilton", "disney"], cols: ["grammyWinner", "tonyWinner", "rent"] },
    { id: 129, title: "Ensemble", rows: ["tonyWinner", "disney", "hamilton"], cols: ["grammyWinner", "originatedRole", "longRunner"] },
    { id: 130, title: "Understudies", rows: ["grammyWinner", "wicked", "disney"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 131, title: "Headliners", rows: ["hamilton", "disney", "screenCredit"], cols: ["tonyWinner", "longRunner", "originatedRole"] },
    { id: 132, title: "Marquee Names", rows: ["hamilton", "screenCredit", "grammyWinner"], cols: ["originatedRole", "longRunner", "rent"] },
    { id: 133, title: "Two Shows a Day", rows: ["disney", "wicked", "hamilton"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 134, title: "Eleven O'Clock", rows: ["sondheim", "rent", "hamilton"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 135, title: "Act One", rows: ["sondheim", "longRunner", "screenCredit"], cols: ["originatedRole", "tonyWinner", "grammyWinner"] },
    { id: 136, title: "Act Two", rows: ["rent", "wicked", "screenCredit"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 137, title: "Intermission", rows: ["originatedRole", "grammyWinner", "rent"], cols: ["tonyWinner", "disney", "longRunner"] },
    { id: 138, title: "Stage Left", rows: ["originatedRole", "grammyWinner", "hamilton"], cols: ["rent", "longRunner", "tonyWinner"] },
    { id: 139, title: "Stage Right", rows: ["rent", "disney", "tonyWinner"], cols: ["screenCredit", "grammyWinner", "originatedRole"] },
    { id: 140, title: "Center Stage", rows: ["disney", "tonyWinner", "hamilton"], cols: ["screenCredit", "rent", "longRunner"] },
    { id: 141, title: "The Revival", rows: ["grammyWinner", "rent", "disney"], cols: ["longRunner", "tonyWinner", "screenCredit"] },
    { id: 142, title: "Limited Engagement", rows: ["rent", "hamilton", "screenCredit"], cols: ["tonyWinner", "originatedRole", "grammyWinner"] },
    { id: 143, title: "Sold Out", rows: ["disney", "rent", "screenCredit"], cols: ["tonyWinner", "grammyWinner", "originatedRole"] },
    { id: 144, title: "Encore", rows: ["screenCredit", "hamilton", "longRunner"], cols: ["originatedRole", "grammyWinner", "rent"] },
    { id: 145, title: "Bows", rows: ["longRunner", "rent", "screenCredit"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 146, title: "Tony Bait", rows: ["longRunner", "tonyWinner", "hamilton"], cols: ["originatedRole", "grammyWinner", "rent"] },
    { id: 147, title: "Dressing Room", rows: ["disney", "originatedRole", "wicked"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 148, title: "The Pit", rows: ["longRunner", "sondheim", "disney"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 149, title: "Downstage", rows: ["hamilton", "sondheim", "tonyWinner"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 150, title: "Upstage", rows: ["disney", "hamilton", "sondheim"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 151, title: "Class of", rows: ["disney", "hamilton", "originatedRole"], cols: ["longRunner", "tonyWinner", "grammyWinner"] },
    { id: 152, title: "Crossover", rows: ["disney", "wicked", "sondheim"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 153, title: "Double Bill", rows: ["wicked", "disney", "rent"], cols: ["longRunner", "originatedRole", "screenCredit"] },
    { id: 154, title: "Triple Threat", rows: ["tonyWinner", "rent", "originatedRole"], cols: ["disney", "grammyWinner", "longRunner"] },
    { id: 155, title: "The Long Run", rows: ["sondheim", "tonyWinner", "rent"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 156, title: "Opening Night", rows: ["originatedRole", "disney", "hamilton"], cols: ["tonyWinner", "rent", "longRunner"] },
    { id: 157, title: "Standing Room Only", rows: ["screenCredit", "tonyWinner", "rent"], cols: ["originatedRole", "longRunner", "grammyWinner"] },
    { id: 158, title: "Curtain Up", rows: ["sondheim", "longRunner", "rent"], cols: ["screenCredit", "originatedRole", "tonyWinner"] },
    { id: 159, title: "Ensemble", rows: ["longRunner", "screenCredit", "hamilton"], cols: ["rent", "grammyWinner", "tonyWinner"] },
    { id: 160, title: "Understudies", rows: ["disney", "rent", "longRunner"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 161, title: "Headliners", rows: ["grammyWinner", "disney", "rent"], cols: ["longRunner", "screenCredit", "originatedRole"] },
    { id: 162, title: "Marquee Names", rows: ["rent", "screenCredit", "originatedRole"], cols: ["disney", "longRunner", "tonyWinner"] },
    { id: 163, title: "Two Shows a Day", rows: ["hamilton", "tonyWinner", "screenCredit"], cols: ["rent", "grammyWinner", "originatedRole"] },
    { id: 164, title: "Eleven O'Clock", rows: ["hamilton", "originatedRole", "grammyWinner"], cols: ["inTheHeights", "rent", "screenCredit"] },
    { id: 165, title: "Act One", rows: ["tonyWinner", "wicked", "grammyWinner"], cols: ["screenCredit", "longRunner", "originatedRole"] },
    { id: 166, title: "Act Two", rows: ["rent", "hamilton", "disney"], cols: ["originatedRole", "grammyWinner", "longRunner"] },
    { id: 167, title: "Intermission", rows: ["hamilton", "disney", "sondheim"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 168, title: "Stage Left", rows: ["grammyWinner", "disney", "tonyWinner"], cols: ["originatedRole", "screenCredit", "longRunner"] },
    { id: 169, title: "Stage Right", rows: ["rent", "hamilton", "grammyWinner"], cols: ["longRunner", "originatedRole", "screenCredit"] },
    { id: 170, title: "Center Stage", rows: ["rent", "tonyWinner", "inTheHeights"], cols: ["screenCredit", "grammyWinner", "originatedRole"] },
    { id: 171, title: "The Revival", rows: ["hamilton", "disney", "longRunner"], cols: ["tonyWinner", "rent", "originatedRole"] },
    { id: 172, title: "Limited Engagement", rows: ["tonyWinner", "hamilton", "screenCredit"], cols: ["grammyWinner", "originatedRole", "longRunner"] },
    { id: 173, title: "Sold Out", rows: ["tonyWinner", "rent", "screenCredit"], cols: ["disney", "originatedRole", "grammyWinner"] },
    { id: 174, title: "Encore", rows: ["rent", "tonyWinner", "disney"], cols: ["grammyWinner", "longRunner", "originatedRole"] },
    { id: 175, title: "Bows", rows: ["longRunner", "rent", "sondheim"], cols: ["originatedRole", "screenCredit", "grammyWinner"] },
    { id: 176, title: "Tony Bait", rows: ["rent", "disney", "screenCredit"], cols: ["grammyWinner", "originatedRole", "longRunner"] },
    { id: 177, title: "Dressing Room", rows: ["rent", "disney", "hamilton"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 178, title: "The Pit", rows: ["sondheim", "disney", "grammyWinner"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 179, title: "Downstage", rows: ["screenCredit", "originatedRole", "rent"], cols: ["longRunner", "grammyWinner", "disney"] },
    { id: 180, title: "Upstage", rows: ["inTheHeights", "tonyWinner", "disney"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 181, title: "Class of", rows: ["disney", "hamilton", "tonyWinner"], cols: ["screenCredit", "longRunner", "grammyWinner"] },
    { id: 182, title: "Crossover", rows: ["disney", "hamilton", "longRunner"], cols: ["rent", "originatedRole", "grammyWinner"] },
    { id: 183, title: "Double Bill", rows: ["rent", "wicked", "hamilton"], cols: ["screenCredit", "longRunner", "originatedRole"] },
    { id: 184, title: "Triple Threat", rows: ["tonyWinner", "originatedRole", "rent"], cols: ["screenCredit", "disney", "longRunner"] },
    { id: 185, title: "The Long Run", rows: ["rent", "longRunner", "originatedRole"], cols: ["grammyWinner", "tonyWinner", "screenCredit"] },
    { id: 186, title: "Opening Night", rows: ["wicked", "grammyWinner", "hamilton"], cols: ["longRunner", "tonyWinner", "originatedRole"] },
    { id: 187, title: "Standing Room Only", rows: ["rent", "disney", "hamilton"], cols: ["tonyWinner", "screenCredit", "grammyWinner"] },
    { id: 188, title: "Curtain Up", rows: ["rent", "wicked", "longRunner"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 189, title: "Ensemble", rows: ["hamilton", "rent", "disney"], cols: ["originatedRole", "screenCredit", "longRunner"] },
    { id: 190, title: "Understudies", rows: ["tonyWinner", "rent", "originatedRole"], cols: ["screenCredit", "grammyWinner", "longRunner"] },
    { id: 191, title: "Headliners", rows: ["sondheim", "longRunner", "inTheHeights"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 192, title: "Marquee Names", rows: ["hamilton", "disney", "tonyWinner"], cols: ["originatedRole", "rent", "grammyWinner"] },
    { id: 193, title: "Two Shows a Day", rows: ["disney", "hamilton", "longRunner"], cols: ["tonyWinner", "screenCredit", "rent"] },
    { id: 194, title: "Eleven O'Clock", rows: ["hamilton", "grammyWinner", "tonyWinner"], cols: ["originatedRole", "rent", "longRunner"] },
    { id: 195, title: "Act One", rows: ["longRunner", "rent", "screenCredit"], cols: ["disney", "grammyWinner", "originatedRole"] },
    { id: 196, title: "Act Two", rows: ["tonyWinner", "rent", "wicked"], cols: ["screenCredit", "longRunner", "originatedRole"] },
    { id: 197, title: "Intermission", rows: ["hamilton", "rent", "screenCredit"], cols: ["longRunner", "grammyWinner", "originatedRole"] },
    { id: 198, title: "Stage Left", rows: ["disney", "sondheim", "rent"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 199, title: "Stage Right", rows: ["longRunner", "screenCredit", "disney"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 200, title: "Center Stage", rows: ["hamilton", "rent", "originatedRole"], cols: ["tonyWinner", "grammyWinner", "screenCredit"] },
    { id: 201, title: "The Revival", rows: ["screenCredit", "hamilton", "grammyWinner"], cols: ["inTheHeights", "tonyWinner", "originatedRole"] },
    { id: 202, title: "Limited Engagement", rows: ["sondheim", "inTheHeights", "rent"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 203, title: "Sold Out", rows: ["longRunner", "disney", "hamilton"], cols: ["originatedRole", "tonyWinner", "grammyWinner"] },
    { id: 204, title: "Encore", rows: ["grammyWinner", "originatedRole", "rent"], cols: ["screenCredit", "disney", "longRunner"] },
    { id: 205, title: "Bows", rows: ["rent", "grammyWinner", "disney"], cols: ["tonyWinner", "longRunner", "originatedRole"] },
    { id: 206, title: "Tony Bait", rows: ["disney", "rent", "screenCredit"], cols: ["grammyWinner", "longRunner", "tonyWinner"] },
    { id: 207, title: "Dressing Room", rows: ["sondheim", "tonyWinner", "longRunner"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 208, title: "The Pit", rows: ["rent", "hamilton", "disney"], cols: ["originatedRole", "longRunner", "tonyWinner"] },
    { id: 209, title: "Downstage", rows: ["sondheim", "rent", "disney"], cols: ["tonyWinner", "screenCredit", "grammyWinner"] },
    { id: 210, title: "Upstage", rows: ["tonyWinner", "originatedRole", "hamilton"], cols: ["longRunner", "screenCredit", "rent"] },
    { id: 211, title: "Class of", rows: ["hamilton", "longRunner", "inTheHeights"], cols: ["grammyWinner", "screenCredit", "originatedRole"] },
    { id: 212, title: "Crossover", rows: ["grammyWinner", "wicked", "disney"], cols: ["longRunner", "screenCredit", "originatedRole"] },
    { id: 213, title: "Double Bill", rows: ["grammyWinner", "disney", "hamilton"], cols: ["rent", "longRunner", "originatedRole"] },
    { id: 214, title: "Triple Threat", rows: ["grammyWinner", "disney", "hamilton"], cols: ["tonyWinner", "originatedRole", "rent"] },
    { id: 215, title: "The Long Run", rows: ["tonyWinner", "inTheHeights", "sondheim"], cols: ["screenCredit", "grammyWinner", "originatedRole"] },
    { id: 216, title: "Opening Night", rows: ["grammyWinner", "hamilton", "disney"], cols: ["rent", "longRunner", "screenCredit"] },
    { id: 217, title: "Standing Room Only", rows: ["rent", "sondheim", "screenCredit"], cols: ["grammyWinner", "originatedRole", "tonyWinner"] },
    { id: 218, title: "Curtain Up", rows: ["hamilton", "screenCredit", "wicked"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 219, title: "Ensemble", rows: ["hamilton", "originatedRole", "longRunner"], cols: ["screenCredit", "tonyWinner", "rent"] },
    { id: 220, title: "Understudies", rows: ["originatedRole", "hamilton", "longRunner"], cols: ["screenCredit", "rent", "grammyWinner"] },
    { id: 221, title: "Headliners", rows: ["longRunner", "hamilton", "sondheim"], cols: ["originatedRole", "tonyWinner", "grammyWinner"] },
    { id: 222, title: "Marquee Names", rows: ["grammyWinner", "longRunner", "hamilton"], cols: ["tonyWinner", "originatedRole", "rent"] },
    { id: 223, title: "Two Shows a Day", rows: ["screenCredit", "grammyWinner", "hamilton"], cols: ["tonyWinner", "rent", "longRunner"] },
    { id: 224, title: "Eleven O'Clock", rows: ["tonyWinner", "longRunner", "rent"], cols: ["grammyWinner", "originatedRole", "disney"] },
    { id: 225, title: "Act One", rows: ["wicked", "grammyWinner", "disney"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 226, title: "Act Two", rows: ["longRunner", "rent", "disney"], cols: ["grammyWinner", "tonyWinner", "screenCredit"] },
    { id: 227, title: "Intermission", rows: ["longRunner", "rent", "tonyWinner"], cols: ["disney", "grammyWinner", "screenCredit"] },
    { id: 228, title: "Stage Left", rows: ["hamilton", "tonyWinner", "rent"], cols: ["screenCredit", "originatedRole", "longRunner"] },
    { id: 229, title: "Stage Right", rows: ["hamilton", "grammyWinner", "disney"], cols: ["screenCredit", "tonyWinner", "rent"] },
    { id: 230, title: "Center Stage", rows: ["hamilton", "sondheim", "wicked"], cols: ["screenCredit", "tonyWinner", "originatedRole"] },
    { id: 231, title: "The Revival", rows: ["grammyWinner", "rent", "sondheim"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 232, title: "Limited Engagement", rows: ["hamilton", "wicked", "grammyWinner"], cols: ["originatedRole", "screenCredit", "tonyWinner"] },
    { id: 233, title: "Sold Out", rows: ["rent", "originatedRole", "hamilton"], cols: ["longRunner", "grammyWinner", "tonyWinner"] },
    { id: 234, title: "Encore", rows: ["tonyWinner", "rent", "hamilton"], cols: ["longRunner", "screenCredit", "grammyWinner"] },
    { id: 235, title: "Bows", rows: ["sondheim", "inTheHeights", "disney"], cols: ["originatedRole", "grammyWinner", "screenCredit"] },
    { id: 236, title: "Tony Bait", rows: ["tonyWinner", "grammyWinner", "rent"], cols: ["originatedRole", "longRunner", "disney"] },
    { id: 237, title: "Dressing Room", rows: ["hamilton", "wicked", "originatedRole"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 238, title: "The Pit", rows: ["grammyWinner", "hamilton", "disney"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 239, title: "Downstage", rows: ["screenCredit", "disney", "originatedRole"], cols: ["longRunner", "grammyWinner", "tonyWinner"] },
    { id: 240, title: "Upstage", rows: ["disney", "longRunner", "wicked"], cols: ["tonyWinner", "originatedRole", "screenCredit"] },
    { id: 241, title: "Class of", rows: ["hamilton", "rent", "grammyWinner"], cols: ["longRunner", "tonyWinner", "screenCredit"] },
    { id: 242, title: "Crossover", rows: ["originatedRole", "hamilton", "rent"], cols: ["screenCredit", "tonyWinner", "longRunner"] },
    { id: 243, title: "Double Bill", rows: ["screenCredit", "grammyWinner", "hamilton"], cols: ["inTheHeights", "originatedRole", "rent"] },
    { id: 244, title: "Triple Threat", rows: ["screenCredit", "disney", "hamilton"], cols: ["rent", "tonyWinner", "longRunner"] },
    { id: 245, title: "The Long Run", rows: ["rent", "hamilton", "disney"], cols: ["longRunner", "tonyWinner", "screenCredit"] },
    { id: 246, title: "Opening Night", rows: ["hamilton", "disney", "grammyWinner"], cols: ["screenCredit", "originatedRole", "longRunner"] },
    { id: 247, title: "Standing Room Only", rows: ["hamilton", "tonyWinner", "disney"], cols: ["longRunner", "screenCredit", "originatedRole"] },
    { id: 248, title: "Curtain Up", rows: ["disney", "rent", "wicked"], cols: ["screenCredit", "longRunner", "tonyWinner"] },
    { id: 249, title: "Ensemble", rows: ["tonyWinner", "hamilton", "longRunner"], cols: ["rent", "grammyWinner", "screenCredit"] },
    { id: 250, title: "Understudies", rows: ["rent", "screenCredit", "grammyWinner"], cols: ["tonyWinner", "disney", "longRunner"] },
    { id: 251, title: "Headliners", rows: ["rent", "originatedRole", "grammyWinner"], cols: ["screenCredit", "longRunner", "tonyWinner"] },
    { id: 252, title: "Marquee Names", rows: ["screenCredit", "grammyWinner", "hamilton"], cols: ["inTheHeights", "tonyWinner", "rent"] },
    { id: 253, title: "Two Shows a Day", rows: ["rent", "tonyWinner", "screenCredit"], cols: ["disney", "originatedRole", "longRunner"] },
    { id: 254, title: "Eleven O'Clock", rows: ["tonyWinner", "disney", "sondheim"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 255, title: "Act One", rows: ["rent", "screenCredit", "originatedRole"], cols: ["grammyWinner", "longRunner", "tonyWinner"] },
    { id: 256, title: "Act Two", rows: ["originatedRole", "disney", "rent"], cols: ["tonyWinner", "grammyWinner", "screenCredit"] },
    { id: 257, title: "Intermission", rows: ["originatedRole", "hamilton", "screenCredit"], cols: ["tonyWinner", "rent", "inTheHeights"] },
    { id: 258, title: "Stage Left", rows: ["wicked", "disney", "hamilton"], cols: ["tonyWinner", "longRunner", "originatedRole"] },
    { id: 259, title: "Stage Right", rows: ["longRunner", "tonyWinner", "disney"], cols: ["screenCredit", "grammyWinner", "originatedRole"] },
    { id: 260, title: "Center Stage", rows: ["disney", "tonyWinner", "hamilton"], cols: ["screenCredit", "grammyWinner", "rent"] },
    { id: 261, title: "The Revival", rows: ["originatedRole", "longRunner", "rent"], cols: ["tonyWinner", "disney", "screenCredit"] },
    { id: 262, title: "Limited Engagement", rows: ["disney", "hamilton", "grammyWinner"], cols: ["originatedRole", "tonyWinner", "screenCredit"] },
    { id: 263, title: "Sold Out", rows: ["rent", "grammyWinner", "wicked"], cols: ["longRunner", "screenCredit", "tonyWinner"] },
    { id: 264, title: "Encore", rows: ["disney", "wicked", "rent"], cols: ["longRunner", "originatedRole", "tonyWinner"] },
    { id: 265, title: "Bows", rows: ["tonyWinner", "screenCredit", "disney"], cols: ["originatedRole", "grammyWinner", "longRunner"] },
    { id: 266, title: "Tony Bait", rows: ["wicked", "hamilton", "disney"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 267, title: "Dressing Room", rows: ["originatedRole", "disney", "hamilton"], cols: ["rent", "screenCredit", "tonyWinner"] },
    { id: 268, title: "The Pit", rows: ["rent", "screenCredit", "hamilton"], cols: ["tonyWinner", "longRunner", "grammyWinner"] },
    { id: 269, title: "Downstage", rows: ["tonyWinner", "hamilton", "grammyWinner"], cols: ["rent", "originatedRole", "screenCredit"] },
    { id: 270, title: "Upstage", rows: ["rent", "disney", "hamilton"], cols: ["tonyWinner", "longRunner", "grammyWinner"] },
    { id: 271, title: "Class of", rows: ["hamilton", "originatedRole", "screenCredit"], cols: ["longRunner", "inTheHeights", "rent"] },
    { id: 272, title: "Crossover", rows: ["grammyWinner", "longRunner", "wicked"], cols: ["tonyWinner", "originatedRole", "screenCredit"] },
    { id: 273, title: "Double Bill", rows: ["longRunner", "hamilton", "grammyWinner"], cols: ["tonyWinner", "screenCredit", "rent"] },
    { id: 274, title: "Triple Threat", rows: ["hamilton", "disney", "originatedRole"], cols: ["rent", "grammyWinner", "tonyWinner"] },
    { id: 275, title: "The Long Run", rows: ["grammyWinner", "disney", "wicked"], cols: ["tonyWinner", "screenCredit", "originatedRole"] },
    { id: 276, title: "Opening Night", rows: ["originatedRole", "rent", "screenCredit"], cols: ["grammyWinner", "tonyWinner", "disney"] },
    { id: 277, title: "Standing Room Only", rows: ["originatedRole", "hamilton", "grammyWinner"], cols: ["tonyWinner", "rent", "screenCredit"] },
    { id: 278, title: "Curtain Up", rows: ["disney", "screenCredit", "hamilton"], cols: ["longRunner", "originatedRole", "grammyWinner"] },
    { id: 279, title: "Ensemble", rows: ["hamilton", "rent", "wicked"], cols: ["originatedRole", "tonyWinner", "screenCredit"] },
    { id: 280, title: "Understudies", rows: ["disney", "hamilton", "tonyWinner"], cols: ["screenCredit", "originatedRole", "grammyWinner"] },
    { id: 281, title: "Headliners", rows: ["sondheim", "originatedRole", "longRunner"], cols: ["grammyWinner", "tonyWinner", "screenCredit"] },
    { id: 282, title: "Marquee Names", rows: ["hamilton", "sondheim", "screenCredit"], cols: ["originatedRole", "tonyWinner", "grammyWinner"] },
    { id: 283, title: "Two Shows a Day", rows: ["longRunner", "tonyWinner", "rent"], cols: ["disney", "screenCredit", "originatedRole"] },
    { id: 284, title: "Eleven O'Clock", rows: ["screenCredit", "rent", "grammyWinner"], cols: ["tonyWinner", "originatedRole", "longRunner"] },
    { id: 285, title: "Act One", rows: ["grammyWinner", "tonyWinner", "hamilton"], cols: ["rent", "screenCredit", "longRunner"] },
    { id: 286, title: "Act Two", rows: ["hamilton", "disney", "screenCredit"], cols: ["grammyWinner", "tonyWinner", "originatedRole"] },
    { id: 287, title: "Intermission", rows: ["rent", "hamilton", "tonyWinner"], cols: ["grammyWinner", "originatedRole", "screenCredit"] },
    { id: 288, title: "Stage Left", rows: ["grammyWinner", "wicked", "hamilton"], cols: ["originatedRole", "screenCredit", "longRunner"] },
    { id: 289, title: "Stage Right", rows: ["originatedRole", "disney", "rent"], cols: ["longRunner", "grammyWinner", "tonyWinner"] },
    { id: 290, title: "Center Stage", rows: ["rent", "disney", "hamilton"], cols: ["screenCredit", "grammyWinner", "longRunner"] },
    { id: 291, title: "The Revival", rows: ["disney", "hamilton", "longRunner"], cols: ["tonyWinner", "grammyWinner", "screenCredit"] },
    { id: 292, title: "Limited Engagement", rows: ["grammyWinner", "tonyWinner", "hamilton"], cols: ["longRunner", "screenCredit", "originatedRole"] },
    { id: 293, title: "Sold Out", rows: ["hamilton", "disney", "originatedRole"], cols: ["tonyWinner", "screenCredit", "grammyWinner"] },
    { id: 294, title: "Encore", rows: ["rent", "sondheim", "hamilton"], cols: ["tonyWinner", "screenCredit", "grammyWinner"] },
    { id: 295, title: "Bows", rows: ["disney", "hamilton", "inTheHeights"], cols: ["originatedRole", "screenCredit", "grammyWinner"] },
    { id: 296, title: "Tony Bait", rows: ["grammyWinner", "longRunner", "hamilton"], cols: ["originatedRole", "screenCredit", "rent"] },
    { id: 297, title: "Dressing Room", rows: ["grammyWinner", "wicked", "originatedRole"], cols: ["tonyWinner", "longRunner", "screenCredit"] },
    { id: 298, title: "The Pit", rows: ["rent", "tonyWinner", "grammyWinner"], cols: ["screenCredit", "originatedRole", "disney"] },
    { id: 299, title: "Downstage", rows: ["rent", "grammyWinner", "tonyWinner"], cols: ["originatedRole", "screenCredit", "longRunner"] },
    { id: 300, title: "Upstage", rows: ["disney", "grammyWinner", "rent"], cols: ["originatedRole", "tonyWinner", "screenCredit"] },
    { id: 301, title: "Class of", rows: ["screenCredit", "tonyWinner", "rent"], cols: ["grammyWinner", "disney", "longRunner"] },
    { id: 302, title: "Crossover", rows: ["hamilton", "originatedRole", "longRunner"], cols: ["tonyWinner", "rent", "grammyWinner"] },
    { id: 303, title: "Double Bill", rows: ["disney", "sondheim", "originatedRole"], cols: ["grammyWinner", "screenCredit", "tonyWinner"] },
    { id: 304, title: "Triple Threat", rows: ["longRunner", "sondheim", "hamilton"], cols: ["screenCredit", "tonyWinner", "grammyWinner"] },
    { id: 305, title: "The Long Run", rows: ["hamilton", "longRunner", "grammyWinner"], cols: ["tonyWinner", "originatedRole", "screenCredit"] },
    { id: 306, title: "Opening Night", rows: ["disney", "hamilton", "wicked"], cols: ["screenCredit", "longRunner", "originatedRole"] },
    { id: 307, title: "Standing Room Only", rows: ["hamilton", "originatedRole", "sondheim"], cols: ["grammyWinner", "screenCredit", "tonyWinner"] },
    { id: 308, title: "Curtain Up", rows: ["sondheim", "longRunner", "grammyWinner"], cols: ["tonyWinner", "screenCredit", "originatedRole"] }
  ];

  return { ACTORS, CONSTRAINTS, PUZZLES };
})();
