/* Marquee — the namesake headliner.
   Daily puzzle = a Broadway title up in lights, letters scrambled. The player
   rearranges the bulbs to spell the title.

   This is a GENERATABLE game: the daily scramble is derived from dayIndex, so
   the only content is this title list. Add titles to extend the rotation —
   the game auto-handles word structure, scrambling, and slots.

   Guidelines for entries:
   - `title`: the real, display-cased title. Letters + spaces solve cleanly;
     punctuation (! , ' -) is stripped for the letter tiles but kept in display.
   - Keep solvable: <= ~16 letters and <= 4 words works best.
   - `hint`: short, spoiler-light category/vibe (no need for hard facts).
   - `difficulty`: 1 easy · 2 medium · 3 hard (length/obscurity).
*/
window.MarqueeTitles = [
  { id: 1,  title: "Wicked",              hint: "Two witches of Oz",                 difficulty: 1 },
  { id: 2,  title: "Hamilton",            hint: "Founding father, hip-hop",          difficulty: 1 },
  { id: 3,  title: "Cats",                hint: "Jellicle felines",                  difficulty: 1 },
  { id: 4,  title: "Rent",                hint: "525,600 minutes",                   difficulty: 1 },
  { id: 5,  title: "Chicago",             hint: "Razzle dazzle, merry murderesses",  difficulty: 1 },
  { id: 6,  title: "Hadestown",           hint: "Way down under the ground",         difficulty: 2 },
  { id: 7,  title: "Annie",               hint: "Tomorrow, tomorrow",                difficulty: 1 },
  { id: 8,  title: "Oklahoma",            hint: "Where the wind comes sweeping",     difficulty: 2 },
  { id: 9,  title: "Carousel",            hint: "Rodgers & Hammerstein carnival",    difficulty: 2 },
  { id: 10, title: "Pippin",             hint: "Magic to do, a Fosse classic",      difficulty: 2 },
  { id: 11, title: "Gypsy",               hint: "Everything's coming up roses",      difficulty: 1 },
  { id: 12, title: "Company",             hint: "Bobby, being alive",                difficulty: 2 },
  { id: 13, title: "Follies",             hint: "Sondheim, faded showgirls",         difficulty: 2 },
  { id: 14, title: "Cabaret",             hint: "Life is a... at the Kit Kat Klub",  difficulty: 2 },
  { id: 15, title: "Hair",                hint: "The tribal love-rock musical",      difficulty: 1 },
  { id: 16, title: "Grease",              hint: "Rydell High, summer nights",        difficulty: 1 },
  { id: 17, title: "Newsies",             hint: "Seize the day, paper boys",         difficulty: 2 },
  { id: 18, title: "Aida",                hint: "Elton John, Egypt",                 difficulty: 1 },
  { id: 19, title: "Waitress",            hint: "Sara Bareilles, sugar & butter",    difficulty: 2 },
  { id: 20, title: "Six",                 hint: "Henry VIII's queens, pop concert",  difficulty: 1 },
  { id: 21, title: "Once",                hint: "Guy, Girl, and a guitar",           difficulty: 1 },
  { id: 22, title: "Falsettos",           hint: "A tight-knit family, William Finn", difficulty: 3 },
  { id: 23, title: "Ragtime",             hint: "Turn-of-the-century America",       difficulty: 2 },
  { id: 24, title: "Parade",              hint: "Jason Robert Brown, a trial",       difficulty: 2 },
  { id: 25, title: "Sweeney Todd",        hint: "The demon barber of Fleet Street",  difficulty: 3 },
  { id: 26, title: "Into the Woods",      hint: "Sondheim's tangled fairy tales",    difficulty: 3 },
  { id: 27, title: "Les Miserables",      hint: "Do you hear the people sing?",      difficulty: 3 },
  { id: 28, title: "Miss Saigon",         hint: "A helicopter, a love story",        difficulty: 3 },
  { id: 29, title: "Mamma Mia",           hint: "ABBA jukebox on a Greek isle",      difficulty: 2 },
  { id: 30, title: "Jersey Boys",         hint: "The Four Seasons' story",           difficulty: 2 },
  { id: 31, title: "Kinky Boots",         hint: "Cyndi Lauper, a shoe factory",      difficulty: 2 },
  { id: 32, title: "Beetlejuice",         hint: "The ghost with the most",           difficulty: 3 },
  { id: 33, title: "Spamalot",            hint: "Monty Python on Broadway",          difficulty: 2 },
  { id: 34, title: "Avenue Q",            hint: "Puppets, but very adult",           difficulty: 2 },
  { id: 35, title: "Matilda",             hint: "Roald Dahl, a gifted girl",         difficulty: 2 },
  { id: 36, title: "Frozen",              hint: "Let it go",                         difficulty: 1 },
  { id: 37, title: "Aladdin",             hint: "A whole new world",                 difficulty: 1 },
  { id: 38, title: "Tarzan",              hint: "Phil Collins, the jungle",          difficulty: 1 },
  { id: 39, title: "The Lion King",       hint: "Hakuna matata",                     difficulty: 2 },
  { id: 40, title: "The Producers",       hint: "Springtime for a flop-turned-hit",  difficulty: 3 },
  { id: 41, title: "The Wiz",             hint: "Ease on down the road",             difficulty: 1 },
  { id: 42, title: "Dear Evan Hansen",    hint: "Waving through a window",           difficulty: 3 },
  { id: 43, title: "Spring Awakening",    hint: "Teen angst, Duncan Sheik",          difficulty: 3 },
  { id: 44, title: "Next to Normal",      hint: "A family and mental illness",       difficulty: 3 },
  { id: 45, title: "In the Heights",      hint: "Washington Heights, Miranda",       difficulty: 3 },
  { id: 46, title: "Bring It On",         hint: "Cheerleading musical",              difficulty: 2 },
  { id: 47, title: "Cinderella",          hint: "A glass slipper, R&H",              difficulty: 2 },
  { id: 48, title: "Pajama Game",         hint: "A factory romance, Adler & Ross",   difficulty: 2 },
  { id: 49, title: "Damn Yankees",        hint: "A deal with the devil for baseball",difficulty: 3 },
  { id: 50, title: "Funny Girl",          hint: "Fanny Brice, don't rain on...",     difficulty: 2 },
  { id: 51, title: "Sunset Boulevard",    hint: "Norma Desmond's close-up",          difficulty: 3 },
  { id: 52, title: "Evita",               hint: "Don't cry for me...",               difficulty: 1 },
  { id: 53, title: "Camelot",             hint: "Lerner & Loewe, King Arthur",       difficulty: 2 },
  { id: 54, title: "Brigadoon",           hint: "A village that wakes once a century",difficulty: 3 },
  { id: 55, title: "Hairspray",           hint: "Good morning, Baltimore",           difficulty: 2 },
  { id: 56, title: "Memphis",             hint: "Early rock and roll radio",         difficulty: 2 },
  { id: 57, title: "Come From Away",      hint: "Gander welcomes the world",         difficulty: 3 },
  { id: 58, title: "The Color Purple",    hint: "Alice Walker, Celie's journey",     difficulty: 3 },
  { id: 59, title: "Bandstand",           hint: "Post-WWII swing band",              difficulty: 2 },
  { id: 60, title: "Tootsie",             hint: "An actor in disguise",              difficulty: 2 },
  { id: 61, title: "Anastasia",           hint: "A lost Russian princess",           difficulty: 2 },
  { id: 62, title: "Amelie",              hint: "A whimsical Parisian",              difficulty: 2 },
  { id: 63, title: "Bonnie and Clyde",    hint: "Depression-era outlaws",            difficulty: 3 },
  { id: 64, title: "Big Fish",            hint: "A father's tall tales",             difficulty: 2 },
  { id: 65, title: "Shrek",               hint: "An ogre's swamp",                   difficulty: 1 },
  { id: 66, title: "Tina",                hint: "Simply the best",                   difficulty: 1 },
  { id: 67, title: "Beautiful",           hint: "The Carole King musical",           difficulty: 2 },
  { id: 68, title: "On the Town",         hint: "Three sailors, 24 hours in NYC",    difficulty: 2 },
  { id: 69, title: "Kiss Me Kate",        hint: "Cole Porter meets Shakespeare",     difficulty: 3 },
  { id: 70, title: "Guys and Dolls",      hint: "Gamblers and a mission doll",       difficulty: 3 },

  { id: 71,  title: "A Chorus Line",        hint: "One singular sensation — dancers audition", difficulty: 2 },
  { id: 72,  title: "West Side Story",      hint: "Jets vs. Sharks; a Romeo & Juliet retelling", difficulty: 2 },
  { id: 73,  title: "The Sound of Music",   hint: "Do-Re-Mi in the Austrian Alps",     difficulty: 2 },
  { id: 74,  title: "Fiddler on the Roof",  hint: "Tradition! in the village of Anatevka", difficulty: 3 },
  { id: 75,  title: "My Fair Lady",         hint: "The rain in Spain; Eliza Doolittle", difficulty: 2 },
  { id: 76,  title: "South Pacific",        hint: "Some enchanted evening",            difficulty: 2 },
  { id: 77,  title: "The King and I",       hint: "Shall we dance, in old Siam",       difficulty: 2 },
  { id: 78,  title: "Show Boat",            hint: "Ol' Man River on the Mississippi",  difficulty: 2 },
  { id: 79,  title: "Anything Goes",        hint: "Cole Porter aboard an ocean liner", difficulty: 2 },
  { id: 80,  title: "Hello Dolly",          hint: "Matchmaker Dolly Levi returns",     difficulty: 2 },
  { id: 81,  title: "Dreamgirls",           hint: "A '60s girl group on the rise",     difficulty: 2 },
  { id: 82,  title: "Sweet Charity",        hint: "Hey, big spender; a Fosse dance hall", difficulty: 2 },
  { id: 83,  title: "Assassins",            hint: "Sondheim; those who shot at presidents", difficulty: 3 },
  { id: 84,  title: "Titanic",              hint: "The 1997 Best Musical aboard the doomed ship", difficulty: 2 },
  { id: 85,  title: "Fun Home",             hint: "Alison Bechdel's graphic-novel memoir", difficulty: 2 },
  { id: 86,  title: "The Band's Visit",     hint: "An Egyptian band stranded in an Israeli town", difficulty: 3 },
  { id: 87,  title: "Moulin Rouge",         hint: "Jukebox spectacle in a Paris nightclub", difficulty: 2 },
  { id: 88,  title: "Mean Girls",           hint: "So fetch; high-school cliques",     difficulty: 2 },
  { id: 89,  title: "Some Like It Hot",     hint: "Two musicians on the run, in disguise", difficulty: 3 },
  { id: 90,  title: "Legally Blonde",       hint: "Elle Woods takes on Harvard Law",   difficulty: 2 },
  { id: 91,  title: "Heathers",             hint: "A pitch-black '80s teen comedy",    difficulty: 2 },
  { id: 92,  title: "The Addams Family",    hint: "They're creepy and they're kooky",  difficulty: 2 },
  { id: 93,  title: "Urinetown",            hint: "A gleeful satire of a pay-to-pee dystopia", difficulty: 3 },
  { id: 94,  title: "Sister Act",           hint: "A lounge singer hides out in a convent", difficulty: 2 },
  { id: 95,  title: "Ghost",                hint: "Unchained melody and a pottery wheel", difficulty: 1 },
  { id: 96,  title: "American Idiot",       hint: "Green Day's punk-rock musical",     difficulty: 2 },
  { id: 97,  title: "Rock of Ages",         hint: "An '80s hair-metal jukebox",        difficulty: 2 },
  { id: 98,  title: "Tommy",                hint: "The Who's pinball wizard",          difficulty: 1 },
  { id: 99,  title: "Motown",               hint: "The Berry Gordy jukebox musical",   difficulty: 2 },
  { id: 100, title: "Jagged Little Pill",   hint: "Built on Alanis Morissette's album", difficulty: 3 },
  { id: 101, title: "SpongeBob",            hint: "Bikini Bottom comes to Broadway",   difficulty: 2 },
  { id: 102, title: "Pretty Woman",         hint: "The Rodeo Drive rom-com, sung",     difficulty: 2 },
  { id: 103, title: "Back to the Future",   hint: "88 miles per hour in a DeLorean",   difficulty: 3 },
  { id: 104, title: "Mrs Doubtfire",        hint: "A father disguised as a nanny",     difficulty: 2 },
  { id: 105, title: "A Strange Loop",       hint: "A Pulitzer-winning meta-musical",   difficulty: 3 },
  { id: 106, title: "The Book of Mormon",   hint: "Two missionaries sent to Uganda",   difficulty: 3 },
  { id: 107, title: "Once on This Island",  hint: "A Caribbean fairy tale; Ahrens & Flaherty", difficulty: 3 },
  { id: 108, title: "Crazy for You",        hint: "Gershwin tunes; 'I Got Rhythm'",    difficulty: 2 },
  { id: 109, title: "Godspell",             hint: "Parables and 'Day by Day'",         difficulty: 2 },
  { id: 110, title: "Mame",                 hint: "An eccentric aunt throws open the windows", difficulty: 2 },
  { id: 111, title: "Applause",             hint: "Backstage drama from 'All About Eve'", difficulty: 2 },
  { id: 112, title: "Carrie",               hint: "The notorious prom-night cult musical", difficulty: 3 },
  { id: 113, title: "Passion",              hint: "Sondheim; an obsessive love",       difficulty: 3 },
  { id: 114, title: "Nine",                 hint: "A film director and the women in his life", difficulty: 2 },
  { id: 115, title: "City of Angels",       hint: "A film-noir-within-a-musical",      difficulty: 2 },
  { id: 116, title: "The Wedding Singer",   hint: "An '80s rom-com at the reception",  difficulty: 2 },
  { id: 117, title: "Catch Me If You Can",  hint: "A teenage con artist on the run",   difficulty: 3 },
  { id: 118, title: "If/Then",              hint: "Two parallel lives; Idina Menzel",  difficulty: 2 },
  { id: 119, title: "The Last Five Years",  hint: "A romance told from both ends at once", difficulty: 3 },
  { id: 120, title: "Bright Star",          hint: "Bluegrass; Steve Martin & Edie Brickell", difficulty: 2 },
  { id: 121, title: "Violet",               hint: "A bus trip to a faith healer",      difficulty: 2 },
  { id: 122, title: "Grey Gardens",         hint: "The reclusive Beales of East Hampton", difficulty: 2 },
  { id: 123, title: "War Paint",            hint: "Rubinstein vs. Arden, cosmetics rivals", difficulty: 3 },
  { id: 124, title: "Allegiance",           hint: "A Japanese-American internment story", difficulty: 2 },
  { id: 125, title: "Side Show",            hint: "Conjoined-twin performers",         difficulty: 2 },
  { id: 126, title: "Pal Joey",             hint: "A Rodgers & Hart nightclub heel",   difficulty: 2 },
  { id: 127, title: "The Full Monty",       hint: "Laid-off men become strippers",     difficulty: 2 },
  { id: 128, title: "Xanadu",               hint: "Roller disco and a Greek muse",     difficulty: 2 },
  { id: 129, title: "Footloose",            hint: "A town that outlawed dancing",      difficulty: 1 },
  { id: 130, title: "Flashdance",           hint: "What a feeling — a welder who dances", difficulty: 2 },
  { id: 131, title: "Children of Eden",     hint: "Schwartz sets the book of Genesis", difficulty: 2 },
  { id: 132, title: "Jekyll & Hyde",        hint: "A doctor and his murderous other half", difficulty: 2 },
  { id: 133, title: "Dracula",              hint: "The count, as a musical",           difficulty: 2 },
  { id: 134, title: "Tuck Everlasting",     hint: "A family that never grows old",     difficulty: 2 },
  { id: 135, title: "Bye Bye Birdie",       hint: "An Elvis-like idol gets drafted",   difficulty: 2 },
  { id: 136, title: "Wonderful Town",       hint: "Two sisters loose in Greenwich Village", difficulty: 2 },
  { id: 137, title: "Finian's Rainbow",     hint: "A leprechaun chases a stolen pot of gold", difficulty: 3 },
  { id: 138, title: "Promises Promises",    hint: "Bacharach; based on 'The Apartment'", difficulty: 2 },
  { id: 139, title: "She Loves Me",         hint: "Feuding clerks who are secret pen pals", difficulty: 2 },
  { id: 140, title: "Bells Are Ringing",    hint: "An answering-service operator meddles in love", difficulty: 3 },
  { id: 141, title: "Honeymoon in Vegas",   hint: "A high-stakes card game over a fiancée", difficulty: 3 },
  { id: 142, title: "First Date",           hint: "A blind date unfolds in real time", difficulty: 2 },
  { id: 143, title: "Big",                  hint: "A kid wishes himself grown-up overnight", difficulty: 1 },
  { id: 144, title: "Honk",                 hint: "An ugly-duckling musical",          difficulty: 2 },
  { id: 145, title: "The Scottsboro Boys",  hint: "Kander & Ebb; a 1930s injustice",   difficulty: 3 },
  { id: 146, title: "Caroline or Change",   hint: "Tony Kushner; a maid in 1963 Louisiana", difficulty: 3 },
  { id: 147, title: "Floyd Collins",        hint: "A man trapped in a Kentucky cave",  difficulty: 3 },
  { id: 148, title: "Songs for a New World", hint: "A Jason Robert Brown song cycle",  difficulty: 3 },
  { id: 149, title: "Jelly's Last Jam",     hint: "Jelly Roll Morton's jazz life",     difficulty: 3 },
  { id: 150, title: "The Prom",             hint: "Broadway divas crash a small-town prom", difficulty: 2 }
];
